/*********************************************************************************//*!
*   \file           T1_config.h
*
*   \brief          generated by T1_projGen.pl for project customer T1 project
*                   using license POT3726 - LicID1353
*
*   \par Visibility
*                   External
*
*   \date           on 12.09.2025 at 16:52:54
*
*   \copyright GLIWA GmbH embedded systems, Weilheim i.OB. All rights reserved
*************************************************************************************/

/*************************************************************************************
 * Command line flags:
 *********************
 -UserCfg=T1_UserCfg.inv
 -Cfg=T1_Cfg.inv
 -OsPm=T1_neusarOS.pm
 -OsCfg=T1_OsCfg.inv
 ************************************************************************************/

#ifndef T1_CONFIG_H_
#define T1_CONFIG_H_ (1)

/*----------------------------------------------------------------------------------*/
/*--- Global macros ----------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/



/*----------------------------------------------------------------------------------*/
/*--- header includes --------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/



/*----------------------------------------------------------------------------------*/
/*--- Task and ISR IDs -------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#define T1_Default_Init_Task_Core0_ID                 (  0u)
#define T1_Idle_Task_Core0_ID                         (  1u)
#define T1_Task_Init_Core0_QM_ID                      (  2u)
#define T1_Task_10ms_Core0_QM_ID                      (  3u)
#define T1_Task_20ms_Core0_QM_ID                      (  4u)
#define T1_Task_50ms_Core0_QM_ID                      (  5u)
#define T1_Task_100ms_Core0_QM_ID                     (  6u)
#define T1_Task_200ms_Core0_QM_ID                     (  7u)
#define T1_Task_500ms_Core0_QM_ID                     (  8u)
#define T1_Task_1000ms_Core0_QM_ID                    (  9u)
#define T1_Task_2ms_Core0_QM_ID                       ( 10u)
#define T1_Default_Init_Task_Core1_ID                 ( 11u)
#define T1_Idle_Task_Core1_ID                         ( 12u)
#define T1_Task_Init_Core1_QM_ID                      ( 13u)
#define T1_Task_5ms_Core1_QM_ID                       ( 14u)
#define T1_Task_10ms_Core1_QM_ID                      ( 15u)
#define T1_Task_20ms_Core1_QM_ID                      ( 16u)
#define T1_Task_50ms_Core1_QM_ID                      ( 17u)
#define T1_Task_100ms_Core1_QM_ID                     ( 18u)
#define T1_Task_200ms_Core1_QM_ID                     ( 19u)
#define T1_Task_500ms_Core1_QM_ID                     ( 20u)
#define T1_Task_1000ms_Core1_QM_ID                    ( 21u)
#define T1_Default_Init_Task_Core2_ID                 ( 22u)
#define T1_Idle_Task_Core2_ID                         ( 23u)
#define T1_Task_Init_Core2_QM_ID                      ( 24u)
#define T1_Task_1ms_Core2_QM_ID                       ( 25u)
#define T1_Task_4ms_Core2_QM_ID                       ( 26u)
#define T1_Task_5ms_Core2_QM_ID                       ( 27u)
#define T1_Task_10ms_Core2_QM_ID                      ( 28u)
#define T1_Task_20ms_Core2_QM_ID                      ( 29u)
#define T1_Task_50ms_Core2_QM_ID                      ( 30u)
#define T1_Task_100ms_Core2_QM_ID                     ( 31u)
#define T1_Task_200ms_Core2_QM_ID                     ( 32u)
#define T1_Task_500ms_Core2_QM_ID                     ( 33u)
#define T1_Task_1000ms_Core2_QM_ID                    ( 34u)
#define T1_CounterIsr_SystemTimer_Core0_ID            ( 35u)
#define T1_MultiCommIsr_OsCore_Core0_ID               ( 36u)
#define T1_Os_Monitor_Isr_ID                          ( 37u)
#define T1_CounterIsr_SystemTimer_Core1_ID            ( 38u)
#define T1_MultiCommIsr_OsCore_Core1_ID               ( 39u)
#define T1_CounterIsr_SystemTimer_Core2_ID            ( 40u)
#define T1_MultiCommIsr_OsCore_Core2_ID               ( 41u)
#define T1_FlashDone_Isr_ID                           ( 42u)
#define T1_PIT0_CH4_ID                                ( 43u)
#define T1_PIT0_CH5_ID                                ( 44u)
#define T1_PIT0_CH6_ID                                ( 45u)
#define T1_Can1_Isr_ID                                ( 46u)
#define T1_Can2_Isr_ID                                ( 47u)
#define T1_Can3_Isr_ID                                ( 48u)
#define T1_Can4_Isr_ID                                ( 49u)
#define T1_Adc89_Grp0_Isr_ID                          ( 50u)
#define T1_Adc89_Grp1_Isr_ID                          ( 51u)
#define T1_Adc89_Grp2_Isr_ID                          ( 52u)
#define T1_Adc89_Grp3_Isr_ID                          ( 53u)
#define T1_Adc89_Grp4_Isr_ID                          ( 54u)
#define T1_Adc89_Grp5_Isr_ID                          ( 55u)
#define T1_CAT1_EDMA_Ch16_IRQHandler_ID               ( 64u)
#define T1_CAT1_EDMA_Ch1_IRQHandler_ID                ( 65u)
#define T1_CAT1_EDMA_Ch3_IRQHandler_ID                ( 66u)
#define T1_CAT1_GTM_ATOM10_ISRfunc_ID                 ( 67u)
/* Core 0: */
#define T1_NOF_TASKS_CORE0                            ( 68u)
#define T1_MAX_TASK_PREEMPTIONS_CORE0                 ( 20u)
#define T1_CAT1_ISR_ID_OFFSET_CORE0                   ( 38u)
#define T1_CAT2_ISR_ID_OFFSET_CORE0                   ( 35u)
#define T1_EXT_ISR_ID_OFFSET_CORE0                    ( 60u)
#define T1_CAT1_TO_TRACE_ID_CORE0( id_ )              (T1_CAT1_ISR_ID_OFFSET_CORE0 + (id_))
#define T1_CAT2_TO_TRACE_ID_CORE0( id_ )              (T1_CAT2_ISR_ID_OFFSET_CORE0 + (id_))
#define T1_EXT_ISR_TO_TRACE_ID_CORE0( id_ )           (T1_EXT_ISR_ID_OFFSET_CORE0 + (id_))
/* Core 1: */
#define T1_NOF_TASKS_CORE1                            ( 40u)
#define T1_MAX_TASK_PREEMPTIONS_CORE1                 ( 20u)
#define T1_CAT1_ISR_ID_OFFSET_CORE1                   ( 40u)
#define T1_CAT2_ISR_ID_OFFSET_CORE1                   ( 38u)
#define T1_EXT_ISR_ID_OFFSET_CORE1                    ( 40u)
#define T1_CAT1_TO_TRACE_ID_CORE1( id_ )              (T1_CAT1_ISR_ID_OFFSET_CORE1 + (id_))
#define T1_CAT2_TO_TRACE_ID_CORE1( id_ )              (T1_CAT2_ISR_ID_OFFSET_CORE1 + (id_))
#define T1_EXT_ISR_TO_TRACE_ID_CORE1( id_ )           (T1_EXT_ISR_ID_OFFSET_CORE1 + (id_))
/* Core 2: */
#define T1_NOF_TASKS_CORE2                            ( 56u)
#define T1_MAX_TASK_PREEMPTIONS_CORE2                 ( 20u)
#define T1_CAT1_ISR_ID_OFFSET_CORE2                   ( 56u)
#define T1_CAT2_ISR_ID_OFFSET_CORE2                   ( 40u)
#define T1_EXT_ISR_ID_OFFSET_CORE2                    ( 56u)
#define T1_CAT1_TO_TRACE_ID_CORE2( id_ )              (T1_CAT1_ISR_ID_OFFSET_CORE2 + (id_))
#define T1_CAT2_TO_TRACE_ID_CORE2( id_ )              (T1_CAT2_ISR_ID_OFFSET_CORE2 + (id_))
#define T1_EXT_ISR_TO_TRACE_ID_CORE2( id_ )           (T1_EXT_ISR_ID_OFFSET_CORE2 + (id_))

/*----------------------------------------------------------------------------------*/
/*--- Application Features ---------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#define T1_AF_TRACE_STARTUP                           (0x00000001uL) /* Capture Startup Trace */
#define T1_AF_ALLOW_TRIGGER                           (0x00000002uL) /* Allow on Target Trigger */
#define T1_AF_ALLOW_TRACEDATA                         (0x00000004uL) /* Allow T1 Trace Data */
#define T1_AF_CHECK_INTEGRATION                       (0x00000008uL) /* Trace the stopwatch T1_SW_CHECK_INTEGRATION_CORE_ALL */

/*----------------------------------------------------------------------------------*/
/*--- T1.delay IDs -----------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

/* Delays for all cores */
#define T1_DL_CHECK_INTEGRATION_CORE_ALL              (0u) /* Check Integration */

/* Delays for core 0 */
#define T1_DL_CHECK_INTEGRATION_CORE0                 (T1_DL_CHECK_INTEGRATION_CORE_ALL) /* Check Integration */

/* Delays for core 1 */
#define T1_DL_CHECK_INTEGRATION_CORE1                 (T1_DL_CHECK_INTEGRATION_CORE_ALL) /* Check Integration */

/* Delays for core 2 */
#define T1_DL_CHECK_INTEGRATION_CORE2                 (T1_DL_CHECK_INTEGRATION_CORE_ALL) /* Check Integration */

/*----------------------------------------------------------------------------------*/
/*--- User Data Event and User Event IDs -------------------------------------------*/
/*----------------------------------------------------------------------------------*/

/* User Events for all cores */
#define T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE_ALL   (0u) /* Check Integration Sync Timer Ticks */
#define T1_UDE_PRINTF_CORE_ALL                        (1u) /* printf string */
#define T1_UDE_16BitDataTrace_CORE_ALL                (2u) /* 16 bit Data tracing */
#define T1_UDE_32BitDataTrace_CORE_ALL                (3u) /* 32 bit Data tracing */
#define T1_UDE_BinaryTrace_CORE_ALL                   (4u) /* Binary Data tracing */
#define T1_UE_T1_CONT_ERR_CORE0                       (32u) /* T1.cont error callback for core 0 */
#define T1_UE_T1_CONT_ERR_CORE1                       (33u) /* T1.cont error callback for core 1 */
#define T1_UE_T1_CONT_ERR_CORE2                       (34u) /* T1.cont error callback for core 2 */
#define T1_UE_T1_CONT_ERR_CORE3                       (35u) /* T1.cont error callback for core 3 */
#define T1_UE_T1_CONT_ERR_CORE4                       (36u) /* T1.cont error callback for core 4 */
#define T1_UE_T1_CONT_ERR_CORE5                       (37u) /* T1.cont error callback for core 5 */
#define T1_UE_CPU_LOAD_CALLBACK_CORE0                 (38u) /* T1.cont CPU load callback for core 0 */
#define T1_UE_CPU_LOAD_CALLBACK_CORE1                 (39u) /* T1.cont CPU load callback for core 1 */
#define T1_UE_CPU_LOAD_CALLBACK_CORE2                 (40u) /* T1.cont CPU load callback for core 2 */
#define T1_UE_CPU_LOAD_CALLBACK_CORE3                 (41u) /* T1.cont CPU load callback for core 3 */
#define T1_UE_CPU_LOAD_CALLBACK_CORE4                 (42u) /* T1.cont CPU load callback for core 4 */
#define T1_UE_CPU_LOAD_CALLBACK_CORE5                 (43u) /* T1.cont CPU load callback for core 5 */
#define T1_UE_T1_ERR_CORE_ALL                         (44u) /* T1_errorCount Increase */
#define T1_UE_TRACE_DEBUG                             (45u) /* T1 trace debug */

/* User Events for core 0 */
#define T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE0      (T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE_ALL) /* Check Integration Sync Timer Ticks */
#define T1_UDE_PRINTF_CORE0                           (T1_UDE_PRINTF_CORE_ALL) /* printf string */
#define T1_UDE_16BitDataTrace_CORE0                   (T1_UDE_16BitDataTrace_CORE_ALL) /* 16 bit Data tracing */
#define T1_UDE_32BitDataTrace_CORE0                   (T1_UDE_32BitDataTrace_CORE_ALL) /* 32 bit Data tracing */
#define T1_UDE_BinaryTrace_CORE0                      (T1_UDE_BinaryTrace_CORE_ALL) /* Binary Data tracing */

/* User Events for core 1 */
#define T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE1      (T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE_ALL) /* Check Integration Sync Timer Ticks */
#define T1_UDE_PRINTF_CORE1                           (T1_UDE_PRINTF_CORE_ALL) /* printf string */
#define T1_UDE_16BitDataTrace_CORE1                   (T1_UDE_16BitDataTrace_CORE_ALL) /* 16 bit Data tracing */
#define T1_UDE_32BitDataTrace_CORE1                   (T1_UDE_32BitDataTrace_CORE_ALL) /* 32 bit Data tracing */
#define T1_UDE_BinaryTrace_CORE1                      (T1_UDE_BinaryTrace_CORE_ALL) /* Binary Data tracing */

/* User Events for core 2 */
#define T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE2      (T1_UDE_CHECK_INTEGRATION_SYNCTIMER_CORE_ALL) /* Check Integration Sync Timer Ticks */
#define T1_UDE_PRINTF_CORE2                           (T1_UDE_PRINTF_CORE_ALL) /* printf string */
#define T1_UDE_16BitDataTrace_CORE2                   (T1_UDE_16BitDataTrace_CORE_ALL) /* 16 bit Data tracing */
#define T1_UDE_32BitDataTrace_CORE2                   (T1_UDE_32BitDataTrace_CORE_ALL) /* 32 bit Data tracing */
#define T1_UDE_BinaryTrace_CORE2                      (T1_UDE_BinaryTrace_CORE_ALL) /* Binary Data tracing */

/*----------------------------------------------------------------------------------*/
/*--- User stopwatch IDs -----------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

/* User stopwatches for all cores */
/* The following user stopwatches are supervised by T1.cont */
#define T1_SW_CHECK_INTEGRATION_CORE_ALL              (   0u) /* Check Integration */

/* User stopwatches for core 0 */
/* The following user stopwatches are supervised by T1.cont */
#define T1_SW_CHECK_INTEGRATION_CORE0                 (T1_SW_CHECK_INTEGRATION_CORE_ALL) /* Check Integration */

/* User stopwatches for core 1 */
/* The following user stopwatches are supervised by T1.cont */
#define T1_SW_CHECK_INTEGRATION_CORE1                 (T1_SW_CHECK_INTEGRATION_CORE_ALL) /* Check Integration */

/* User stopwatches for core 2 */
/* The following user stopwatches are supervised by T1.cont */
#define T1_SW_CHECK_INTEGRATION_CORE2                 (T1_SW_CHECK_INTEGRATION_CORE_ALL) /* Check Integration */

/*----------------------------------------------------------------------------------*/
/*--- Config macros ----------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#define T1_NOF_CORES                                  (3u)
#define T1_PC_ARRAY( coreId_, var_ )                  ((var_ ## PC)[coreId_])
#define T1_PC( coreId_, var_ )                        T1_PC_ARRAY( coreId_, var_ )
#define T1_COMMS_CORE_OFFSET                          (2u)
#define T1_SID                                        (2u)
#define T1_TRACE_56BIT_SYNC_TIMER                     (0)
#define T1_FG_CONT_ACT_EXTRA_ENTRIES                  (4480)
#define T1_CAN_PC_TO_ECU_ID                           (0x7FAu)
#define T1_CAN_ECU_TO_PC_ID                           (0x7CBu)
#define T1_GCP_MAX_RX_FRAME_SIZE                      (8u)
#define T1_GCP_MAX_TX_FRAME_SIZE                      (8u)
#define T1_STATIC_RUNNABLE_ID                         (1023u)
#define T1_TIMEOUT_RX                                 (100u)
#define T1_TIMEOUT_TX                                 (100u)
#define T1_TIMEOUT_RESPONSE                           (1000u)
#define T1_INIT_FEATURE_MASK                          (0uL)
#define T1_GET_SYNC_TIME( )                           ((T1_uint32_t)T1_GET_TRACE_TIME_PC( 0u ))
#define T1_SYNC_TIMER_WIDTH_BITS                      (29u)
#define T1_SYNC_TIMER_DURATION_NS                     ((1000.0f/50)*8)
#define T1_ALL_TRACE_TIMERS_ARE_SYNC_TIMER            (1)
#define T1_ANY_TRACE_TIMER_IS_SYNC_TIMER              (1)
#define T1_CONT_NOF_FOCUS_MEASUREMENTS                (2u)
#define T1_MAX_NOF_TASKS                              ( 68u)
#define T1_MIN_CAT1_ISR_ID_OFFSET                     ( 38u)
#define T1_MIN_CAT2_ISR_ID_OFFSET                     ( 35u)
#define T1_MIN_EXT_ISR_ID_OFFSET                      ( 40u)
#define T1_GET_RAW_TIME( )                            (*(T1_tickUint_t volatile const *)T1_PTIMER_CORE0)
#define T1_ALL_TIMERS_ARE_MEMORY_MAPPED               (1)
#define T1_SYNC_TO_TRACE_TIME( syncTime__ )           ((T1_tickUint_t)(((syncTime__) << 0) >> 0))
#define T1_TRACE_TO_SYNC_TIME( traceTime__ )          ((T1_uint32_t)(((traceTime__) << 3) >> 3))
#define T1_RAW_TO_SYNC_TIME( rawTime_ )               ((T1_uint32_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_TRACE_TIME( rawTime_ )              ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_TRACE_TIME_UNMASKED( rawTime_ )     ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#if ! defined T1_GET_TRACE_TIME_PC
#   if defined T1_GET_RAW_TIME && defined T1_RAW_TO_TRACE_TIME
#       define T1_GET_TRACE_TIME_PC( coreId_ )                                  \
            T1_RAW_TO_TRACE_TIME( T1_GET_RAW_TIME( ) )
#   else /* Different timers/speeds for different cores */
#       define T1_GET_TRACE_TIME_PC( coreId_ )                                  \
(                                                                               \
    0u == (coreId_) ? T1_RAW_TO_TRACE_TIME_CORE0( T1_GET_RAW_TIME_CORE0( ) ) :  \
    1u == (coreId_) ? T1_RAW_TO_TRACE_TIME_CORE1( T1_GET_RAW_TIME_CORE1( ) ) :  \
                      T1_RAW_TO_TRACE_TIME_CORE2( T1_GET_RAW_TIME_CORE2( ) )    \
)
#       define T1_TRACE_TO_SYNC_TIME_PC( coreId_, traceTime_ )                  \
(                                                                               \
    0u == (coreId_) ? T1_TRACE_TO_SYNC_TIME_CORE0( traceTime_ ) :               \
    1u == (coreId_) ? T1_TRACE_TO_SYNC_TIME_CORE1( traceTime_ ) :               \
                      T1_TRACE_TO_SYNC_TIME_CORE2( traceTime_ )                 \
)
#   endif /* defined T1_GET_RAW_TIME && defined T1_RAW_TO_TRACE_TIME */
#endif /* ! defined T1_GET_TRACE_TIME_PC */

/* Core-specific configuration for core 0 */
#define T1_BSF_EVENT_ID_CORE0                         (T1_ACTIVATION)
#define T1_BSF_EVENT_INFO_CORE0                       (T1_Task_20ms_Core0_QM_ID)
#define T1_BACKGROUND_TASK_ID_CORE0                   (T1_Idle_Task_Core0_ID)
#define T1_TICK_DURATION_CORE0_NS                     ((1000.0f/50)*8)
#define T1_SYNC_TO_TRACE_TIME_CORE0( syncTime__ )     ((T1_tickUint_t)(((syncTime__) << 0) >> 0))
#define T1_TRACE_TO_SYNC_TIME_CORE0( traceTime__ )    ((T1_uint32_t)(((traceTime__) << 3) >> 3))
#define T1_RAW_TO_TRACE_TIME_CORE0( rawTime_ )        ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_TRACE_TIME_UNMASKED_CORE0( rawTime_ ) ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_SYNC_TIME_CORE0( rawTime_ )         ((T1_uint32_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_OVERHEAD_CORE0_NS                          (178)
#define T1_FLEX_OVERHEAD_CORE0_NS                     (500)
#define T1_CPULOAD_THRESHOLD_256THS_CORE0             (243u) /* 94.9% */
#define T1_FEATURE_MASK_CALLBACK_CORE0                (0u)
#define T1_TRACEBUFFER_ENTRIES_CORE0_                 (6000)
#define T1_TRACEBUFFER_ENTRIES_CORE0                  (6000u)
#define T1_NOF_CSRNS_CORE0                            (2u)
#define T1_NOF_USER_STPWS_CORE0                       (1u)
#define T1_NOF_FLEX_STPWS_CORE0                       (16u)
#define T1_NOF_STPWS_CORE0                            (T1_NOF_USER_STPWS_CORE0 + T1_NOF_FLEX_STPWS_CORE0)
#define T1_NOF_FLEX_ADDRS_CORE0                       (16u)
#define T1_NOF_FLEXBUFFER_ENTRIES_CORE0               (1u)
#define T1_OUTER_HANDLER_CORE0                        (T1_OuterHandlerCore0)
#define T1_PTIMER_CORE0                               (0xFC068004uL)
#define T1_SYNC_PERIOD_CORE0                          (10u)
#define T1_GET_RAW_TIME_CORE0( )                      (*(T1_tickUint_t volatile const *)T1_PTIMER_CORE0)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE0            (1)
#define T1_TRACE_TIMER_COUNTS_DOWN_CORE0              (T1_FALSE)
#define T1_TRACE_TIMER_BIT_LENGTH_CORE0               (29u)
#define T1_CPULOAD_TX_PERIOD_CORE0                    (20u)
#define T1_CPULOAD_SAMPLES_CORE0                      (20u)
#define T1_CONT_ANALYSIS_CAPACITY_CORE0               (6000u)
#define T1_NOF_DELAYS_CORE0                           (1u)

/* Core-specific configuration for core 1 */
#define T1_BSF_EVENT_ID_CORE1                         (T1_ACTIVATION)
#define T1_BSF_EVENT_INFO_CORE1                       (T1_Task_20ms_Core1_QM_ID)
#define T1_BACKGROUND_TASK_ID_CORE1                   (T1_Idle_Task_Core1_ID)
#define T1_TICK_DURATION_CORE1_NS                     ((1000.0f/50)*8)
#define T1_SYNC_TO_TRACE_TIME_CORE1( syncTime__ )     ((T1_tickUint_t)(((syncTime__) << 0) >> 0))
#define T1_TRACE_TO_SYNC_TIME_CORE1( traceTime__ )    ((T1_uint32_t)(((traceTime__) << 3) >> 3))
#define T1_RAW_TO_TRACE_TIME_CORE1( rawTime_ )        ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_TRACE_TIME_UNMASKED_CORE1( rawTime_ ) ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_SYNC_TIME_CORE1( rawTime_ )         ((T1_uint32_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_OVERHEAD_CORE1_NS                          (178)
#define T1_FLEX_OVERHEAD_CORE1_NS                     (500)
#define T1_CPULOAD_THRESHOLD_256THS_CORE1             (243u) /* 94.9% */
#define T1_FEATURE_MASK_CALLBACK_CORE1                (0u)
#define T1_TRACEBUFFER_ENTRIES_CORE1_                 (2000)
#define T1_TRACEBUFFER_ENTRIES_CORE1                  (2000u)
#define T1_NOF_CSRNS_CORE1                            (2u)
#define T1_NOF_USER_STPWS_CORE1                       (1u)
#define T1_NOF_FLEX_STPWS_CORE1                       (16u)
#define T1_NOF_STPWS_CORE1                            (T1_NOF_USER_STPWS_CORE1 + T1_NOF_FLEX_STPWS_CORE1)
#define T1_NOF_FLEX_ADDRS_CORE1                       (16u)
#define T1_NOF_FLEXBUFFER_ENTRIES_CORE1               (1u)
#define T1_OUTER_HANDLER_CORE1                        (T1_OuterHandlerCore1)
#define T1_PTIMER_CORE1                               (0xFC068004uL)
#define T1_SYNC_PERIOD_CORE1                          (10u)
#define T1_GET_RAW_TIME_CORE1( )                      (*(T1_tickUint_t volatile const *)T1_PTIMER_CORE1)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE1            (1)
#define T1_TRACE_TIMER_COUNTS_DOWN_CORE1              (T1_FALSE)
#define T1_TRACE_TIMER_BIT_LENGTH_CORE1               (29u)
#define T1_CPULOAD_TX_PERIOD_CORE1                    (20u)
#define T1_CPULOAD_SAMPLES_CORE1                      (20u)
#define T1_CONT_ANALYSIS_CAPACITY_CORE1               (2000u)
#define T1_NOF_DELAYS_CORE1                           (1u)

/* Core-specific configuration for core 2 */
#define T1_BSF_EVENT_ID_CORE2                         (T1_ACTIVATION)
#define T1_BSF_EVENT_INFO_CORE2                       (T1_Task_20ms_Core2_QM_ID)
#define T1_BACKGROUND_TASK_ID_CORE2                   (T1_Idle_Task_Core2_ID)
#define T1_TICK_DURATION_CORE2_NS                     ((1000.0f/50)*8)
#define T1_SYNC_TO_TRACE_TIME_CORE2( syncTime__ )     ((T1_tickUint_t)(((syncTime__) << 0) >> 0))
#define T1_TRACE_TO_SYNC_TIME_CORE2( traceTime__ )    ((T1_uint32_t)(((traceTime__) << 3) >> 3))
#define T1_RAW_TO_TRACE_TIME_CORE2( rawTime_ )        ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_TRACE_TIME_UNMASKED_CORE2( rawTime_ ) ((T1_tickUint_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_RAW_TO_SYNC_TIME_CORE2( rawTime_ )         ((T1_uint32_t)(((rawTime_) << 0) >> (3 + 0)))
#define T1_OVERHEAD_CORE2_NS                          (178)
#define T1_FLEX_OVERHEAD_CORE2_NS                     (500)
#define T1_CPULOAD_THRESHOLD_256THS_CORE2             (243u) /* 94.9% */
#define T1_FEATURE_MASK_CALLBACK_CORE2                (0u)
#define T1_TRACEBUFFER_ENTRIES_CORE2_                 (4000)
#define T1_TRACEBUFFER_ENTRIES_CORE2                  (4000u)
#define T1_NOF_CSRNS_CORE2                            (2u)
#define T1_NOF_USER_STPWS_CORE2                       (1u)
#define T1_NOF_FLEX_STPWS_CORE2                       (16u)
#define T1_NOF_STPWS_CORE2                            (T1_NOF_USER_STPWS_CORE2 + T1_NOF_FLEX_STPWS_CORE2)
#define T1_NOF_FLEX_ADDRS_CORE2                       (16u)
#define T1_NOF_FLEXBUFFER_ENTRIES_CORE2               (1u)
#define T1_OUTER_HANDLER_CORE2                        (T1_OuterHandlerCore2)
#define T1_PTIMER_CORE2                               (0xFC068004uL)
#define T1_SYNC_PERIOD_CORE2                          (10u)
#define T1_GET_RAW_TIME_CORE2( )                      (*(T1_tickUint_t volatile const *)T1_PTIMER_CORE2)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE2            (1)
#define T1_TRACE_TIMER_COUNTS_DOWN_CORE2              (T1_FALSE)
#define T1_TRACE_TIMER_BIT_LENGTH_CORE2               (29u)
#define T1_CPULOAD_TX_PERIOD_CORE2                    (20u)
#define T1_CPULOAD_SAMPLES_CORE2                      (20u)
#define T1_CONT_ANALYSIS_CAPACITY_CORE2               (4000u)
#define T1_NOF_DELAYS_CORE2                           (1u)

/* Unused cores. */
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE3            (1)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE4            (1)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE5            (1)


#if ! defined T1_CORE_ID_TO_SCOPE_CONSTS
#   if ! defined T1_CLONE
/* This default version can be evaluated at compile time when passed a literal input */
#       if 2 < T1_NOF_CORES && defined __GNUC__ /* use switch statement */
#           define T1_CORE_ID_TO_SCOPE_CONSTS( coreId_ ) ({                 \
    T1_scopeConsts_t * pScopeConsts_;                                       \
    switch( coreId_ )                                                       \
    {                                                                       \
    case 0:     pScopeConsts_  = T1_P_SCOPE_CONSTS0;    break;              \
    case 1:     pScopeConsts_  = T1_P_SCOPE_CONSTS1;    break;              \
    default:    pScopeConsts_  = T1_P_SCOPE_CONSTS2;    break;              \
    }                                                                       \
    pScopeConsts_;                                                          \
})
#           define T1_CORE_ID_TO_SCOPE_FG_CONSTS( coreId_ ) ({              \
    T1_scopeFgConsts_t * pScopeFgConsts_;                                   \
    switch( coreId_ )                                                       \
    {                                                                       \
    case 0:     pScopeFgConsts_  = T1_P_SCOPE_FG_CONSTS0;    break;         \
    case 1:     pScopeFgConsts_  = T1_P_SCOPE_FG_CONSTS1;    break;         \
    default:    pScopeFgConsts_  = T1_P_SCOPE_FG_CONSTS2;    break;         \
    }                                                                       \
    pScopeFgConsts_;                                                        \
})
#       else /* NOTE 'coreId_' can be evaluated more than once with >2 cores */
#           define T1_CORE_ID_TO_SCOPE_CONSTS( coreId_ ) (                  \
    ( 0 == (coreId_) ) ? T1_P_SCOPE_CONSTS0   :                             \
    ( 1 == (coreId_) ) ? T1_P_SCOPE_CONSTS1   :                             \
                         T1_P_SCOPE_CONSTS2                                 \
)
#           define T1_CORE_ID_TO_SCOPE_FG_CONSTS( coreId_ ) (               \
    ( 0 == (coreId_) ) ? T1_P_SCOPE_FG_CONSTS0  :                           \
    ( 1 == (coreId_) ) ? T1_P_SCOPE_FG_CONSTS1  :                           \
                         T1_P_SCOPE_FG_CONSTS2                              \
)
#       endif /* switch or ?: */
#   endif /* ! defined T1_CLONE */
#endif /* ! defined T1_CORE_ID_TO_SCOPE_CONSTS */

#if ! defined T1_CONT_RC_UNMAP
#   define T1_CONT_RC_UNMAP( coreId_ )                (coreId_)
#endif /* ! defined T1_CONT_RC_UNMAP */

#define T1_TRACE_TASK( taskId_ ) \
(  1 \
 && ((taskId_) != T1_Idle_Task_Core0_ID) \
 && ((taskId_) != T1_Idle_Task_Core1_ID) \
 && ((taskId_) != T1_Idle_Task_Core2_ID) \
)


/*----------------------------------------------------------------------------------*/
/*--- Function wrapper -------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#if defined T1_ENABLE

#endif /* defined T1_ENABLE */

/*----------------------------------------------------------------------------------*/

#endif /* T1_CONFIG_H_ */
