/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2022 by Vector Informatik GmbH.                                                  All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/**        \file  Etm.h
 *        \brief  Etm header file
 *
 *      \details  Implementation of the Etm (Ethernet Testability Module) module. This module implements the
 *                AUTOSAR Testability Protocol and Service Primitives protocol for interaction with external testers.
 *
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  BETA MODULE
 *  -------------------------------------------------------------------------------------------------------------------
 *  Beta Modules and Beta Features are basically operable, but not sufficiently tested, verified and/or qualified for
 *  use in series production and/or in vehicles operating on public or non-public roads. Please consult the Product
 *  Information for details.
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Version   Date        Author  Change Id     Description
 *  -------------------------------------------------------------------------------------------------------------------
 *   1.00.00  2014-11-19  visjsb  -             Initial creation
 *   1.01.00  2014-12-12  visjsb  ESCAN00080171 MSN renamed from "Eti"/"EtiTcpIpX" to "EtiTcpIpIx"
 *            2015-02-09  visjsb  ESCAN00081103 Add Basic Features and IxANVL compatibility
 *   1.02.00  2015-03-24  visjsb  ESCAN00081641 Update to R12
 *   1.02.01  2015-09-14  visjsb  ESCAN00082279 Added script integration for IxANVL (partly)
 *   1.03.00  2015-09-14  visjsb  ESCAN00085197 Update to R13
 *   2.00.00  2015-09-24  visjsb  ESCAN00085422 Implement ETM protocol support
 *   2.00.01  2015-09-24  visjsb  ESCAN00085422 Implement ETM protocol support
 *   3.00.00  2015-11-26  visjsb  ESCAN00086773 FEAT-1711: Update to R14
 *   4.00.00  2015-12-21  visjsb  ESCAN00087257 FEAT-1776: Module renaming: TestApp_EtiTcpIp_Ixia --> SysService_AsrEtm
 *   4.00.01  2016-01-15  visjsb  ESCAN00087493 Optimized internal user script interface
 *   4.00.02  2016-02-25  visjsb  ESCAN00088546 Etm call TcpIp_TcpListen() with unchecked parameters who force DETs
 *   4.01.00  2016-04-14  visjsb  ESCAN00089466 Improved UserScript configuration
 *   4.02.00  2016-08-17  visjsb  ESCAN00091507 Extend user dependent configuration
 *   4.02.01  2017-01-13  visjsb  ESCAN00093349 Stackoverflow during TCP handshake
 *            2017-01-13  visjsb  ESCAN00093515 Etm send random data using SendData command
 *            2017-01-13  visjsb  ESCAN00093518 Sending data with 400 bytes in the SendData command are restricted by an OS stackprotaction
 *            2017-01-13  visjsb  ESCAN00093520 ECU does not response to tester after reboot
 *   5.00.00  2017-04-19  visjsb  STORYC-581    Enhancements for ETM ("Clear NDP Cache" command and persistant lock functionality)
 *   5.01.00  2017-05-15  visjsb  STORYC-1143   Change internal function and config data init handling
 *            2017-06-09  visjsb  ESCAN00095485 After an ECU reset ETM is not responding anymore
 *   5.01.01  2017-07-10  visjsb  ESCAN00095612 Compiler warning: a value of type "const uint8 *" cannot be used to initialize an entity of type "uint8 *"
 *            2017-08-14  visjsb  ESCAN00096294 Missing Etm_TcpConnected callback leads to DET error TCPIP_E_CBK_REQUIRED.
 *            2017-08-14  visjsb  ESCAN00095913 ListenAndAccept Event is not generated by ETM after TCP connection is established.
 *            2017-08-14  visjsb  ESCAN00096297 ETM_EVENT_LENGTH_FORWARD_DATA is 2 Byte too short.
 *   6.00.00  2018-02-16  visjsb  STORYC-4354   Update to R20
 *   6.00.01  2018-03-14  visjsb  STORYC-4672   Rework MISRA deviations/justifications
 *   6.00.02  2018-04-24  visjsb  ESCAN00099192 Compiler error: Could not find symbols IPV6_HTON and IPV6_UINT8_HTONS
 *   6.00.03  2018-06-27  visjsb  ESCAN00099804 Compiler error: C4013: 'TcpIp_VSockIpAddrIsEqual' undefined; assuming extern returning int
 *   7.00.00  2019-01-04  visjsb  STORYC-5601   Support ETM protocol according to AUTOSAR ATS 1.2.0
 *   7.00.01  2019-01-15  visjsb  STORYC-4512   MISRA-C:2012 Compliance
 *   7.00.02  2019-01-15  visjsb  STORYC-4512   MISRA-C:2012 Compliance
 *   7.00.03  2019-06-27  visjsb  ESCAN00103523 Compiler error: Undeclared Identifier Etm_CommandPending
 *   8.00.00  2019-07-08  visjsb  STORY-10023   Support ETM protocol according to AUTOSAR ATS 1.2.0 - incl. TC8 support - ETH/PHY primitives
 *   8.00.01  2019-09-02  visjsb  ESCAN00104143 Etm Service Primitive TCP.SEND_DATA return E_NOT_OK and send no data.
 *   8.00.02  2019-12-11  visjsb  SAA-387       Code refactoring
 *   8.00.03  2020-07-10  visjsb  ESCAN00106820 Service Primitive ECHO_REQUEST stay pending even if echo was send.
 *   8.00.04  2020-10-01  viseje  SAA-863       Update to QAC Helix
 *   8.00.05  2020-10-01  visjsb  SAA-863       Update to QAC Helix
 *   9.00.00  2020-10-08  visjsb  ESCAN00107575 Service Primitive indicates E_OK but request was dropped
 *   9.00.01  2020-10-29  visjsb  SAA-1263      Update version history to current template
 *            2020-10-29  visjsb  ESCAN00107668 Etm ignores Service Primitives with GID value 0x7F.
 *   9.00.02  2020-12-01  visjsb  SAA-1289      Move self-defined reboot service primitive from filtered source code section to application template file.
 *            2020-12-03  visjsb  SAA-829       Extend the Etm for Etm_DhcpEvent() callback to support TC8 tests.
 *   9.00.03  2020-12-18  visjsb  SAA-1510      Add blacklist for unsupported DHCP options
 *   9.00.04  2020-12-18  visjsb  TAR-513       Etm MISRA Rule 9.1 / QAC MsgId 2962, 2972
 *  10.00.00  2022-02-15  visjsb  SAA-1369      Support IP address state ONHOLD
 *            2022-02-15  visjsb  SAA-2300      Usage of <Mip>_MemMap in Etm
 *********************************************************************************************************************/

#if !defined (ETM_H)
# define ETM_H

/**********************************************************************************************************************
 * INCLUDES
 *********************************************************************************************************************/

#include "Etm_Cbk.h"

# if (ETM_DEV_ERROR_DETECT == STD_ON)
#  include "Det.h"
# endif /* (ETM_DEV_ERROR_DETECT == STD_ON) */

/**********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 *********************************************************************************************************************/

/* Vendor and module identification */
# define ETM_VENDOR_ID                        30u
# define ETM_MODULE_ID                        170u

/* AUTOSAR Software specification version information */
# define ETM_AR_RELEASE_MAJOR_VERSION         4u
# define ETM_AR_RELEASE_MINOR_VERSION         2u
# define ETM_AR_RELEASE_REVISION_VERSION      1u

/* ----- Component version information (decimal version of ALM implementation package) ----- */
# define ETM_SW_MAJOR_VERSION                10u
# define ETM_SW_MINOR_VERSION                 0u
# define ETM_SW_PATCH_VERSION                 0u

/* ----- DET Instance ID ----- */
# define ETM_INSTANCE_ID_DET                  0x05u

/* ----- ETM Protocol Version (SOME/IP) ----- */
# define ETM_SOMEIP_PROTOCOL_VERSION          1u
# define ETM_SOMEIP_INTERFACE_VERSION         1u

/* ----- API service IDs ----- */
# define ETM_SID_INIT                         0x00u /* Service ID: Etm_Init() */
# define ETM_SID_GET_VERSION_INFO             0x01u /* Service ID: Etm_GetVersionInfo() */
# define ETM_SID_MAIN_FUNCTION                0x02u /* Service ID: Etm_MainFunction() */
# define ETM_SID_RX_INDICATION                0x03u /* Service ID: Etm_RxIndication() */
# define ETM_SID_TX_CONFIRMATION              0x04u /* Service ID: not yet used */
# define ETM_SID_CBK_TCP_ACCEPTED             0x05u /* Service ID: not yet used */
# define ETM_SID_CBK_TCP_CONNECTED            0x06u /* Service ID: not yet used */
# define ETM_SID_CBK_TCPIP_EVENT              0x07u /* Service ID: not yet used */
# define ETM_SID_ACTIVATE_PROCESSING          0x08u /* Serive ID: Etm_ActivateProcessing() */
# define ETM_SID_DEACTIVATE_PROCESSING        0x09u /* Serive ID: Etm_DeactivateProcessing() */
# define ETM_SID_INTERNAL_FUNCTION            0xFFu /* Service ID: internal functions */

/* ----- Error code IDs ----- */
# define ETM_E_NOT_INITIALIZED                0x01u /*! \brief Error code: API service used without module initialization */
# define ETM_E_ALREADY_INITIALIZED            0x02u /*! \brief Error code: The service Etm_Init() is called while the module is already initialized */
# define ETM_E_INV_CONFIG                     0x03u /*! \brief Error code: API service Etm_Init() called with wrong configuration */
# define ETM_E_NULL_POINTER                   0x04u /*! \brief Error code: API service called with NULL_PTR */
# define ETM_E_INV_POINTER                    0x05u /*! \brief Error code: API service called with invalid pointer */
# define ETM_E_INV_PARAM                      0x06u /*! \brief Error code: API service called with invalid parameter */
# define ETM_E_INV_SOCK_HND                   0x07u /*! \brief Error code: API service called with invalid socket handle */
# define ETM_E_INV_SOCK_ADDR_FAMILY           0x08u /*! \brief Error code: API service called with invalid address family */

/* ----- ETM Processing States ----- */
# if (ETM_NVM_ENABELD == STD_ON)
#  define ETM_PROCESSING_INVALID              0x00u
#  define ETM_PROCESSING_ACTIVE               0x01u /* Service Primitive and command processing enabled */
#  define ETM_PROCESSING_INACTIVE             0x02u /* Service Primitive and command processing disabled */
# endif /* (ETM_NVM_ENABELD == STD_ON) */

# define ETM_INV_SOCKET_ID                    0xFFu

/* ----- Mapping of error reporting macro ----- */
# if (ETM_DEV_ERROR_DETECT == STD_ON)
#  define Etm_CheckDetErrorReturnVoid(CONDITION, API_ID, ERROR_CODE)             { if (!(CONDITION)){ (void)Det_ReportError((uint16)ETM_MODULE_ID, (uint8)ETM_INSTANCE_ID_DET, (uint8)(API_ID), (uint8)(ERROR_CODE)); return; } }            /* PRQA S 3458 */ /* MD_MSR_FctLikeMacro */
#  define Etm_CheckDetErrorReturnValue(CONDITION, API_ID, ERROR_CODE, RET_VAL)   { if (!(CONDITION)){ (void)Det_ReportError((uint16)ETM_MODULE_ID, (uint8)ETM_INSTANCE_ID_DET, (uint8)(API_ID), (uint8)(ERROR_CODE)); return (RET_VAL); } }  /* PRQA S 3458 */ /* MD_MSR_FctLikeMacro */
#  define Etm_ReportDetError(API_ID, ERROR_CODE)                                 {                    (void)Det_ReportError((uint16)ETM_MODULE_ID, (uint8)ETM_INSTANCE_ID_DET, (uint8)(API_ID), (uint8)(ERROR_CODE)); }                      /* PRQA S 3458 */ /* MD_MSR_FctLikeMacro */
# else
#  define Etm_CheckDetErrorReturnVoid(CONDITION, API_ID, ERROR_CODE)
#  define Etm_CheckDetErrorReturnValue(CONDITION, API_ID, ERROR_CODE, RET_VAL)
#  define Etm_ReportDetError(API_ID, ERROR_CODE)
# endif

/**********************************************************************************************************************
 *  GLOBAL FUNCTION MACROS
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 *********************************************************************************************************************/

# define ETM_START_SEC_CONST_8
# include "Etm_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

# if (ETM_NVM_ENABELD == STD_ON)
extern CONST(uint8, ETM_CONST) Etm_NvmBlock_Rom; /* used as default value for Etm processing state */
# endif /* (ETM_NVM_ENABELD == STD_ON) */

# define ETM_STOP_SEC_CONST_8
# include "Etm_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

/*****************************************************/

# define ETM_START_SEC_VAR_NO_INIT_8
# include "Etm_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

# if (ETM_NVM_ENABELD == STD_ON)
extern VAR(uint8, ETM_VAR_NO_INIT) Etm_NvmBlock_Ram; /* used to save the Etm processing state */
# endif /* (ETM_NVM_ENABELD == STD_ON) */

# define ETM_STOP_SEC_VAR_NO_INIT_8
# include "Etm_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

/**********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 *********************************************************************************************************************/

# define ETM_START_SEC_CODE
# include "Etm_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

/**********************************************************************************************************************
 *  Etm_InitMemory()
 *********************************************************************************************************************/
/*! \brief        Function for *_INIT_*-variable initialization
 *  \details      Service to initialize module global variables at power up. This function initializes the
 *                variables in *_INIT_* sections. Used in case they are not initialized by the startup code.
 *  \param        void none
 *  \return       none
 *  \pre          Module is uninitialized.
 *  \context      TASK
 *  \reentrant    Non Reentrant.
 *  \synchronous  Synchronous.
 *********************************************************************************************************************/
FUNC(void, ETM_CODE) Etm_InitMemory(void);

/**********************************************************************************************************************
 *  Etm_Init()
 *********************************************************************************************************************/
/*! \brief        Initialization function
 *  \details      This function initializes the module Etm. It initializes all variables and sets the module state to
 *                initialized.
 *  \param[in]    ConfigPtr Configuration structure for initializing the module.
 *  \return       none
 *  \pre          Interrupts are disabled.
 *  \pre          Module is uninitialized.
 *  \pre          Etm_InitMemory has been called unless Etm_ModuleInitialized is initialized by start-up code.
 *  \context      TASK
 *  \reentrant    Non Reentrant.
 *  \synchronous  Synchronous.
 *  \note         Specification of module initialization
 *********************************************************************************************************************/
FUNC(void, ETM_CODE) Etm_Init(ETM_P2C(Etm_ConfigType) ConfigPtr);

# if (ETM_VERSION_INFO_API == STD_ON)
/**********************************************************************************************************************
 *  Etm_GetVersionInfo()
 *********************************************************************************************************************/
/*! \brief        Returns the version information
 *  \details      Etm_GetVersionInfo() returns version information, vendor ID and AUTOSAR module ID of the component.
 *  \param[out]   VersionInfoPtr Pointer to where to store the version information. Parameter must not be NULL.
 *  \return       none
 *  \pre          none
 *  \context      TASK
 *  \reentrant    Reentrant.
 *  \synchronous  Synchronous.
 *********************************************************************************************************************/
FUNC(void, ETM_CODE) Etm_GetVersionInfo(ETM_P2V(Std_VersionInfoType) VersionInfoPtr);
# endif /* (ETM_VERSION_INFO_API == STD_ON) */

# if (ETM_NVM_ENABELD == STD_ON)
/**********************************************************************************************************************
 *  Etm_ActivateProcessing()
 *********************************************************************************************************************/
/*! \brief        Activates the Service Primitive and command processing
 *  \details      Etm_ActivateProcessing() starts the message procesing.
 *                This service can, for example, be triggered by a diagnostic message.
 *  \param        void none
 *  \return       none
 *  \pre          none
 *  \context      TASK
 *  \reentrant    Non Reentrant.
 *  \synchronous  Synchronous.
 *********************************************************************************************************************/
FUNC(void, ETM_CODE) Etm_ActivateProcessing(void);
# endif /* (ETM_NVM_ENABELD == STD_ON) */

# if (ETM_NVM_ENABELD == STD_ON)
/**********************************************************************************************************************
 *  Etm_DeactivateProcessing()
 *********************************************************************************************************************/
/*! \brief        Deactivates the Service Primitive and command processing
 *  \details      Etm_DeactivateProcessing() stops the message procesing.
 *                This service can, for example, be triggered by a diagnostic message.
 *  \param        void none
 *  \return       none
 *  \pre          none
 *  \context      TASK
 *  \reentrant    Non Reentrant.
 *  \synchronous  Synchronous.
 *********************************************************************************************************************/
FUNC(void, ETM_CODE) Etm_DeactivateProcessing(void);
# endif /* (ETM_NVM_ENABELD == STD_ON) */

# define ETM_STOP_SEC_CODE
# include "Etm_MemMap.h" /* PRQA S 5087 */  /* MD_MSR_MemMap */

#endif /* ETM_H */

/**********************************************************************************************************************
 *  END OF FILE: Etm.h
 *********************************************************************************************************************/
