/*
********************************************************************************
*
* File name: Com_Lcfg.h
*
* Copyright 2018-2024 Neusoft Reach Corporation. All rights reserved.
*
********************************************************************************
*
* History
*-------------------------------------------------------------------------------
********************************************************************************
* Version: 1.0
* Author/Date: WangJP/2021.08.14
* Change: New created
* Cause: New
********************************************************************************
*/
#ifndef COM_LCFG_H_
#define COM_LCFG_H_

/*
********************************************************************************
*    Includes
********************************************************************************
*/
#include "Com_Cfg.h"
#include "Com_Types.h"
#include "ComRx_Indication.h"



/*
********************************************************************************
*    Global Macros
********************************************************************************
*/
#define COM_RXPDU_NUM                  (21U)
#define COM_TXPDU_NUM                  (23U)
#define COM_RXSIG_NUM                  (141U)
#define COM_TXSIG_NUM                  (182U)
#define COM_RXGRP_NUM                  (0U)
#define COM_TXGRP_NUM                  (0U)
#define COM_PDUGRP_SIZE                6U
#define COM_PDUGRP_MATCH_SIZE          (44U)
#define COM_TX_TIMEBASE                (5U)
#define COM_RX_TIMEBASE                (5U)

#define Com_Config_Ptr                 NULL_PTR
#define COM_PDUGRP_VECTOR_SIZE         (((COM_PDUGRP_SIZE-1U)/8U)+1U)
#define COM_TXMETA_BYTEMAXNUM          (1U)
   

#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTOPERATINGMODEMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	0U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTROTDIRTIONMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	1U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTSYSSTSMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	2U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_HIGHPRECISIONMOTTQMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	3U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTCURMAXOUTPHIGHPRECISIONTQMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	4U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTTQMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	5U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_CURMAXOUTPTQOFMOTMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	6U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTSPDMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	7U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_HIGHUPWROFFALLWEDMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	8U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_ACTVDISCHRGSTMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	9U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MOTFAILRSTSMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	10U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MSGCNTERMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	11U
#define  COMCONF_COMSIGNAL_MCU1_D3_SO0_MSGCHKSUMMCU1_MCU1_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	12U
#define  COMCONF_COMSIGNAL_ECMCU_D3_SO0_MOTTQECMCU_ECMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	13U
#define  COMCONF_COMSIGNAL_MCU3_D3_SO0_MOTAVLMAXGENNHIGHPRECISIONTQMCU3_MCU3_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	14U
#define  COMCONF_COMSIGNAL_MCU3_D3_SO0_MOTAVLMAXGENNTQMCU3_MCU3_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	15U
#define  COMCONF_COMSIGNAL_MCU3_D3_SO0_MSGCNTERMCU3_MCU3_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	16U
#define  COMCONF_COMSIGNAL_MCU3_D3_SO0_MSGCHKSUMMCU3_MCU3_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	17U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MOTOPERATINGMODEMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	18U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MOTROTDIRTIONMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	19U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MOTSYSSTSMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	20U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_HIGHPRECISIONMOTTQMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	21U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_OTCURMAXOUTPHIGHPRECISIONTQMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	22U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MOTTQMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	23U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_CURMAXOUTPTQOFMOTMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	24U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MOTSPDMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	25U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_HIGHUPWROFFALLWEDMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	26U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_ACTVDISCHRGSTMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	27U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MOTFAILRSTSMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	28U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MSGCNTERMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	29U
#define  COMCONF_COMSIGNAL_MCU21_D3_SO0_MSGCHKSUMMCU21_MCU21_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	30U
#define  COMCONF_COMSIGNAL_MCU22_D3_SO0_MOTCTRLLERBUSUMCU22_MCU22_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	31U
#define  COMCONF_COMSIGNAL_MCU22_D3_SO0_MOTCTRLLERBUSCURMCU22_MCU22_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	32U
#define  COMCONF_COMSIGNAL_MCU22_D3_SO0_MOTTMCU22_MCU22_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	33U
#define  COMCONF_COMSIGNAL_MCU22_D3_SO0_MOTCTRLLERTMCU22_MCU22_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	34U
#define  COMCONF_COMSIGNAL_MCU23_D3_SO0_OTAVLMAXGENNHIGHPRECISIONTQMCU23_MCU23_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	35U
#define  COMCONF_COMSIGNAL_MCU23_D3_SO0_MOTAVLMAXGENNTQMCU23_MCU23_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	36U
#define  COMCONF_COMSIGNAL_MCU23_D3_SO0_MSGCNTERMCU23_MCU23_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	37U
#define  COMCONF_COMSIGNAL_MCU23_D3_SO0_MSGCHKSUMMCU23_MCU23_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	38U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_PROTLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	39U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_AMBERWARNLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	40U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_REDSTOPLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	41U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_MALFCTINDCRLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	42U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_FLASHPROTLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	43U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_FLASHAMBERWARNLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	44U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_FLASHREDSTOPLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	45U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_FLASHMALFCTINDCRLAMPDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	46U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_SPN8LEASTSIGNIFICANTBITSDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	47U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_SPNSECBYTEDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	48U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_FMIDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	49U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_SPN3MOSTSIGNIFICANTBITSDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	50U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_OCCURRENCECNTDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	51U
#define  COMCONF_COMSIGNAL_DM1MCU_D3_SO0_SPNCNVNMETHODDM1MCU_DM1MCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	52U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_PROTLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	53U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_AMBERWARNLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	54U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_REDSTOPLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	55U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_MALFCTINDCRLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	56U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_FLASHPROTLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	57U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_FLASHAMBERWARNLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	58U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_FLASHREDSTOPLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	59U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_FLASHMALFCTINDCRLAMPDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	60U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_SPN8LEASTSIGNIFICANTBITSDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	61U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_SPNSECBYTEDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	62U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_FMIDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	63U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_SPN3MOSTSIGNIFICANTBITSDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	64U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_OCCURRENCECNTDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	65U
#define  COMCONF_COMSIGNAL_DM1MCU2_D3_SO0_SPNCNVNMETHODDM1MCU2_DM1MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	66U
#define  COMCONF_COMSIGNAL_MCU2_D3_SO0_MOTCTRLLERBUSUMCU2_MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	67U
#define  COMCONF_COMSIGNAL_MCU2_D3_SO0_MOTCTRLLERBUSCURMCU2_MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	68U
#define  COMCONF_COMSIGNAL_MCU2_D3_SO0_MOTTMCU2_MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	69U
#define  COMCONF_COMSIGNAL_MCU2_D3_SO0_MOTCTRLLERTMCU2_MCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_TX	70U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_VOUSET_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	71U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_COUSET_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	72U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_MODE_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	73U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_ENABLE_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	74U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_SLEEP_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	75U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_PRECHARGE_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	76U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_FAULT_CLEAR_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	77U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_DIR_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	78U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_DIR_CHECK_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	79U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_COUNTER_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	80U
#define  COMCONF_COMSIGNAL_DCDC_CMD1_VR82BV_DCDC_CHECKSUM_DCDC_CMD1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_TX	81U
#define  COMCONF_COMSIGNAL_APCU1_OJCG_C_APCUHIGHUBUSUAPCU1_APCU1_FAW3_HVAC_V2_0DBC_DBC_TX	82U
#define  COMCONF_COMSIGNAL_APCU1_OJCG_C_APCUMOTWORKINGSTSAPCU1_APCU1_FAW3_HVAC_V2_0DBC_DBC_TX	83U
#define  COMCONF_COMSIGNAL_APCU1_OJCG_C_APCUMOTFAILRSTSAPCU1_APCU1_FAW3_HVAC_V2_0DBC_DBC_TX	84U
#define  COMCONF_COMSIGNAL_APCU1_OJCG_C_APCUOUTPCURAPCU1_APCU1_FAW3_HVAC_V2_0DBC_DBC_TX	85U
#define  COMCONF_COMSIGNAL_APCU2_OJCG_C_APCUTAPCU2_APCU2_FAW3_HVAC_V2_0DBC_DBC_TX	86U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_PROTLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	87U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_AMBERWARNLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	88U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_REDSTOPLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	89U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_MALFCTINDCRLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	90U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_FLASHPROTLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	91U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_FLASHAMBERWARNLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	92U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_FLASHREDSTOPLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	93U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_FLASHMALFCTINDCRLAMPDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	94U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_SPN8LEASTSIGNIFICANTBITSDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	95U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_SPNSECBYTEDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	96U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_FMIDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	97U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_SPN3MOSTSIGNIFICANTBITSDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	98U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_OCCURRENCECNTDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	99U
#define  COMCONF_COMSIGNAL_DM1APCU_OJCG_C_SPNCNVNMETHODDM1APCU_DM1APCU_FAW3_HVAC_V2_0DBC_DBC_TX	100U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCINPUDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	101U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCINPCURDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	102U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCOUTPUDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	103U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCOUTPCURDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	104U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCTDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	105U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCWORKINGSTSDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	106U
#define  COMCONF_COMSIGNAL_DCDC1_OJCG_C_DCDCFLTSTSDCDC1_DCDC1_FAW3_HVAC_V2_0DBC_DBC_TX	107U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_PROTLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	108U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_AMBERWARNLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	109U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_REDSTOPLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	110U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_MALFCTINDCRLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	111U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_FLASHPROTLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	112U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_FLASHAMBERWARNLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	113U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_FLASHREDSTOPLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	114U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_FLASHMALFCTINDCRLAMPDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	115U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_SPN8LEASTSIGNIFICANTBITSDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	116U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_SPNSECBYTEDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	117U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_FMIDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	118U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_SPN3MOSTSIGNIFICANTBITSDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	119U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_OCCURRENCECNTDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	120U
#define  COMCONF_COMSIGNAL_DM1DCDC_OJCG_C_SPNCNVNMETHODDM1DCDC_DM1DCDC_FAW3_HVAC_V2_0DBC_DBC_TX	121U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_PROTLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	122U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_AMBERWARNLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	123U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_REDSTOPLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	124U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_MALFCTINDCRLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	125U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_FLASHPROTLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	126U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_FLASHAMBERWARNLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	127U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_FLASHREDSTOPLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	128U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_FLASHMALFCTINDCRLAMPDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	129U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_SPN8LEASTSIGNIFICANTBITSDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	130U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_SPNSECBYTEDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	131U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_FMIDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	132U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_SPN3MOSTSIGNIFICANTBITSDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	133U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_OCCURRENCECNTDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	134U
#define  COMCONF_COMSIGNAL_DM1OPCU_OJCG_C_SPNCNVNMETHODDM1OPCU_DM1OPCU_FAW3_HVAC_V2_0DBC_DBC_TX	135U
#define  COMCONF_COMSIGNAL_OPCU1_OJCG_C_OPCUHIGHUBUSUOPCU1_OPCU1_FAW3_HVAC_V2_0DBC_DBC_TX	136U
#define  COMCONF_COMSIGNAL_OPCU1_OJCG_C_OPCUMOTFAILRSTSOPCU1_OPCU1_FAW3_HVAC_V2_0DBC_DBC_TX	137U
#define  COMCONF_COMSIGNAL_OPCU1_OJCG_C_OPCUWORKINGSTSOPCU1_OPCU1_FAW3_HVAC_V2_0DBC_DBC_TX	138U
#define  COMCONF_COMSIGNAL_OPCU2_OJCG_C_OILPUMPMOTIVTERTOPCU2_OPCU2_FAW3_HVAC_V2_0DBC_DBC_TX	139U
#define  COMCONF_COMSIGNAL_OPCU2_OJCG_C_OILPUMPMOTOUTPCUROPCU2_OPCU2_FAW3_HVAC_V2_0DBC_DBC_TX	140U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_MAINPOSRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	141U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_MAINNEGTIVERLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	142U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_PDUFAILRSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	143U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_PRECHRGNRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	144U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_FUELCELLRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	145U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_PTCRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	146U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_ACSORYRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	147U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_MECURLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	148U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_DCDCRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	149U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_MAINPOSRLYPWRONSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	150U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_MECUPWRONSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	151U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_BATTPACKHEATGPOSRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	152U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_BATTPACKHEATGNEGRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	153U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_HYDROCOOLGRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	154U
#define  COMCONF_COMSIGNAL_RELAYSTATE_OJCG_C_ACRLYSTSRELAYSTATE_RELAYSTATE_FAW3_HVAC_V2_0DBC_DBC_TX	155U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_DIRTCURCHRG1POSRLYSTSRELAYSTATE2_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	156U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_DIRTCURCHRG1NEGRLYSTSRELAYSTATE2_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	157U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_DIRTCURCHRG2NEGRLYSTSRELAYSTATE20_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	158U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_DIRTCURCHRG2NEGRLYSTSRELAYSTATE21_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	159U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_PWRBATTURELAYSTATE2_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	160U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_BATTHEATPTCRLYSTSRELAYSTATE2_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	161U
#define  COMCONF_COMSIGNAL_RELAYSTATE2_OJCG_C_WTRCOOLGRLYSTSRELAYSTATE2_RELAYSTATE2_FAW3_HVAC_V2_0DBC_DBC_TX	162U
#define  COMCONF_COMSIGNAL_IMCU1PTU_OJCG_C_INSULATIONRIMCU1PTU_IMCU1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	163U
#define  COMCONF_COMSIGNAL_IMCU1PTU_OJCG_C_SULATIONMONRDETECTSURESDIMCU1PTU_IMCU1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	164U
#define  COMCONF_COMSIGNAL_IMCU1PTU_OJCG_C_INSULATIONMONRSYSSTSIMCU1PTU_IMCU1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	165U
#define  COMCONF_COMSIGNAL_IMCU1PTU_OJCG_C_INSULATIONMONRALRMIMCU1PTU_IMCU1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	166U
#define  COMCONF_COMSIGNAL_MECU1RESERVED_OJCG_C_MECUBUSBARUMECU1RESERVED_MECU1RESERVED_FAW3_HVAC_V2_0DBC_DBC_TX	167U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_PROTLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	168U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_AMBERWARNLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	169U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_REDSTOPLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	170U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_MALFCTINDCRLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	171U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_FLASHPROTLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	172U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_FLASHAMBERWARNLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	173U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_FLASHREDSTOPLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	174U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_FLASHMALFCTINDCRLAMPDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	175U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_SPN8LEASTSIGNIFICANTBITSDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	176U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_SPNSECBYTEDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	177U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_FMIDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	178U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_SPN3MOSTSIGNIFICANTBITSDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	179U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_OCCURRENCECNTDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	180U
#define  COMCONF_COMSIGNAL_DM1PTU_OJCG_C_SPNCNVNMETHODDM1PTU_DM1PTU_FAW3_HVAC_V2_0DBC_DBC_TX	181U


#define  COM_IPDU_GROUP_CAN_MATRIX_DCDC_V0_1_20250414_DBC_VR82BV_TX_INDEX	(0U)
#define  COM_IPDU_GROUP_CAN_MATRIX_DCDC_V0_1_20250414_DBC_VR82BV_RX_INDEX	(1U)
#define  COM_IPDU_GROUP_FAW_MCD_MCU_CAN_V1_4_1_DBC_D3_SO0_TX_INDEX	(2U)
#define  COM_IPDU_GROUP_FAW_MCD_MCU_CAN_V1_4_1_DBC_D3_SO0_RX_INDEX	(3U)
#define  COM_IPDU_GROUP_FAW3_HVAC_V2_0DBC_DBC_OJCG_C_TX_INDEX	(4U)
#define  COM_IPDU_GROUP_FAW3_HVAC_V2_0DBC_DBC_OJCG_C_RX_INDEX	(5U)
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_OVRDCTRLMODETSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	0U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_REQEDSPDCTRLCDNSTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	1U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_OVRDCTRLMODEPRIOTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	2U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_REQEDSPDSPDLIMTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	3U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_REQEDTQTQLIMTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	4U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_REQEDTQFRACTNALTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	5U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_MSGCNTERTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	6U
#define  COMCONF_COMSIGNAL_TSC1MTR_D3_SO0_MSGCHKSUMTSC1MTR_TSC1MTR_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	7U
#define  COMCONF_COMSIGNAL_EEC2HCU_D3_SO0_ACCRPEDLAPPOSN_EEC2HCU_EEC2HCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	8U
#define  COMCONF_COMSIGNAL_CCVSHCU_D3_SO0_PRKGBRKSWTCCVSHCU_CCVSHCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	9U
#define  COMCONF_COMSIGNAL_CCVSHCU_D3_SO0_BRKSWTCCVSHCU_CCVSHCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	10U
#define  COMCONF_COMSIGNAL_TC1_D3_SO0_TRSMREQEDGEARTC1_TC1_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	11U
#define  COMCONF_COMSIGNAL_TC1_D3_SO0_TRSMMODE2TC1_TC1_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	12U
#define  COMCONF_COMSIGNAL_TC1HANDLE_D3_SO0_TRSMREQEDGEARTC1HANDLE_TC1HANDLE_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	13U
#define  COMCONF_COMSIGNAL_ETC1_D3_SO0_SHIFTINPROCETC1_ETC1_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	14U
#define  COMCONF_COMSIGNAL_ETC2_D3_SO0_SELEDGEARETC2_ETC2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	15U
#define  COMCONF_COMSIGNAL_ETC2_D3_SO0_ACTGEARRATETC2_ETC2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	16U
#define  COMCONF_COMSIGNAL_ETC2_D3_SO0_CURGEARETC2_ETC2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	17U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_REQHCUTOCTRLTHEMOTAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	18U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_TRSMGEARSELFLRNINGSTAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	19U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_HOLDCURGEARREQAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	20U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_CLUSTSAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	21U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_SERSPARALLELMODESTAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	22U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_CLUCNSEDTQAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	23U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_SWTSTOFTHEFPICKERAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	24U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_DRVGFSTAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	25U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_PRKGFSTAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	26U
#define  COMCONF_COMSIGNAL_AMT3_D3_SO0_PTOBINDINGSTAMT3_AMT3_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	27U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_THEREQEDMOTOPERATINGMODEHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	28U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_HIGHPRECISIONMOTTQREQEDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	29U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTTQREQEDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	30U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTSPDREQEDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	31U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTWORKENACMDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	32U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTNEGHIGHURLYCMDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	33U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTPOSHIGHURLYCMDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	34U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTPRECHRGHIGHURLYCMDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	35U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_HIGHUPWROFFREQOFMOTHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	36U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MOTACTVDISCHRGCMDHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	37U
#define  COMCONF_COMSIGNAL_HCUMCU_D3_SO0_MAXSPDLIMUNDERCURLOADHCUMCU_HCUMCU_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	38U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_THEREQEDMOTOPERATINGMODEHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	39U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_HIGHPRECISIONMOTTQREQEDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	40U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTTQREQEDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	41U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTSPDREQEDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	42U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTWORKENACMDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	43U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTNEGHIGHURLYCMDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	44U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTPOSHIGHURLYCMDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	45U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTPRECHRGHIGHURLYCMDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	46U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_HIGHUPWROFFREQOFMOTHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	47U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MOTACTVDISCHRGCMDHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	48U
#define  COMCONF_COMSIGNAL_HCUMCU2_D3_SO0_MAXSPDLIMUNDERCURLOADHCUMCU2_HCUMCU2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	49U
#define  COMCONF_COMSIGNAL_SC_D3_SO0_PTOSWTCMDSC_SC_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	50U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_OVRDCTRLMODETSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	51U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_REQEDSPDCTRLCDNSTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	52U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_OVRDCTRLMODEPRIOTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	53U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_REQEDSPDSPDLIMTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	54U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_REQEDTQTQLIMTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	55U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_REQEDTQFRACTNALTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	56U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_MSGCNTERTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	57U
#define  COMCONF_COMSIGNAL_TSC1MTR2_D3_SO0_MSGCHKSUMTSC1MTR2_TSC1MTR2_FAW_MCD_MCU_CAN_V1_4_1_DBC_RX	58U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_VIN_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	59U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_VOUT_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	60U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_COUT_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	61U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_MODEFB_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	62U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_DIRFB_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	63U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_CMDSRC_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	64U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_FAULTLEVEL_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	65U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_STATE_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	66U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_COUNTER1_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	67U
#define  COMCONF_COMSIGNAL_DCDC_STATUS1_VR82BV_DCDC_CHECKSUM1_DCDC_STATUS1_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	68U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_COUTLIMIT_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	69U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VIN_OV_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	70U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VIN_OV_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	71U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VIN_OV_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	72U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VIN_UV_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	73U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VIN_UV_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	74U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VIN_UV_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	75U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VOUT_OV_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	76U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VOUT_OV_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	77U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VOUT_OV_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	78U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VOUT_UV_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	79U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VOUT_UV_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	80U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_VOUT_UV_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	81U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_COUT_OC_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	82U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_COUT_OC_LEVEL2_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	83U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_COUT_OC_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	84U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_COUT_OC_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	85U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_OUT_SC_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	86U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_OUT_SC_LEVEL2_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	87U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_PSFB_OT_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	88U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_PSFB_OT_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	89U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_PSFB_OT_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	90U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_SR_OT_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	91U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_SR_OT_LEVEL3_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	92U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_SR_OT_LEVEL4_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	93U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_OC_PSFB_LEVEL2_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	94U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_OC_BOOSTSUB1_LEVEL2_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	95U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_OC_BOOSTSUB2_LEVEL2_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	96U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_CAN_TIMEOUT_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	97U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_CAN_E2E_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	98U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_INITIAL_FAILURE_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	99U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_PRECHARGE_FAILURE_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	100U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_PSFB_CS_FAILURE_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	101U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HARD_FAILURE_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	102U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOC_PSFB_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	103U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOC_COUT_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	104U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOC_VIN_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	105U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOV_VOUT_BOOST_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	106U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOV_VOUT_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	107U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOC_BOOSTSUB1_LEVEL1_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	108U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_HOC_BOOSTSUB2_LEVEL2_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	109U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_BOOSTSUB1_CS_FAILURE_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	110U
#define  COMCONF_COMSIGNAL_DCDC_STATUS2_VR82BV_DCDC_BOOSTSUB2_CS_FAILURE_DCDC_STATUS2_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	111U
#define  COMCONF_COMSIGNAL_DCDC_STATUS3_VR82BV_DCDC_SOFTVER_DCDC_STATUS3_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	112U
#define  COMCONF_COMSIGNAL_DCDC_STATUS3_VR82BV_DCDC_HARDVER_DCDC_STATUS3_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	113U
#define  COMCONF_COMSIGNAL_DCDC_STATUS3_VR82BV_DCDC_TEMP_DCLINK_DCDC_STATUS3_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	114U
#define  COMCONF_COMSIGNAL_DCDC_STATUS3_VR82BV_DCDC_TEMP_SR_DCDC_STATUS3_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	115U
#define  COMCONF_COMSIGNAL_DCDC_STATUS3_VR82BV_DCDC_TEMP_TSFM_DCDC_STATUS3_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	116U
#define  COMCONF_COMSIGNAL_DCDC_STATUS3_VR82BV_DCDC_TEMP_PSFB_DCDC_STATUS3_CAN_MATRIX_DCDC_V0_1_20250414_DBC_RX	117U
#define  COMCONF_COMSIGNAL_HCUDCDC_OJCG_C_DCDCOUTPUREQHCUDCDC_HCUDCDC_FAW3_HVAC_V2_0DBC_DBC_RX	118U
#define  COMCONF_COMSIGNAL_HCUDCDC_OJCG_C_DCDCWORKINGEANABLECMDHCUDCDC_HCUDCDC_FAW3_HVAC_V2_0DBC_DBC_RX	119U
#define  COMCONF_COMSIGNAL_HCUAPCU_OJCG_C_AIRPUMPMOTWORKINGENAHCUAPCU_HCUAPCU_FAW3_HVAC_V2_0DBC_DBC_RX	120U
#define  COMCONF_COMSIGNAL_HCUOPCU_OJCG_C_OILPUMPMOTWORKINGENACMDHCUOPCU_HCUOPCU_FAW3_HVAC_V2_0DBC_DBC_RX	121U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_MAINPOSHIGHURLYCTRLCMDHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	122U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_FUELCELLRLYCTRLCMDHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	123U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_BATTHEATPTCRLYCTRLCMDHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	124U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_ACSORYRLYCTRLCMDHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	125U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_PTCRLYCTRLCMDHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	126U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_MECURLYCLOSINGREQHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	127U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_DCDCRLYCLOSINGREQHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	128U
#define  COMCONF_COMSIGNAL_HCU3_OJCG_C_ACRLYCLOSINGREQHCU3_HCU3_FAW3_HVAC_V2_0DBC_DBC_RX	129U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_DIRTCURCHRG1POSRLYCTRLCMDBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	130U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_DIRTCURCHRG1NEGRLYCTRLCMDBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	131U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_DIRTCURCHRG2POSRLYCTRLCMDBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	132U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_DIRTCURCHRG2NEGRLYCTRLCMDBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	133U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_WTRCOOLGRLYCTRLCMDBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	134U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_INSULATIONTESTERCTRLCMDBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	135U
#define  COMCONF_COMSIGNAL_BMS5_OJCG_C_MAINNEGRLYSTSBMS5_BMS5_FAW3_HVAC_V2_0DBC_DBC_RX	136U
#define  COMCONF_COMSIGNAL_MCU2_OJCG_C_MOTCTRLLERBUSUMCU2_MCU2_FAW3_HVAC_V2_0DBC_DBC_RX	137U
#define  COMCONF_COMSIGNAL_MCU2_OJCG_C_MOTCTRLLERBUSCURMCU2_MCU2_FAW3_HVAC_V2_0DBC_DBC_RX	138U
#define  COMCONF_COMSIGNAL_MCU2_OJCG_C_MOTTMCU2_MCU2_FAW3_HVAC_V2_0DBC_DBC_RX	139U
#define  COMCONF_COMSIGNAL_MCU2_OJCG_C_MOTCTRLLERTMCU2_MCU2_FAW3_HVAC_V2_0DBC_DBC_RX	140U


#define COM_TX_TIMEBASE_CAN                            (ComTxTimeBase)
#define COM_TX_TIMEBASE_LIN                            (ComTxTimeBase)
#define COM_TX_TIMEBASE_FR                             (ComTxTimeBase)
#define COM_TX_TIMEBASE_ETH                            (ComTxTimeBase)
#define COM_RX_TIMEBASE_CAN                            (ComRxTimeBase)
#define COM_RX_TIMEBASE_LIN                            (ComRxTimeBase)
#define COM_RX_TIMEBASE_FR                             (ComRxTimeBase)
#define COM_RX_TIMEBASE_ETH                            (ComRxTimeBase)

#define COM_RXPDU_NUM_5MS (21U)
#define COM_RXPDU_TOTAL_TABLES (1U)
#define Com_MainFunctionRx() Com_MainFunction_Rx(0U)
#define COM_TXPDU_NUM_5MS (23U)
#define COM_TXPDU_TOTAL_TABLES (1U)
#define Com_MainFunctionTx() Com_MainFunction_Tx(0U)
#define COM_GWINFO_NUM_5MS (0U)
#define COM_GWDSCPINFO_NUM_5MS (0U)
#define COM_GATEWAYINFO_TOTAL_TABLES (1U)
#define Com_MainFunctionRouteSignals() Com_MainFunction_RouteSignals(0U)

/*
********************************************************************************
*    Global Types
********************************************************************************
*/
typedef uint8 Com_IpduGroupVector[COM_PDUGRP_VECTOR_SIZE];

/*
********************************************************************************
*    Global Variables
********************************************************************************
*/
#define COM_START_SEC_VAR_INIT
#include "Com_MemMap.h"
#if( STD_ON == COM_PERFOPTMZ_SUPPORT)
#endif
#if( (COM_METADATA_SUPPORT == STD_ON) && (COM_TXMETADATA_NUM > COM_INIT_ZERO) )
extern VAR(Com_PduMetaDataMonitorType, COM_VAR_INIT) Com_TxPduMonMetaData[COM_TXMETADATA_NUM];
#endif /* ((COM_METADATA_SUPPORT == STD_ON) && (COM_TXMETADATA_NUM > COM_INIT_ZERO)) */
#define COM_STOP_SEC_VAR_INIT
#include "Com_MemMap.h"

/*
********************************************************************************
*    Global Constants
********************************************************************************
*/
/*
********************************************************************************
*    Global Functions
********************************************************************************
*/
#define COM_START_SEC_CONFIG_DATA
#include "Com_MemMap.h"
extern CONST(Com_SignalBaseInfo_st, COM_CONFIG_DATA) Com_SignalBaseInfo[COM_RXSIG_NUM + COM_TXSIG_NUM];
extern CONST(COM_TxSigGrpInfo_st, COM_CONFIG_DATA) Com_TxSigGrpInfo[COM_TXGRP_NUM + 1U];
extern CONST(COM_RxSigGrpInfo_st, COM_CONFIG_DATA) Com_RxSigGrpInfo[COM_RXGRP_NUM + 1U];
extern VAR(COM_TxPduInfo_st, COM_CONFIG_DATA) Com_TxPduInfo[COM_TXPDU_NUM];/* WangM CONST-->VAR */
extern VAR(COM_RxPduInfo_st, COM_CONFIG_DATA) Com_RxPduInfo[COM_RXPDU_NUM];/* WangM CONST-->VAR */
extern CONST(COM_TxModeInfo_st, COM_CONFIG_DATA) Com_TxModeInfo[COM_TXPDU_NUM];
extern CONST(Com_TxMode_st, COM_CONFIG_DATA) Com_TxModeTrue[COM_TXPDU_NUM];
extern CONST(Com_TxMode_st, COM_CONFIG_DATA) Com_TxModeFalse[COM_TXPDU_NUM];
extern CONST(COM_TxSignalInfo_st, COM_CONFIG_DATA) Com_TxSignalInfo[COM_TXSIG_NUM];
extern VAR(COM_RxSignalInfo_st, COM_CONFIG_DATA) Com_RxSignalInfo[COM_RXSIG_NUM];/* WangM CONST-->VAR */
extern CONST(uint16, COM_CONFIG_DATA) Com_PduGrpVectorMatch[COM_PDUGRP_MATCH_SIZE];
#if(COM_GWSIGNAL_SUPPORT == STD_ON)
extern CONST(Com_GwMappingSigType, COM_CONFIG_DATA) Com_GwInfo[COM_GWSIGNAL_NUM + 1U];
extern CONST(Com_GwMappingSigDscpType, COM_CONFIG_DATA) Com_GwDscpInfo[COM_GWSIGNALDSCP_NUM + 1U];
#endif
#if (COM_MULTICORE_SUPPORT == STD_ON)
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_RxPduIndex_Can[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_RxPduIndex_Lin[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_RxPduIndex_Fr[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_RxPduIndex_Eth[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_TxPduIndex_Can[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_TxPduIndex_Lin[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_TxPduIndex_Fr[COM_CORE_NUM];
extern CONST(Com_PduIndexInfo_st, COM_CONFIG_DATA)Com_TxPduIndex_Eth[COM_CORE_NUM];
#endif /* COM_MULTICORE_SUPPORT == STD_ON */

extern CONST(Com_RxPduInfoTableType, COM_CONFIG_DATA) Com_RxPduInfoTable[COM_RXPDU_TOTAL_TABLES];
extern CONST(Com_TxPduInfoTableType, COM_CONFIG_DATA) Com_TxPduInfoTable[COM_TXPDU_TOTAL_TABLES];
extern CONST(Com_GatewayInfoTableType, COM_CONFIG_DATA) Com_GatewayInfoTable[COM_GATEWAYINFO_TOTAL_TABLES];
#define COM_STOP_SEC_CONFIG_DATA
#include "Com_MemMap.h"

#endif /* COM_LCFG_H_ */

