/*
********************************************************************************
*
* File name: Dem_Types.h
*
* Copyright 2020-2024 Neusoft Reach Corporation. All rights reserved.
*
********************************************************************************
*
* History
*-------------------------------------------------------------------------------
********************************************************************************
* Version: 1.0
* Author/Date: ZhiDX/2020.10.16
* Change: New created.
* Cause: New
********************************************************************************
* Version: 3.0
* Author/Date: ZhiDX/2022.02.17
* Change: Remove type definition which should be generated by RTE.
* Cause: Bugfix
********************************************************************************
* Version: 3.1
* Author/Date: FanHT/2022.05.26
* Change: Add conditional compilation to resolve redefinitions with RTE.
* Cause: Bugfix
********************************************************************************
* Version: 3.2
* Author/Date: FanHT/2022.11.24
* Change: Add conditional compilation to resolve redefinitions with RTE.
* Cause: Bugfix
********************************************************************************
* Version: 3.3
* Author/Date: FanHT/2022.12.05
* Change: Add conditional compilation to resolve redefinitions with RTE.
* Cause: Bugfix
********************************************************************************
* Version: 3.4
* Author/Date: WangYS/2023.04.01
* Change: Modify Definition Name.
* Cause: Optimization
********************************************************************************
* Version: 3.5
* Author/Date: WangYS/2023.05.29
* Change: Adjust the space spacing of the typedef.
* Cause: Optimization
********************************************************************************
* Version: 3.6
* Author/Date: ZhangF/2023.08.14
* Change: Fix compile warning.
* Cause: Update
********************************************************************************
* Version: 3.7
* Author/Date: ZengJX/2024.03.13
* Change: Fix compile warning.
* Cause: Update
********************************************************************************
* Version: 3.8
* Author/Date: ZengJX/2024.04.01
* Change: Add comments for Rte_TypeDef_Dem_EventStatusType and 
*         Rte_TypeDef_Dem_UdsStatusByteType.
* Cause: Optimization
********************************************************************************
* Version: 3.9
* Author/Date: ZengJX/2024.04.15
* Change: Optimize comments specifications.
* Cause: Optimization
********************************************************************************
* Version: 3.10
* Author/Date: ZengJX/2024.07.18
* Change: Modify copyright information.
* Cause: Optimization
********************************************************************************
* Version: 3.11
* Author/Date: ZengJX/2024.08.14
* Change: Move application type definitions to RTE.
* Cause: Update
********************************************************************************
* Version: 3.12
* Author/Date: ZengJX/2024.09.19
* Change: Delete definitions of Dem_OperationCycleStateType，Dem_EventldType，
*         Dem_ReturnControlDTCSettingType and Dem_ReturnClearDTCType.
* Cause: Bugfix
********************************************************************************
* Version: 3.13
* Author/Date: ZengJX/2024.09.23
* Change: Add header file to fix compile warning.
* Cause: Optimization
********************************************************************************
*/
#ifndef DEM_TYPES_H_
#define DEM_TYPES_H_

/*
********************************************************************************
*    Includes
********************************************************************************
*/
#include "Std_Types.h"
#include "Rte_Dem.h"

/*
********************************************************************************
*    Global Macros
********************************************************************************
*/
typedef struct
{
    uint8 acCfgNone;
} Dem_ConfigType;

#ifndef DEM_EVENT_STATUS_PASSED
#define DEM_EVENT_STATUS_PASSED                     ((Dem_EventStatusType)0x00U)
#endif
#ifndef DEM_EVENT_STATUS_FAILED
#define DEM_EVENT_STATUS_FAILED                     ((Dem_EventStatusType)0x01U)
#endif
#ifndef DEM_EVENT_STATUS_PREPASSED
#define DEM_EVENT_STATUS_PREPASSED                  ((Dem_EventStatusType)0x02U)
#endif
#ifndef DEM_EVENT_STATUS_PREFAILED
#define DEM_EVENT_STATUS_PREFAILED                  ((Dem_EventStatusType)0x03U)
#endif
#ifndef DEM_EVENT_STATUS_FDC_THRESHOLD_REACHED
#define DEM_EVENT_STATUS_FDC_THRESHOLD_REACHED      ((Dem_EventStatusType)0x04U)
#endif
#ifndef DEM_EVENT_STATUS_NONE
#define DEM_EVENT_STATUS_NONE                       ((Dem_EventStatusType)0x05U)
#endif

#ifndef DEM_TEMPORARILY_DEFECTIVE
#define DEM_TEMPORARILY_DEFECTIVE                   ((Dem_DebouncingStateType)0x01U)
#endif
#ifndef DEM_FINALLY_DEFECTIVE
#define DEM_FINALLY_DEFECTIVE                       ((Dem_DebouncingStateType)0x02U)
#endif
#ifndef DEM_TEMPORARILY_HEALED
#define DEM_TEMPORARILY_HEALED                      ((Dem_DebouncingStateType)0x04U)
#endif
#ifndef DEM_TEST_COMPLETE
#define DEM_TEST_COMPLETE                           ((Dem_DebouncingStateType)0x08U)
#endif
#ifndef DEM_DTR_UPDATE
#define DEM_DTR_UPDATE                              ((Dem_DebouncingStateType)0x10U)
#endif

#ifndef DEM_DEBOUNCE_STATUS_FREEZE
#define DEM_DEBOUNCE_STATUS_FREEZE                  ((Dem_DebounceResetStatusType)0x00U)
#endif
#ifndef DEM_DEBOUNCE_STATUS_RESET
#define DEM_DEBOUNCE_STATUS_RESET                   ((Dem_DebounceResetStatusType)0x01U)
#endif

#ifndef DEM_UDS_STATUS_TF
#define DEM_UDS_STATUS_TF                           ((Dem_UdsStatusByteType)0x01)
#endif
#ifndef DEM_UDS_STATUS_TFTOC
#define DEM_UDS_STATUS_TFTOC                        ((Dem_UdsStatusByteType)0x02)
#endif
#ifndef DEM_UDS_STATUS_PDTC
#define DEM_UDS_STATUS_PDTC                         ((Dem_UdsStatusByteType)0x04)
#endif
#ifndef DEM_UDS_STATUS_CDTC
#define DEM_UDS_STATUS_CDTC                         ((Dem_UdsStatusByteType)0x08)
#endif
#ifndef DEM_UDS_STATUS_TNCSLC
#define DEM_UDS_STATUS_TNCSLC                       ((Dem_UdsStatusByteType)0x10)
#endif
#ifndef DEM_UDS_STATUS_TFSLC
#define DEM_UDS_STATUS_TFSLC                        ((Dem_UdsStatusByteType)0x20)
#endif
#ifndef DEM_UDS_STATUS_TNCTOC
#define DEM_UDS_STATUS_TNCTOC                       ((Dem_UdsStatusByteType)0x40)
#endif
#ifndef DEM_UDS_STATUS_WIR
#define DEM_UDS_STATUS_WIR                          ((Dem_UdsStatusByteType)0x80)
#endif

#ifndef DEM_CYCLE_STATE_START
#define DEM_CYCLE_STATE_START                       ((Dem_OperationCycleStateType)0x00U)
#endif
#ifndef DEM_CYCLE_STATE_END
#define DEM_CYCLE_STATE_END                         ((Dem_OperationCycleStateType)0x01U)
#endif

#ifndef DEM_INDICATOR_OFF
#define DEM_INDICATOR_OFF                           ((Dem_IndicatorStatusType)0x00U)
#endif
#ifndef DEM_INDICATOR_CONTINUOUS
#define DEM_INDICATOR_CONTINUOUS                    ((Dem_IndicatorStatusType)0x01U)
#endif
#ifndef DEM_INDICATOR_BLINKING
#define DEM_INDICATOR_BLINKING                      ((Dem_IndicatorStatusType)0x02U)
#endif
#ifndef DEM_INDICATOR_BLINK_CONT
#define DEM_INDICATOR_BLINK_CONT                    ((Dem_IndicatorStatusType)0x03U)
#endif
#ifndef DEM_INDICATOR_SLOW_FLASH
#define DEM_INDICATOR_SLOW_FLASH                    ((Dem_IndicatorStatusType)0x04U)
#endif
#ifndef DEM_INDICATOR_FAST_FLASH
#define DEM_INDICATOR_FAST_FLASH                    ((Dem_IndicatorStatusType)0x05U)
#endif
#ifndef DEM_INDICATOR_ON_DEMAND
#define DEM_INDICATOR_ON_DEMAND                     ((Dem_IndicatorStatusType)0x06U)
#endif
#ifndef DEM_INDICATOR_SHORT
#define DEM_INDICATOR_SHORT                         ((Dem_IndicatorStatusType)0x07U)
#endif
#ifndef DEM_INDICATOR_NONE
#define DEM_INDICATOR_NONE                          ((Dem_IndicatorStatusType)0x0FU)
#endif

#ifndef DEM_DTC_KIND_ALL_DTCS
#define DEM_DTC_KIND_ALL_DTCS                       ((Dem_DTCKindType)0x01)
#endif
#ifndef DEM_DTC_KIND_EMISSION_REL_DTCS
#define DEM_DTC_KIND_EMISSION_REL_DTCS              ((Dem_DTCKindType)0x02)
#endif

#ifndef DEM_DTC_FORMAT_OBD
#define DEM_DTC_FORMAT_OBD                          ((Dem_DTCFormatType)0U)
#endif
#ifndef DEM_DTC_FORMAT_UDS
#define DEM_DTC_FORMAT_UDS                          ((Dem_DTCFormatType)1U)
#endif
#ifndef DEM_DTC_FORMAT_J1939
#define DEM_DTC_FORMAT_J1939                        ((Dem_DTCFormatType)2U)
#endif

#ifndef DEM_DTC_ORIGIN_PRIMARY_MEMORY
#define DEM_DTC_ORIGIN_PRIMARY_MEMORY               ((Dem_DTCOriginType)0x01)
#endif
#ifndef DEM_DTC_ORIGIN_MIRROR_MEMORY
#define DEM_DTC_ORIGIN_MIRROR_MEMORY                ((Dem_DTCOriginType)0x02)
#endif
#ifndef DEM_DTC_ORIGIN_PERMANENT_MEMORY
#define DEM_DTC_ORIGIN_PERMANENT_MEMORY             ((Dem_DTCOriginType)0x03)
#endif
#ifndef DEM_DTC_ORIGIN_USERDEFINED_MEMORY_0
#define DEM_DTC_ORIGIN_USERDEFINED_MEMORY_0         ((Dem_DTCOriginType)0x10)
#endif
#ifndef DEM_DTC_ORIGIN_USERDEFINED_MEMORY_1
#define DEM_DTC_ORIGIN_USERDEFINED_MEMORY_1         ((Dem_DTCOriginType)0x11)
#endif

#ifndef Rte_TypeDef_Dem_DTCRequestType
#define Rte_TypeDef_Dem_DTCRequestType
typedef uint8 Dem_DTCRequestType;
#endif
#ifndef DEM_FIRST_FAILED_DTC
#define DEM_FIRST_FAILED_DTC                        ((Dem_DTCRequestType)0x01U)         /* first failed DTC request */
#endif
#ifndef DEM_MOST_RECENT_FAILED_DTC
#define DEM_MOST_RECENT_FAILED_DTC                  ((Dem_DTCRequestType)0x02U)         /* most recent failed DTC requested */
#endif
#ifndef DEM_FIRST_DET_CONFIRMED_DTC
#define DEM_FIRST_DET_CONFIRMED_DTC                 ((Dem_DTCRequestType)0x03U)         /* first detected confirmed DTC requested */
#endif
#ifndef DEM_MOST_REC_DET_CONFIRMED_DTC
#define DEM_MOST_REC_DET_CONFIRMED_DTC              ((Dem_DTCRequestType)0x04U)         /* most recently detected confirmed DTC requested */
#endif

#ifndef Rte_TypeDef_Dem_DTCTranslationFormatType
#define Rte_TypeDef_Dem_DTCTranslationFormatType
typedef uint8 Dem_DTCTranslationFormatType;
#endif
#ifndef DEM_DTC_TRANSLATION_ISO15031_6
#define DEM_DTC_TRANSLATION_ISO15031_6              ((Dem_DTCTranslationFormatType)0x00U)    /* DTC format ISO 15031-6 / SAE J2012-DA_DTCFormat_00. */
#endif
#ifndef DEM_DTC_TRANSLATION_ISO14229_1
#define DEM_DTC_TRANSLATION_ISO14229_1              ((Dem_DTCTranslationFormatType)0x01U)    /* DTC format ISO 14229-1. */
#endif
#ifndef DEM_DTC_TRANSLATION_SAEJ1939_73
#define DEM_DTC_TRANSLATION_SAEJ1939_73             ((Dem_DTCTranslationFormatType)0x02U)    /* DTC format SAE J1939-73. */
#endif
#ifndef DEM_DTC_TRANSLATION_ISO11992_4
#define DEM_DTC_TRANSLATION_ISO11992_4              ((Dem_DTCTranslationFormatType)0x03U)    /* DTC format ISO 11992-4. */
#endif
#ifndef DEM_DTC_TRANSLATION_J2012DA_FORMAT_04
#define DEM_DTC_TRANSLATION_J2012DA_FORMAT_04       ((Dem_DTCTranslationFormatType)0x04U)    /* DTC format SAE_J2012-DA_DTCFormat_04. */
#endif

#ifndef Rte_TypeDef_Dem_DTCSeverityType
#define Rte_TypeDef_Dem_DTCSeverityType
typedef uint8 Dem_DTCSeverityType;
#endif

#ifndef DEM_SEVERITY_NO_SEVERITY
#define DEM_SEVERITY_NO_SEVERITY                    ((Dem_DTCSeverityType)0x00U)
#endif
#ifndef DEM_SEVERITY_WWHOBD_CLASS_NO_CLASS
#define DEM_SEVERITY_WWHOBD_CLASS_NO_CLASS          ((Dem_DTCSeverityType)0x01U)
#endif
#ifndef DEM_SEVERITY_WWHOBD_CLASS_A
#define DEM_SEVERITY_WWHOBD_CLASS_A                 ((Dem_DTCSeverityType)0x02U)
#endif
#ifndef DEM_SEVERITY_WWHOBD_CLASS_B1
#define DEM_SEVERITY_WWHOBD_CLASS_B1                ((Dem_DTCSeverityType)0x04U)
#endif
#ifndef DEM_SEVERITY_WWHOBD_CLASS_B2
#define DEM_SEVERITY_WWHOBD_CLASS_B2                ((Dem_DTCSeverityType)0x08U)
#endif
#ifndef DEM_SEVERITY_WWHOBD_CLASS_C
#define DEM_SEVERITY_WWHOBD_CLASS_C                 ((Dem_DTCSeverityType)0x10U)
#endif
#define DTC_CLASS                                   ((Dem_DTCSeverityType)0x1fU)
#ifndef DEM_SEVERITY_MAINTENANCE_ONLY
#define DEM_SEVERITY_MAINTENANCE_ONLY               ((Dem_DTCSeverityType)0x20U)
#endif
#ifndef DEM_SEVERITY_CHECK_AT_NEXT_HALT
#define DEM_SEVERITY_CHECK_AT_NEXT_HALT             ((Dem_DTCSeverityType)0x40U)
#endif
#ifndef DEM_SEVERITY_CHECK_IMMEDIATELY
#define DEM_SEVERITY_CHECK_IMMEDIATELY              ((Dem_DTCSeverityType)0x80U)
#endif

#ifndef DEM_DTR_CTL_NORMAL
#define DEM_DTR_CTL_NORMAL                          ((Dem_DTRControlType)0x00)
#endif
#ifndef DEM_DTR_CTL_NO_MAX
#define DEM_DTR_CTL_NO_MAX                          ((Dem_DTRControlType)0x01)
#endif
#ifndef DEM_DTR_CTL_NO_MIN
#define DEM_DTR_CTL_NO_MIN                          ((Dem_DTRControlType)0x02)
#endif
#ifndef DEM_DTR_CTL_RESET
#define DEM_DTR_CTL_RESET                           ((Dem_DTRControlType)0x03)
#endif
#ifndef DEM_DTR_CTL_INVISIBLE
#define DEM_DTR_CTL_INVISIBLE                       ((Dem_DTRControlType)0x04)
#endif

#ifndef Rte_TypeDef_Dem_InitMonitorReasonType
#define Rte_TypeDef_Dem_InitMonitorReasonType
typedef uint8 Dem_InitMonitorReasonType;
#endif
#ifndef DEM_INIT_MONITOR_NONE
#define DEM_INIT_MONITOR_NONE                       ((Dem_InitMonitorReasonType)0x00U)
#endif
#ifndef DEM_INIT_MONITOR_CLEAR
#define DEM_INIT_MONITOR_CLEAR                      ((Dem_InitMonitorReasonType)0x01U)
#endif
#ifndef DEM_INIT_MONITOR_RESTART
#define DEM_INIT_MONITOR_RESTART                    ((Dem_InitMonitorReasonType)0x02U)
#endif
#ifndef DEM_INIT_MONITOR_REENABLED
#define DEM_INIT_MONITOR_REENABLED                  ((Dem_InitMonitorReasonType)0x03U)
#endif
#ifndef DEM_INIT_MONITOR_STORAGE_REENABLED
#define DEM_INIT_MONITOR_STORAGE_REENABLED          ((Dem_InitMonitorReasonType)0x04U)
#endif

#ifndef DEM_IUMPR_GENERAL_DENOMINATOR
#define DEM_IUMPR_GENERAL_DENOMINATOR               ((Dem_IumprDenomCondIdType)0x01)
#endif
#ifndef DEM_IUMPR_DEN_COND_COLDSTART
#define DEM_IUMPR_DEN_COND_COLDSTART                ((Dem_IumprDenomCondIdType)0x02)
#endif
#ifndef DEM_IUMPR_DEN_COND_EVAP
#define DEM_IUMPR_DEN_COND_EVAP                     ((Dem_IumprDenomCondIdType)0x03)
#endif
#ifndef DEM_IUMPR_DEN_COND_500MI
#define DEM_IUMPR_DEN_COND_500MI                    ((Dem_IumprDenomCondIdType)0x04)
#endif

#ifndef DEM_IUMPR_DEN_STATUS_NOT_REACHED
#define DEM_IUMPR_DEN_STATUS_NOT_REACHED            ((Dem_IumprDenomCondStatusType)0x00U)     /* Condition of IUMPRDenominator given by IUMPRDenCondId is not met (yet). */
#endif
#ifndef DEM_IUMPR_DEN_STATUS_REACHED
#define DEM_IUMPR_DEN_STATUS_REACHED                ((Dem_IumprDenomCondStatusType)0x01U)     /* Condition of IUMPRDenominator given by IUMPRDenCondId is met. */
#endif
#ifndef DEM_IUMPR_DEN_STATUS_INHIBITED
#define DEM_IUMPR_DEN_STATUS_INHIBITED              ((Dem_IumprDenomCondStatusType)0x02U)     /* Condition of IUMPRDenominator given by IUMPRDenCondId is inhibited and cannot be reached. */
#endif

#ifndef Rte_TypeDef_Dem_J1939DcmDTCStatusFilterType
#define Rte_TypeDef_Dem_J1939DcmDTCStatusFilterType
typedef uint8 Dem_J1939DcmDTCStatusFilterType;
#endif
#ifndef DEM_J1939DTC_ACTIVE
#define DEM_J1939DTC_ACTIVE                         ((Dem_J1939DcmDTCStatusFilterType)0x00)
#endif
#ifndef DEM_J1939DTC_PREVIOUSLY_ACTIVE
#define DEM_J1939DTC_PREVIOUSLY_ACTIVE              ((Dem_J1939DcmDTCStatusFilterType)0x01)
#endif
#ifndef DEM_J1939DTC_PENDING
#define DEM_J1939DTC_PENDING                        ((Dem_J1939DcmDTCStatusFilterType)0x02)
#endif
#ifndef DEM_J1939DTC_PERMANENT
#define DEM_J1939DTC_PERMANENT                      ((Dem_J1939DcmDTCStatusFilterType)0x03)
#endif
#ifndef DEM_J1939DTC_CURRENTLY_ACTIVE
#define DEM_J1939DTC_CURRENTLY_ACTIVE               ((Dem_J1939DcmDTCStatusFilterType)0x04)
#endif

#ifndef Rte_TypeDef_Dem_J1939DcmSetClearFilterType
#define Rte_TypeDef_Dem_J1939DcmSetClearFilterType
typedef uint8 Dem_J1939DcmSetClearFilterType;
#endif
#ifndef DEM_J1939DTC_CLEAR_ALL
#define DEM_J1939DTC_CLEAR_ALL                      ((Dem_J1939DcmSetClearFilterType)0x00)
#endif
#ifndef DEM_J1939DTC_CLEAR_PREVIOUSLY_ACTIVE
#define DEM_J1939DTC_CLEAR_PREVIOUSLY_ACTIVE        ((Dem_J1939DcmSetClearFilterType)0x01)
#endif

#ifndef Rte_TypeDef_Dem_J1939DcmSetFreezeFrameFilterType
#define Rte_TypeDef_Dem_J1939DcmSetFreezeFrameFilterType
typedef uint8 Dem_J1939DcmSetFreezeFrameFilterType;
#endif
#ifndef DEM_J1939DCM_FREEZEFRAME
#define DEM_J1939DCM_FREEZEFRAME                    ((Dem_J1939DcmSetFreezeFrameFilterType)0x00)
#endif
#ifndef DEM_J1939DCM_EXPANDED_FREEZEFRAME
#define DEM_J1939DCM_EXPANDED_FREEZEFRAME           ((Dem_J1939DcmSetFreezeFrameFilterType)0x01)
#endif
#ifndef DEM_J1939DCM_SPNS_IN_EXPANDED_FREEZEFRAME
#define DEM_J1939DCM_SPNS_IN_EXPANDED_FREEZEFRAME   ((Dem_J1939DcmSetFreezeFrameFilterType)0x02)
#endif

#ifndef Rte_TypeDef_Dem_J1939DcmLampStatusType
#define Rte_TypeDef_Dem_J1939DcmLampStatusType
typedef uint16 Dem_J1939DcmLampStatusType;
#endif

typedef struct
{
    uint8 ActiveTroubleCodes;
    uint8 PreviouslyActiveDiagnosticTroubleCodes;
    uint8 OBDCompliance;
    uint8 ContinuouslyMonitoredSystemsSupport_Status;
    uint16 NonContinuouslyMonitoredSystemsSupport;
    uint16 NonContinuouslyMonitoredSystemsStatus;
} Dem_J1939DcmDiagnosticReadiness1Type;

typedef struct
{
    uint16 DistanceTraveledWhileMILisActivated;
    uint16 DistanceSinceDTCsCleared;
    uint16 MinutesRunbyEngineWhileMILisActivated;
    uint16 TimeSinceDiagnosticTroubleCodesCleared;
} Dem_J1939DcmDiagnosticReadiness2Type;

typedef struct
{
    uint16 TimeSinceEngineStart;
    uint8 NumberofWarmupsSinceDTCsCleared;
    uint8 ContinuouslyMonitoredSystemsEnableCompletedStatus;
    uint16 NonContinuouslyMonitoredSystemsEnableStatus;
    uint16 NonContinuouslyMonitoredSystems;
} Dem_J1939DcmDiagnosticReadiness3Type;

typedef uint8 Dem_ReturnGetStatusOfDTCType;
#ifndef DEM_STATUS_OK
#define DEM_STATUS_OK                               ((Dem_ReturnGetStatusOfDTCType)0x00U)
#endif
#ifndef DEM_STATUS_WRONG_DTC
#define DEM_STATUS_WRONG_DTC                        ((Dem_ReturnGetStatusOfDTCType)0x01U)
#endif
#ifndef DEM_STATUS_WRONG_DTCORIGIN
#define DEM_STATUS_WRONG_DTCORIGIN                  ((Dem_ReturnGetStatusOfDTCType)0x02U)
#endif
#ifndef DEM_STATUS_FAILED
#define DEM_STATUS_FAILED                           ((Dem_ReturnGetStatusOfDTCType)0x03U)
#endif
#ifndef DEM_STATUS_PENDING
#define DEM_STATUS_PENDING                          ((Dem_ReturnGetStatusOfDTCType)0x04U)
#endif

typedef uint8 Dem_ReturnGetSeverityOfDTCType;
#ifndef DEM_GET_SEVERITYOFDTC_OK
#define DEM_GET_SEVERITYOFDTC_OK                    ((Dem_ReturnGetSeverityOfDTCType)(0x00U))  /* Severity successfully returned. */
#endif
#ifndef DEM_GET_SEVERITYOFDTC_WRONG_DTC
#define DEM_GET_SEVERITYOFDTC_WRONG_DTC             ((Dem_ReturnGetSeverityOfDTCType)(0x01U))  /* DTC value not existing (in UDS format). */
#endif
#ifndef DEM_GET_SEVERITYOFDTC_NOSEVERITY
#define DEM_GET_SEVERITYOFDTC_NOSEVERITY            ((Dem_ReturnGetSeverityOfDTCType)(0x02U))  /* Severity information is not available. */
#endif
#ifndef DEM_GET_SEVERITYOFDTC_PENDING
#define DEM_GET_SEVERITYOFDTC_PENDING               ((Dem_ReturnGetSeverityOfDTCType)(0x03U))  /* The requested value is calculated asynchronously and currently not available. The caller can retry later. */
#endif

typedef uint8 Dem_ReturnGetFunctionalUnitOfDTCType;
#ifndef DEM_GET_FUNCTIONALUNITOFDTC_OK
#define DEM_GET_FUNCTIONALUNITOFDTC_OK              ((Dem_ReturnGetFunctionalUnitOfDTCType)0x00U)
#endif
#ifndef DEM_GET_FUNCTIONALUNITOFDTC_WRONG_DTC
#define DEM_GET_FUNCTIONALUNITOFDTC_WRONG_DTC       ((Dem_ReturnGetFunctionalUnitOfDTCType)0x01U)
#endif
#ifndef DEM_GET_FUNCTIONALUNITOFDTC_PENDING
#define DEM_GET_FUNCTIONALUNITOFDTC_PENDING         ((Dem_ReturnGetFunctionalUnitOfDTCType)0x02U)
#endif

typedef uint8 Dem_ReturnSetFilterType;
#ifndef DEM_FILTER_ACCEPTED
#define DEM_FILTER_ACCEPTED                         ((Dem_ReturnSetFilterType)(0x00U))  /* Filter was accepted. */
#endif
#ifndef DEM_WRONG_FILTER
#define DEM_WRONG_FILTER                            ((Dem_ReturnSetFilterType)(0x01U))  /* Wrong filter selected. */
#endif

typedef uint8 Dem_ReturnGetNumberOfFilteredDTCType;
#ifndef DEM_NUMBER_OK
#define DEM_NUMBER_OK                               ((Dem_ReturnGetNumberOfFilteredDTCType)0x00)
#endif
#ifndef DEM_NUMBER_FAILED
#define DEM_NUMBER_FAILED                           ((Dem_ReturnGetNumberOfFilteredDTCType)0x01)
#endif
#ifndef DEM_NUMBER_PENDING
#define DEM_NUMBER_PENDING                          ((Dem_ReturnGetNumberOfFilteredDTCType)0x02)
#endif

typedef uint8 Dem_ReturnGetNextFilteredElementType;
#ifndef DEM_FILTERED_OK
#define DEM_FILTERED_OK                             ((Dem_ReturnGetNextFilteredElementType)0x00)
#endif
#ifndef DEM_FILTERED_NO_MATCHING_ELEMENT
#define DEM_FILTERED_NO_MATCHING_ELEMENT            ((Dem_ReturnGetNextFilteredElementType)0x01)
#endif
#ifndef DEM_FILTERED_PENDING
#define DEM_FILTERED_PENDING                        ((Dem_ReturnGetNextFilteredElementType)0x02)
#endif
#ifndef DEM_FILTERED_BUFFER_TOO_SMALL
#define DEM_FILTERED_BUFFER_TOO_SMALL               ((Dem_ReturnGetNextFilteredElementType)0x03)
#endif

typedef uint8 Dem_ReturnGetDTCByOccurrenceTimeType;
#ifndef DEM_OCCURR_OK
#define DEM_OCCURR_OK                               ((Dem_ReturnGetDTCByOccurrenceTimeType)0x00)
#endif
#ifndef DEM_OCCURR_NOT_AVAILABLE
#define DEM_OCCURR_NOT_AVAILABLE                    ((Dem_ReturnGetDTCByOccurrenceTimeType)0x01)
#endif

typedef uint8 Dem_ReturnDisableDTCRecordUpdateType;
#ifndef DEM_DISABLE_DTCRECUP_OK
#define DEM_DISABLE_DTCRECUP_OK                     ((Dem_ReturnDisableDTCRecordUpdateType)0x00)
#endif
#ifndef DEM_DISABLE_DTCRECUP_WRONG_DTC
#define DEM_DISABLE_DTCRECUP_WRONG_DTC              ((Dem_ReturnDisableDTCRecordUpdateType)0x01)
#endif
#ifndef DEM_DISABLE_DTCRECUP_WRONG_DTCORIGIN
#define DEM_DISABLE_DTCRECUP_WRONG_DTCORIGIN        ((Dem_ReturnDisableDTCRecordUpdateType)0x02)
#endif
#ifndef DEM_DISABLE_DTCRECUP_PENDING
#define DEM_DISABLE_DTCRECUP_PENDING                ((Dem_ReturnDisableDTCRecordUpdateType)0x03)
#endif

typedef uint8 Dem_ReturnGetFreezeFrameDataByDTCType;
#ifndef DEM_GET_FFDATABYDTC_OK
#define DEM_GET_FFDATABYDTC_OK                      ((Dem_ReturnGetFreezeFrameDataByDTCType)0x00)
#endif
#ifndef DEM_GET_FFDATABYDTC_WRONG_DTC
#define DEM_GET_FFDATABYDTC_WRONG_DTC               ((Dem_ReturnGetFreezeFrameDataByDTCType)0x01)
#endif
#ifndef DEM_GET_FFDATABYDTC_WRONG_DTCORIGIN
#define DEM_GET_FFDATABYDTC_WRONG_DTCORIGIN         ((Dem_ReturnGetFreezeFrameDataByDTCType)0x02)
#endif
#ifndef DEM_GET_FFDATABYDTC_WRONG_RECORDNUMBER
#define DEM_GET_FFDATABYDTC_WRONG_RECORDNUMBER      ((Dem_ReturnGetFreezeFrameDataByDTCType)0x03)
#endif
#ifndef DEM_GET_FFDATABYDTC_WRONG_BUFFERSIZE
#define DEM_GET_FFDATABYDTC_WRONG_BUFFERSIZE        ((Dem_ReturnGetFreezeFrameDataByDTCType)0x04)
#endif
#ifndef DEM_GET_FFDATABYDTC_PENDING
#define DEM_GET_FFDATABYDTC_PENDING                 ((Dem_ReturnGetFreezeFrameDataByDTCType)0x05)
#endif

typedef uint8 Dem_ReturnGetExtendedDataRecordByDTCType;
#ifndef DEM_RECORD_OK
#define DEM_RECORD_OK                               ((Dem_ReturnGetExtendedDataRecordByDTCType)0x00)
#endif
#ifndef DEM_RECORD_WRONG_DTC
#define DEM_RECORD_WRONG_DTC                        ((Dem_ReturnGetExtendedDataRecordByDTCType)0x01)
#endif
#ifndef DEM_RECORD_WRONG_DTCORIGIN
#define DEM_RECORD_WRONG_DTCORIGIN                  ((Dem_ReturnGetExtendedDataRecordByDTCType)0x02)
#endif
#ifndef DEM_RECORD_WRONG_NUMBER
#define DEM_RECORD_WRONG_NUMBER                     ((Dem_ReturnGetExtendedDataRecordByDTCType)0x03)
#endif
#ifndef DEM_RECORD_WRONG_BUFFERSIZE
#define DEM_RECORD_WRONG_BUFFERSIZE                 ((Dem_ReturnGetExtendedDataRecordByDTCType)0x04)
#endif
#ifndef DEM_RECORD_PENDING
#define DEM_RECORD_PENDING                          ((Dem_ReturnGetExtendedDataRecordByDTCType)0x05)
#endif

typedef uint8 Dem_ReturnGetSizeOfDataByDTCType;
#ifndef DEM_GETSIZEBYDTC_OK
#define DEM_GETSIZEBYDTC_OK                         ((Dem_ReturnGetSizeOfDataByDTCType)0x00)
#endif
#ifndef DEM_GETSIZEBYDTC_WRONG_DTC
#define DEM_GETSIZEBYDTC_WRONG_DTC                  ((Dem_ReturnGetSizeOfDataByDTCType)0x01)
#endif
#ifndef DEM_GETSIZEBYDTC_WRONG_DTCORIGIN
#define DEM_GETSIZEBYDTC_WRONG_DTCORIGIN            ((Dem_ReturnGetSizeOfDataByDTCType)0x02)
#endif
#ifndef DEM_GETSIZEBYDTC_WRONG_RECNUM
#define DEM_GETSIZEBYDTC_WRONG_RECNUM               ((Dem_ReturnGetSizeOfDataByDTCType)0x03)
#endif
#ifndef DEM_GETSIZEBYDTC_PENDING
#define DEM_GETSIZEBYDTC_PENDING                    ((Dem_ReturnGetSizeOfDataByDTCType)0x04)
#endif

#ifndef DEM_CLEAR_OK
#define DEM_CLEAR_OK                                ((Dem_ReturnClearDTCType)(0x00U))  /* DTC successfully cleared. */
#endif
#ifndef DEM_CLEAR_WRONG_DTC
#define DEM_CLEAR_WRONG_DTC                         ((Dem_ReturnClearDTCType)(0x01U))  /* DTC value not existing (in this format). */
#endif
#ifndef DEM_CLEAR_WRONG_DTCORIGIN
#define DEM_CLEAR_WRONG_DTCORIGIN                   ((Dem_ReturnClearDTCType)(0x02U))  /* Wrong DTC origin. */
#endif
#ifndef DEM_CLEAR_FAILED
#define DEM_CLEAR_FAILED                            ((Dem_ReturnClearDTCType)(0x03U))  /* DTC clearing failed. */
#endif
#ifndef DEM_CLEAR_PENDING
#define DEM_CLEAR_PENDING                           ((Dem_ReturnClearDTCType)(0x04U))  /* The DTC clearing is performed asynchronously and still pending. The caller can retry later. */
#endif
#ifndef DEM_CLEAR_BUSY
#define DEM_CLEAR_BUSY                              ((Dem_ReturnClearDTCType)(0x05U))  /* DTC not cleared, as another clearing process is in progress. The caller can retry later. */
#endif
#ifndef DEM_CLEAR_MEMORY_ERROR
#define DEM_CLEAR_MEMORY_ERROR                      ((Dem_ReturnClearDTCType)(0x06U))  /* An error occurred during erasing a non-volatile memory location. */
#endif

#ifndef DEM_CONTROL_DTC_SETTING_OK
#define DEM_CONTROL_DTC_SETTING_OK                  ((Dem_ReturnControlDTCSettingType)(0x00U))
#endif
#ifndef DEM_CONTROL_DTC_SETTING_N_OK
#define DEM_CONTROL_DTC_SETTING_N_OK                ((Dem_ReturnControlDTCSettingType)(0x01U))
#endif
#ifndef DEM_CONTROL_DTC_WRONG_DTCGROUP
#define DEM_CONTROL_DTC_WRONG_DTCGROUP              ((Dem_ReturnControlDTCSettingType)(0x02U))
#endif

#ifndef Rte_TypeDef_Dem_EventStatusExtendedType
#define Rte_TypeDef_Dem_EventStatusExtendedType
typedef uint8 Dem_EventStatusExtendedType;
#endif

/*
********************************************************************************
*    Global Types
********************************************************************************
*/
/*
********************************************************************************
*    Global Variables
********************************************************************************
*/
/*
********************************************************************************
*    Global Constants
********************************************************************************
*/
/*
********************************************************************************
*    Global Functions
********************************************************************************
*/

#endif /* DEM_TYPES_H_ */
