/*************************************************************************************
 *  FILE:           X:\Projects\FAW_OS\TASKING_V6.0r1\FAW_MultiCore297_Demo\01_MV4_ECU_V01\T1_Config\T1\src\T1_configGen.c
 *
 *  DESCRIPTION:    this file was generated by perl script T1_projGen.pl
 *
 *  AUTHOR:         GLIWA GmbH
 *
 *  COPYRIGHT:      GLIWA GmbH | know-how in embedded software
 *                  Weilheim i.OB.
 *                  All rights reserved
 ************************************************************************************/

/*----------------------------------------------------------------------------------*/
/*--- header includes --------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#include "T1_AppInterface.h"


/*----------------------------------------------------------------------------------*/
/*--- Config variables -------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#if defined T1_NOF_CORES
#   if 3 != T1_NOF_CORES
#       error T1_NOF_CORES does not match generated configuration
#   endif /* 3 != T1_NOF_CORES */
#else /* ! defined T1_NOF_CORES */
#   error T1_NOF_CORES is not defined and generated configuration is for multi-core T1
#endif /* defined T1_NOF_CORES */

#if defined T1_ENABLE && !defined T1_DISABLE_T1_BASE

#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_commsCoreOffset = 0u;
#   if !defined T1_EXTERNAL_BID
T1_EXTERN T1_uint8_t const T1_SEC_CONST_8 T1_CAT( T1_bid_, T1_BUILD_ID );
T1_uint8_t const        T1_SEC_CONST_8 T1_CAT( T1_bid_, T1_BUILD_ID ) = 0u;
#   endif /* !defined T1_EXTERNAL_BID */
#   if !defined T1_NO_INIT_SID
T1_uint8_t const        T1_SEC_CONST_8 T1_sid = T1_SID;
#   endif /* !defined T1_NO_INIT_SID */
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   if defined T1_NO_INIT_SID
#       define T1_START_SEC_NO_INIT_8
#       include "T1_MemMap.h"
T1_uint8_t              T1_SEC_NO_INIT_8 T1_sid;
#       define T1_STOP_SEC_NO_INIT_8
#       include "T1_MemMap.h"
#   endif /* defined T1_NO_INIT_SID */
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_timeouts_t const     T1_SEC_CONST_16 T1_timeouts = { T1_TIMEOUT_RX, T1_TIMEOUT_TX, T1_TIMEOUT_RESPONSE };
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
#   if !defined T1_EXTERNAL_BID
T1_uint8_t const * const T1_SEC_CONST_32 T1_pBid = &T1_CAT( T1_bid_, T1_BUILD_ID );
T1_uint32_t const       T1_SEC_CONST_32 T1_bid = T1_CAT( T1_BUILD_ID, uL );
#   endif /* !defined T1_EXTERNAL_BID */
T1_featureMask_t const  T1_SEC_CONST_32 T1_initFeatureMask = T1_INIT_FEATURE_MASK;
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   if defined T1_CPU32BIT
#       define T1_START_SEC_CONST_8
#       include "T1_MemMap.h"
T1_bool_t const         T1_SEC_CONST_8 T1_traceTimerBitLengthPC[3] =
{
    T1_TRACE_TIMER_BIT_LENGTH_CORE0,
    T1_TRACE_TIMER_BIT_LENGTH_CORE1,
    T1_TRACE_TIMER_BIT_LENGTH_CORE2
};
#       define T1_STOP_SEC_CONST_8
#       include "T1_MemMap.h"
#   endif /* defined T1_CPU32BIT */
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_nofCores = T1_NOF_CORES;
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_baseGlobals_t        T1_SEC_NO_INIT_32_CORE0 T1_baseGlobals0;
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_baseGlobals_t        T1_SEC_NO_INIT_32_CORE1 T1_baseGlobals1;
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_baseGlobals_t        T1_SEC_NO_INIT_32_CORE2 T1_baseGlobals2;
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_baseGlobals_t * const T1_SEC_CONST_32 T1_baseGlobalsPC[3] =
{
    &T1_baseGlobals0,
    &T1_baseGlobals1,
    &T1_baseGlobals2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"

#endif /* defined T1_ENABLE && !defined T1_DISABLE_T1_BASE */

#if defined T1_ENABLE && !defined T1_DISABLE_T1_CONT

#   if 8 != T1_CONT_NOF_VRTL_STPWS && 64 != T1_CONT_NOF_VRTL_STPWS
#       error Unsupported number of event chains configured (must be 8 or 64)
#   endif /* 8 != T1_CONT_NOF_VRTL_STPWS && 64 != T1_CONT_NOF_VRTL_STPWS */

#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_nOfVrtlStpws = T1_CONT_NOF_VRTL_STPWS;
T1_uint8_t const        T1_SEC_CONST_8 T1_nofFocusMeasurements = T1_CONT_NOF_FOCUS_MEASUREMENTS;
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_NOF_RESULTS_CORE0 \
    (T1_NOF_TASKS_CORE0 + 2*(T1_NOF_USER_STPWS_CORE0 + T1_NOF_FLEX_STPWS_CORE0 + T1_CONT_NOF_VRTL_STPWS) + 3u)
#   if !defined T1_OVERHEAD_CORE0_NS
#       error T1_OVERHEAD_CORE0_NS not defined
#   endif /* T1_OVERHEAD_CORE0_NS */
#   if !defined T1_FLEX_OVERHEAD_CORE0_NS
#       error T1_FLEX_OVERHEAD_CORE0_NS not defined
#   endif /* T1_FLEX_OVERHEAD_CORE0_NS */
#   if !defined T1_CPULOAD_TX_PERIOD_CORE0
#       error T1_CPULOAD_TX_PERIOD_CORE0 not defined
#   endif /* T1_CPULOAD_TX_PERIOD_CORE0 */
#   if !defined T1_CPULOAD_SAMPLES_CORE0
#       error T1_CPULOAD_SAMPLES_CORE0 not defined
#   endif /* T1_CPULOAD_SAMPLES_CORE0 */
#   if !defined T1_NOF_TASKS_CORE0
#       error T1_NOF_TASKS_CORE0 not defined
#   endif /* T1_NOF_TASKS_CORE0 */
#   if !defined T1_NOF_USER_STPWS_CORE0
#       error T1_NOF_USER_STPWS_CORE0 not defined
#       if 1 != T1_NOF_USER_STPWS_CORE0
#           error T1_NOF_USER_STPWS_CORE0 does not match generated configuration
#       endif /* 1 != T1_NOF_USER_STPWS_CORE0 */
#   endif /* T1_NOF_USER_STPWS_CORE0 */
#   if !defined T1_NOF_CSRNS_CORE0
#       error T1_NOF_CSRNS_CORE0 not defined
#       if 2 != T1_NOF_CSRNS_CORE0
#           error T1_NOF_CSRNS_CORE0 does not match generated configuration
#       endif /* 2 != T1_NOF_CSRNS_CORE0 */
#   endif /* T1_NOF_CSRNS_CORE0 */
#   if !defined T1_NOF_FLEX_STPWS_CORE0
#       error T1_NOF_FLEX_STPWS_CORE0 not defined
#   endif /* T1_NOF_FLEX_STPWS_CORE0 */
#   if !defined T1_DISABLE_T1_FLEX && T1_NOF_FLEX_STPWS_CORE0 < 1
#       error At least one core 0 T1.flex stopwatch is required
#   endif /* T1_NOF_FLEX_STPWS_CORE0 */
#   define T1_NOF_RESULTS_CORE1 \
    (T1_NOF_TASKS_CORE1 + 2*(T1_NOF_USER_STPWS_CORE1 + T1_NOF_FLEX_STPWS_CORE1 + T1_CONT_NOF_VRTL_STPWS) + 3u)
#   if !defined T1_OVERHEAD_CORE1_NS
#       error T1_OVERHEAD_CORE1_NS not defined
#   endif /* T1_OVERHEAD_CORE1_NS */
#   if !defined T1_FLEX_OVERHEAD_CORE1_NS
#       error T1_FLEX_OVERHEAD_CORE1_NS not defined
#   endif /* T1_FLEX_OVERHEAD_CORE1_NS */
#   if !defined T1_CPULOAD_TX_PERIOD_CORE1
#       error T1_CPULOAD_TX_PERIOD_CORE1 not defined
#   endif /* T1_CPULOAD_TX_PERIOD_CORE1 */
#   if !defined T1_CPULOAD_SAMPLES_CORE1
#       error T1_CPULOAD_SAMPLES_CORE1 not defined
#   endif /* T1_CPULOAD_SAMPLES_CORE1 */
#   if !defined T1_NOF_TASKS_CORE1
#       error T1_NOF_TASKS_CORE1 not defined
#   endif /* T1_NOF_TASKS_CORE1 */
#   if !defined T1_NOF_USER_STPWS_CORE1
#       error T1_NOF_USER_STPWS_CORE1 not defined
#       if 1 != T1_NOF_USER_STPWS_CORE1
#           error T1_NOF_USER_STPWS_CORE1 does not match generated configuration
#       endif /* 1 != T1_NOF_USER_STPWS_CORE1 */
#   endif /* T1_NOF_USER_STPWS_CORE1 */
#   if !defined T1_NOF_CSRNS_CORE1
#       error T1_NOF_CSRNS_CORE1 not defined
#       if 2 != T1_NOF_CSRNS_CORE1
#           error T1_NOF_CSRNS_CORE1 does not match generated configuration
#       endif /* 2 != T1_NOF_CSRNS_CORE1 */
#   endif /* T1_NOF_CSRNS_CORE1 */
#   if !defined T1_NOF_FLEX_STPWS_CORE1
#       error T1_NOF_FLEX_STPWS_CORE1 not defined
#   endif /* T1_NOF_FLEX_STPWS_CORE1 */
#   if !defined T1_DISABLE_T1_FLEX && T1_NOF_FLEX_STPWS_CORE1 < 1
#       error At least one core 1 T1.flex stopwatch is required
#   endif /* T1_NOF_FLEX_STPWS_CORE1 */
#   define T1_NOF_RESULTS_CORE2 \
    (T1_NOF_TASKS_CORE2 + 2*(T1_NOF_USER_STPWS_CORE2 + T1_NOF_FLEX_STPWS_CORE2 + T1_CONT_NOF_VRTL_STPWS) + 3u)
#   if !defined T1_OVERHEAD_CORE2_NS
#       error T1_OVERHEAD_CORE2_NS not defined
#   endif /* T1_OVERHEAD_CORE2_NS */
#   if !defined T1_FLEX_OVERHEAD_CORE2_NS
#       error T1_FLEX_OVERHEAD_CORE2_NS not defined
#   endif /* T1_FLEX_OVERHEAD_CORE2_NS */
#   if !defined T1_CPULOAD_TX_PERIOD_CORE2
#       error T1_CPULOAD_TX_PERIOD_CORE2 not defined
#   endif /* T1_CPULOAD_TX_PERIOD_CORE2 */
#   if !defined T1_CPULOAD_SAMPLES_CORE2
#       error T1_CPULOAD_SAMPLES_CORE2 not defined
#   endif /* T1_CPULOAD_SAMPLES_CORE2 */
#   if !defined T1_NOF_TASKS_CORE2
#       error T1_NOF_TASKS_CORE2 not defined
#   endif /* T1_NOF_TASKS_CORE2 */
#   if !defined T1_NOF_USER_STPWS_CORE2
#       error T1_NOF_USER_STPWS_CORE2 not defined
#       if 1 != T1_NOF_USER_STPWS_CORE2
#           error T1_NOF_USER_STPWS_CORE2 does not match generated configuration
#       endif /* 1 != T1_NOF_USER_STPWS_CORE2 */
#   endif /* T1_NOF_USER_STPWS_CORE2 */
#   if !defined T1_NOF_CSRNS_CORE2
#       error T1_NOF_CSRNS_CORE2 not defined
#       if 2 != T1_NOF_CSRNS_CORE2
#           error T1_NOF_CSRNS_CORE2 does not match generated configuration
#       endif /* 2 != T1_NOF_CSRNS_CORE2 */
#   endif /* T1_NOF_CSRNS_CORE2 */
#   if !defined T1_NOF_FLEX_STPWS_CORE2
#       error T1_NOF_FLEX_STPWS_CORE2 not defined
#   endif /* T1_NOF_FLEX_STPWS_CORE2 */
#   if !defined T1_DISABLE_T1_FLEX && T1_NOF_FLEX_STPWS_CORE2 < 1
#       error At least one core 2 T1.flex stopwatch is required
#   endif /* T1_NOF_FLEX_STPWS_CORE2 */
#   define T1_START_SEC_NO_INIT_8
#   include "T1_MemMap.h"
T1_contStatus_t         T1_SEC_NO_INIT_8 T1_contBgStatusPC[3];
T1_contStatus_t         T1_SEC_NO_INIT_8 T1_contHandlerStatusPC[3];
#   define T1_STOP_SEC_NO_INIT_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_contScopeGlobals_t   T1_SEC_NO_INIT_32_CORE0 T1_contGlobals0;
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_contScopeGlobals_t   T1_SEC_NO_INIT_32_CORE1 T1_contGlobals1;
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_contScopeGlobals_t   T1_SEC_NO_INIT_32_CORE2 T1_contGlobals2;
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_contScopeGlobals_t * const T1_SEC_CONST_32 T1_contGlobalsPC[3] =
{
    &T1_contGlobals0,
    &T1_contGlobals1,
    &T1_contGlobals2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_stpwData_t           T1_SEC_NO_INIT_32_CORE0 T1_stpwData0[T1_NOF_USER_STPWS_CORE0 + T1_NOF_FLEX_STPWS_CORE0 + T1_CONT_NOF_VRTL_STPWS];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_stpwData_t           T1_SEC_NO_INIT_32_CORE1 T1_stpwData1[T1_NOF_USER_STPWS_CORE1 + T1_NOF_FLEX_STPWS_CORE1 + T1_CONT_NOF_VRTL_STPWS];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_stpwData_t           T1_SEC_NO_INIT_32_CORE2 T1_stpwData2[T1_NOF_USER_STPWS_CORE2 + T1_NOF_FLEX_STPWS_CORE2 + T1_CONT_NOF_VRTL_STPWS];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_stpwData_t * const   T1_SEC_CONST_32 T1_stpwDataPC[3] =
{
    T1_stpwData0,
    T1_stpwData1,
    T1_stpwData2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_csrnData_t           T1_SEC_NO_INIT_32_CORE0 T1_csrnData0[T1_NOF_CSRNS_CORE0];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_csrnData_t           T1_SEC_NO_INIT_32_CORE1 T1_csrnData1[T1_NOF_CSRNS_CORE1];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_csrnData_t           T1_SEC_NO_INIT_32_CORE2 T1_csrnData2[T1_NOF_CSRNS_CORE2];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_csrnData_t * const   T1_SEC_CONST_32 T1_csrnDataPC[3] =
{
    T1_csrnData0,
    T1_csrnData1,
    T1_csrnData2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_resultTime_t         T1_SEC_NO_INIT_32_CORE0 T1_resultBuffer0[((T1_NOF_RESULTS_CORE0 + 0xFu) & ~0xFu) + 1u];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_resultTime_t         T1_SEC_NO_INIT_32_CORE1 T1_resultBuffer1[((T1_NOF_RESULTS_CORE1 + 0xFu) & ~0xFu) + 1u];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_resultTime_t         T1_SEC_NO_INIT_32_CORE2 T1_resultBuffer2[((T1_NOF_RESULTS_CORE2 + 0xFu) & ~0xFu) + 1u];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_resultTime_t * const T1_SEC_CONST_32 T1_resultBufferPC[3] =
{
    T1_resultBuffer0,
    T1_resultBuffer1,
    T1_resultBuffer2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_taskStackElem_t      T1_SEC_NO_INIT_32_CORE0 T1_taskStack0[T1_MAX_TASK_PREEMPTIONS_CORE0+T1_TASK_STACK_OVERRUNS];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_taskStackElem_t      T1_SEC_NO_INIT_32_CORE1 T1_taskStack1[T1_MAX_TASK_PREEMPTIONS_CORE1+T1_TASK_STACK_OVERRUNS];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_taskStackElem_t      T1_SEC_NO_INIT_32_CORE2 T1_taskStack2[T1_MAX_TASK_PREEMPTIONS_CORE2+T1_TASK_STACK_OVERRUNS];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_taskStackElem_t * const T1_SEC_CONST_32 T1_taskStackPC[3] =
{
    T1_taskStack0,
    T1_taskStack1,
    T1_taskStack2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_vStpwMapping_t       T1_SEC_NO_INIT_32_CORE0 T1_vStpw0[2*T1_CONT_NOF_VRTL_STPWS];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_vStpwMapping_t       T1_SEC_NO_INIT_32_CORE1 T1_vStpw1[2*T1_CONT_NOF_VRTL_STPWS];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_vStpwMapping_t       T1_SEC_NO_INIT_32_CORE2 T1_vStpw2[2*T1_CONT_NOF_VRTL_STPWS];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_vStpwMapping_t * const T1_SEC_CONST_32 T1_vStpwPC[3] =
{
    T1_vStpw0,
    T1_vStpw1,
    T1_vStpw2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_focusData_t          T1_SEC_NO_INIT_32_CORE0 T1_focus0[T1_CONT_NOF_FOCUS_MEASUREMENTS];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_focusData_t          T1_SEC_NO_INIT_32_CORE1 T1_focus1[T1_CONT_NOF_FOCUS_MEASUREMENTS];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_focusData_t          T1_SEC_NO_INIT_32_CORE2 T1_focus2[T1_CONT_NOF_FOCUS_MEASUREMENTS];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_focusData_t * const  T1_SEC_CONST_32 T1_focusPC[3] =
{
    T1_focus0,
    T1_focus1,
    T1_focus2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   if defined T1_WAIT_RESUME
#       define T1_START_SEC_NO_INIT_32_CORE0
#       include "T1_MemMap.h"
T1_taskData_t           T1_SEC_NO_INIT_32_CORE0 T1_taskData0[T1_NOF_TASKS_CORE0];
#       define T1_STOP_SEC_NO_INIT_32_CORE0
#       include "T1_MemMap.h"
#       define T1_START_SEC_NO_INIT_32_CORE1
#       include "T1_MemMap.h"
T1_taskData_t           T1_SEC_NO_INIT_32_CORE1 T1_taskData1[T1_NOF_TASKS_CORE1];
#       define T1_STOP_SEC_NO_INIT_32_CORE1
#       include "T1_MemMap.h"
#       define T1_START_SEC_NO_INIT_32_CORE2
#       include "T1_MemMap.h"
T1_taskData_t           T1_SEC_NO_INIT_32_CORE2 T1_taskData2[T1_NOF_TASKS_CORE2];
#       define T1_STOP_SEC_NO_INIT_32_CORE2
#       include "T1_MemMap.h"
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_taskData_t * const   T1_SEC_CONST_32 T1_taskDataPC[3] =
{
    T1_taskData0,
    T1_taskData1,
    T1_taskData2
};
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#   else /* ! defined T1_WAIT_RESUME */
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_taskData_t     * const T1_SEC_CONST_32 T1_taskDataPC[1] = { T1_NULL };
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#   endif /* defined T1_WAIT_RESUME */
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_resultsIdx_t const   T1_SEC_CONST_16 T1_nofResultsPC[3] =
{
    T1_NOF_RESULTS_CORE0,
    T1_NOF_RESULTS_CORE1,
    T1_NOF_RESULTS_CORE2
};
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_tick_t const         T1_SEC_CONST_16 T1_overheadPC[3] =
{
    (T1_tick_t)T1_NS_TO_TICKS( T1_OVERHEAD_CORE0_NS ),
    (T1_tick_t)T1_NS_TO_TICKS( T1_OVERHEAD_CORE1_NS ),
    (T1_tick_t)T1_NS_TO_TICKS( T1_OVERHEAD_CORE2_NS )
};
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_tick_t const         T1_SEC_CONST_16 T1_flexOverheadPC[3] =
{
    (T1_tick_t)T1_NS_TO_TICKS( T1_FLEX_OVERHEAD_CORE0_NS ),
    (T1_tick_t)T1_NS_TO_TICKS( T1_FLEX_OVERHEAD_CORE1_NS ),
    (T1_tick_t)T1_NS_TO_TICKS( T1_FLEX_OVERHEAD_CORE2_NS )
};
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_uint16_t const       T1_SEC_CONST_16 T1_cpuLoadTxPeriodPC[3] =
{
    T1_CPULOAD_TX_PERIOD_CORE0,
    T1_CPULOAD_TX_PERIOD_CORE1,
    T1_CPULOAD_TX_PERIOD_CORE2
};
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_uint16_t const       T1_SEC_CONST_16 T1_startOfFrameEventPC[3] =
{
    T1_COMBINE_EVENT_INFO( T1_BSF_EVENT_ID_CORE0, T1_BSF_EVENT_INFO_CORE0 ),
    T1_COMBINE_EVENT_INFO( T1_BSF_EVENT_ID_CORE1, T1_BSF_EVENT_INFO_CORE1 ),
    T1_COMBINE_EVENT_INFO( T1_BSF_EVENT_ID_CORE2, T1_BSF_EVENT_INFO_CORE2 )
};
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_16
#   include "T1_MemMap.h"
T1_anaCapa_t const      T1_SEC_CONST_16 T1_defaultAnalysisCapacityPC[3] =
{
    T1_CONT_ANALYSIS_CAPACITY_CORE0,
    T1_CONT_ANALYSIS_CAPACITY_CORE1,
    T1_CONT_ANALYSIS_CAPACITY_CORE2
};
#   define T1_STOP_SEC_CONST_16
#   include "T1_MemMap.h"
#   if !defined T1_70618
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_longTime_t const     T1_SEC_CONST_32 T1_38948[3] =
{
    0xFFFFFFFFuL,
    0xFFFFFFFFuL,
    0xFFFFFFFFuL
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   endif /* !defined T1_70618 */
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_avgCPULoadSamplesPC[3] =
{
    T1_CPULOAD_SAMPLES_CORE0,
    T1_CPULOAD_SAMPLES_CORE1,
    T1_CPULOAD_SAMPLES_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_taskIdx_t const      T1_SEC_CONST_8 T1_nofTasksPC[3] =
{
    T1_NOF_TASKS_CORE0,
    T1_NOF_TASKS_CORE1,
    T1_NOF_TASKS_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_stpwIdx_t const      T1_SEC_CONST_8 T1_nofStpwsPC[3] =
{
    T1_NOF_USER_STPWS_CORE0 + T1_NOF_FLEX_STPWS_CORE0 + T1_CONT_NOF_VRTL_STPWS,
    T1_NOF_USER_STPWS_CORE1 + T1_NOF_FLEX_STPWS_CORE1 + T1_CONT_NOF_VRTL_STPWS,
    T1_NOF_USER_STPWS_CORE2 + T1_NOF_FLEX_STPWS_CORE2 + T1_CONT_NOF_VRTL_STPWS
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_stpwIdx_t const      T1_SEC_CONST_8 T1_nofUserStpwsPC[3] =
{
    1u,
    1u,
    1u
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_csrnIdx_t const      T1_SEC_CONST_8 T1_nofCsrnsPC[3] =
{
    2u,
    2u,
    2u
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_nofPreemptionsPC[3] =
{
    T1_MAX_TASK_PREEMPTIONS_CORE0,
    T1_MAX_TASK_PREEMPTIONS_CORE1,
    T1_MAX_TASK_PREEMPTIONS_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_cpuLoadThresholdPC[3] =
{
    243u,
    243u,
    243u
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_taskIdx_t const      T1_SEC_CONST_8 T1_bgTaskIdxPC[3] =
{
    T1_BACKGROUND_TASK_IDX_CORE0,
    T1_BACKGROUND_TASK_IDX_CORE1,
    T1_BACKGROUND_TASK_IDX_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   if defined T1_CONT_DEFAULT_CONFIG_STOPWATCH
#       define T1_START_SEC_CONST_8
#       include "T1_MemMap.h"
T1_stpwConfig_t         T1_SEC_CONST_8 T1_stpwConfig0[1] =
{
    T1_CONT_DEFAULT_CONFIG_STOPWATCH( 0u )
};
T1_stpwConfig_t         T1_SEC_CONST_8 T1_stpwConfig1[1] =
{
    T1_CONT_DEFAULT_CONFIG_STOPWATCH( 0u )
};
T1_stpwConfig_t         T1_SEC_CONST_8 T1_stpwConfig2[1] =
{
    T1_CONT_DEFAULT_CONFIG_STOPWATCH( 0u )
};
#       define T1_STOP_SEC_CONST_8
#       include "T1_MemMap.h"
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_stpwConfig_t * const T1_SEC_CONST_32 T1_stpwConfigPC[3] =
{
    T1_stpwConfig0,
    T1_stpwConfig1,
    T1_stpwConfig2
};
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#   endif /* defined T1_CONT_DEFAULT_CONFIG_STOPWATCH */
#   if defined T1_CONT_DEFAULT_CONFIG_CONSTRAINT
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_csrnData_t const     T1_SEC_CONST_32 T1_csrnConfig0[2] =
{
    T1_CONT_DEFAULT_CONFIG_CONSTRAINT,
    T1_CONT_DEFAULT_CONFIG_CONSTRAINT
};
T1_csrnData_t const     T1_SEC_CONST_32 T1_csrnConfig1[2] =
{
    T1_CONT_DEFAULT_CONFIG_CONSTRAINT,
    T1_CONT_DEFAULT_CONFIG_CONSTRAINT
};
T1_csrnData_t const     T1_SEC_CONST_32 T1_csrnConfig2[2] =
{
    T1_CONT_DEFAULT_CONFIG_CONSTRAINT,
    T1_CONT_DEFAULT_CONFIG_CONSTRAINT
};
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_csrnData_t const * const T1_SEC_CONST_32 T1_csrnConfigPC[3] =
{
    T1_csrnConfig0,
    T1_csrnConfig1,
    T1_csrnConfig2
};
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#   endif /* defined T1_CONT_DEFAULT_CONFIG_CONSTRAINT */

#endif /* defined T1_ENABLE && !defined T1_DISABLE_T1_CONT */

#if defined T1_ENABLE && !defined T1_DISABLE_T1_DELAY
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_nofDelaysPC[3] =
{
    T1_NOF_DELAYS_CORE0,
    T1_NOF_DELAYS_CORE1,
    T1_NOF_DELAYS_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_delay_t              T1_SEC_NO_INIT_32_CORE0 T1_delays0[T1_NOF_DELAYS_CORE0];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_delay_t              T1_SEC_NO_INIT_32_CORE1 T1_delays1[T1_NOF_DELAYS_CORE1];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_delay_t              T1_SEC_NO_INIT_32_CORE2 T1_delays2[T1_NOF_DELAYS_CORE2];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_delay_t * const      T1_SEC_CONST_32 T1_delaysPC[3] =
{
    T1_delays0,
    T1_delays1,
    T1_delays2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_delayGlobals_t       T1_SEC_NO_INIT_32_CORE0 T1_delayGlobals0;
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_delayGlobals_t       T1_SEC_NO_INIT_32_CORE1 T1_delayGlobals1;
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_delayGlobals_t       T1_SEC_NO_INIT_32_CORE2 T1_delayGlobals2;
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_delayGlobals_t * const T1_SEC_CONST_32 T1_delayGlobalsPC[3] =
{
    &T1_delayGlobals0,
    &T1_delayGlobals1,
    &T1_delayGlobals2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"

#endif /* defined T1_ENABLE && !defined T1_DISABLE_T1_DELAY */

#if defined T1_ENABLE && !defined T1_DISABLE_T1_FLEX

#   define T1_START_SEC_NO_INIT_32
#   include "T1_MemMap.h"
T1_uint32_t             T1_SEC_NO_INIT_32 T1_swdStart;
#   define T1_STOP_SEC_NO_INIT_32
#   include "T1_MemMap.h"

#   if defined T1_TRICORE
#       define T1_START_SEC_NO_INIT_32_DCX_CORE0
#       include "T1_MemMap.h"
T1_flexAddr_t           T1_SEC_NO_INIT_32_DCX_CORE0 T1_dcx0[4];
#       define T1_STOP_SEC_NO_INIT_32_DCX_CORE0
#       include "T1_MemMap.h"
#       define T1_START_SEC_NO_INIT_32_DCX_CORE1
#       include "T1_MemMap.h"
T1_flexAddr_t           T1_SEC_NO_INIT_32_DCX_CORE1 T1_dcx1[4];
#       define T1_STOP_SEC_NO_INIT_32_DCX_CORE1
#       include "T1_MemMap.h"
#       define T1_START_SEC_NO_INIT_32_DCX_CORE2
#       include "T1_MemMap.h"
T1_flexAddr_t           T1_SEC_NO_INIT_32_DCX_CORE2 T1_dcx2[4];
#       define T1_STOP_SEC_NO_INIT_32_DCX_CORE2
#       include "T1_MemMap.h"
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_flexAddr_t * const   T1_SEC_CONST_32 T1_dcxPC[3] =
{
    T1_dcx0,
    T1_dcx1,
    T1_dcx2
};
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#       define T1_START_SEC_CONST_32
#       include "T1_MemMap.h"
T1_pVoidVoid_t const    T1_SEC_CONST_32 T1_OuterExceptionHandlerPC[3] =
{
    T1_OuterExceptionHandlerCore0,
    T1_OuterExceptionHandlerCore1,
    T1_OuterExceptionHandlerCore2
};
#       define T1_STOP_SEC_CONST_32
#       include "T1_MemMap.h"
#   endif /* defined T1_TRICORE */
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_nofAddrsPC[3] =
{
    T1_NOF_FLEX_ADDRS_CORE0,
    T1_NOF_FLEX_ADDRS_CORE1,
    T1_NOF_FLEX_ADDRS_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_flexAddr_t           T1_SEC_NO_INIT_32_CORE0 T1_addrs0[T1_NOF_FLEX_ADDRS_CORE0];
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_flexAddr_t           T1_SEC_NO_INIT_32_CORE1 T1_addrs1[T1_NOF_FLEX_ADDRS_CORE1];
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_flexAddr_t           T1_SEC_NO_INIT_32_CORE2 T1_addrs2[T1_NOF_FLEX_ADDRS_CORE2];
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_flexAddr_t * const   T1_SEC_CONST_32 T1_addrsPC[3] =
{
    T1_addrs0,
    T1_addrs1,
    T1_addrs2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_flexGlobals_t        T1_SEC_NO_INIT_32_CORE0 T1_flexGlobals0;
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_flexGlobals_t        T1_SEC_NO_INIT_32_CORE1 T1_flexGlobals1;
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_flexGlobals_t        T1_SEC_NO_INIT_32_CORE2 T1_flexGlobals2;
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_flexGlobals_t * const T1_SEC_CONST_32 T1_flexGlobalsPC[3] =
{
    &T1_flexGlobals0,
    &T1_flexGlobals1,
    &T1_flexGlobals2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"

#endif /* defined T1_ENABLE && !defined T1_DISABLE_T1_FLEX */

#if defined T1_ENABLE && !defined T1_DISABLE_T1_SCOPE

#   if !defined T1_SYNC_TIMER_WIDTH_BITS
#       error T1_SYNC_TIMER_WIDTH_BITS must be defined
#   endif /* !defined T1_SYNC_TIMER_WIDTH_BITS */
#   if !defined T1_TRACEBUFFER_ENTRIES_CORE0
#       if defined T1_EXTERNAL_TRACEBUFFER
#           define T1_TRACEBUFFER_ENTRIES_CORE0
#       else /* !defined T1_EXTERNAL_TRACEBUFFER */
#           error T1_TRACEBUFFER_ENTRIES_CORE0 not defined
#       endif /* defined T1_EXTERNAL_TRACEBUFFER */
#   endif /* T1_TRACEBUFFER_ENTRIES_CORE0 */
#   if !defined T1_TRACE_TIMER_COUNTS_DOWN_CORE0
#       error T1_TRACE_TIMER_COUNTS_DOWN_CORE0 not defined
#   endif /* T1_TRACE_TIMER_COUNTS_DOWN_CORE0 */
#   if !defined T1_TRACEBUFFER_ENTRIES_CORE1
#       if defined T1_EXTERNAL_TRACEBUFFER
#           define T1_TRACEBUFFER_ENTRIES_CORE1
#       else /* !defined T1_EXTERNAL_TRACEBUFFER */
#           error T1_TRACEBUFFER_ENTRIES_CORE1 not defined
#       endif /* defined T1_EXTERNAL_TRACEBUFFER */
#   endif /* T1_TRACEBUFFER_ENTRIES_CORE1 */
#   if !defined T1_TRACE_TIMER_COUNTS_DOWN_CORE1
#       error T1_TRACE_TIMER_COUNTS_DOWN_CORE1 not defined
#   endif /* T1_TRACE_TIMER_COUNTS_DOWN_CORE1 */
#   if !defined T1_TRACEBUFFER_ENTRIES_CORE2
#       if defined T1_EXTERNAL_TRACEBUFFER
#           define T1_TRACEBUFFER_ENTRIES_CORE2
#       else /* !defined T1_EXTERNAL_TRACEBUFFER */
#           error T1_TRACEBUFFER_ENTRIES_CORE2 not defined
#       endif /* defined T1_EXTERNAL_TRACEBUFFER */
#   endif /* T1_TRACEBUFFER_ENTRIES_CORE2 */
#   if !defined T1_TRACE_TIMER_COUNTS_DOWN_CORE2
#       error T1_TRACE_TIMER_COUNTS_DOWN_CORE2 not defined
#   endif /* T1_TRACE_TIMER_COUNTS_DOWN_CORE2 */
#   define T1_START_SEC_NO_INIT_32_TRACEBUFFER_CORE0
#   include "T1_MemMap.h"
#   if defined T1_EXTERNAL_TRACEBUFFER
T1_EXTERN
#   endif /* !defined T1_EXTERNAL_TRACEBUFFER */
T1_traceEntry_t T1_FAR  T1_SEC_NO_INIT_32_TRACEBUFFER_CORE0 T1_traceBuffer0[T1_TRACEBUFFER_ENTRIES_CORE0];
#   define T1_STOP_SEC_NO_INIT_32_TRACEBUFFER_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_TRACEBUFFER_CORE1
#   include "T1_MemMap.h"
#   if defined T1_EXTERNAL_TRACEBUFFER
T1_EXTERN
#   endif /* !defined T1_EXTERNAL_TRACEBUFFER */
T1_traceEntry_t T1_FAR  T1_SEC_NO_INIT_32_TRACEBUFFER_CORE1 T1_traceBuffer1[T1_TRACEBUFFER_ENTRIES_CORE1];
#   define T1_STOP_SEC_NO_INIT_32_TRACEBUFFER_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_TRACEBUFFER_CORE2
#   include "T1_MemMap.h"
#   if defined T1_EXTERNAL_TRACEBUFFER
T1_EXTERN
#   endif /* !defined T1_EXTERNAL_TRACEBUFFER */
T1_traceEntry_t T1_FAR  T1_SEC_NO_INIT_32_TRACEBUFFER_CORE2 T1_traceBuffer2[T1_TRACEBUFFER_ENTRIES_CORE2];
#   define T1_STOP_SEC_NO_INIT_32_TRACEBUFFER_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_traceEntry_t T1_FAR * const T1_SEC_CONST_32 T1_traceBufferPC[3] =
{
    T1_traceBuffer0,
    T1_traceBuffer1,
    T1_traceBuffer2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_traceIndirect_t const T1_SEC_CONST_32 T1_traceIndirect =
{
#if defined T1_CONT_REMOTE
    T1_TraceEventNoSuspTimeRC__,
    T1_TraceSyncNoSuspRC__
#else /* !defined T1_CONT_REMOTE */
    T1_TraceEventNoSuspTime__,
    T1_TraceSyncNoSusp__
#endif /* defined T1_CONT_REMOTE */
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   if !defined T1_EXTERNAL_TRACEBUFFER
#       define T1_START_SEC_CONST_16
#       include "T1_MemMap.h"
T1_uint16_t const       T1_SEC_CONST_16 T1_bufferSizePC[3] =
{
    T1_TRACEBUFFER_ENTRIES_CORE0,
    T1_TRACEBUFFER_ENTRIES_CORE1,
    T1_TRACEBUFFER_ENTRIES_CORE2
};
#       define T1_STOP_SEC_CONST_16
#       include "T1_MemMap.h"
#   endif /* !defined T1_EXTERNAL_TRACEBUFFER */
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_bool_t const         T1_SEC_CONST_8 T1_syncTimerIsTraceTimerPC[3] =
{
    T1_TRACE_TIMER_IS_SYNC_TIMER_CORE0,
    T1_TRACE_TIMER_IS_SYNC_TIMER_CORE1,
    T1_TRACE_TIMER_IS_SYNC_TIMER_CORE2
};
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"
#   if defined T1_DISABLE_T1_CONT
#   define T1_START_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
T1_scopeGlobals_t       T1_SEC_NO_INIT_32_CORE0 T1_scopeGlobals0;
#   define T1_STOP_SEC_NO_INIT_32_CORE0
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
T1_scopeGlobals_t       T1_SEC_NO_INIT_32_CORE1 T1_scopeGlobals1;
#   define T1_STOP_SEC_NO_INIT_32_CORE1
#   include "T1_MemMap.h"
#   define T1_START_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
T1_scopeGlobals_t       T1_SEC_NO_INIT_32_CORE2 T1_scopeGlobals2;
#   define T1_STOP_SEC_NO_INIT_32_CORE2
#   include "T1_MemMap.h"
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_scopeGlobals_t * const T1_SEC_CONST_32 T1_scopeGlobalsPC[3] =
{
    &T1_scopeGlobals0,
    &T1_scopeGlobals1,
    &T1_scopeGlobals2
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   else /* ! defined T1_DISABLE_T1_CONT */
#   define T1_START_SEC_CONST_32
#   include "T1_MemMap.h"
T1_scopeGlobals_t * const T1_SEC_CONST_32 T1_scopeGlobalsPC[3] =
{
    &(T1_contGlobals0.scopeGlobals),
    &(T1_contGlobals1.scopeGlobals),
    &(T1_contGlobals2.scopeGlobals)
};
#   define T1_STOP_SEC_CONST_32
#   include "T1_MemMap.h"
#   endif /* defined T1_DISABLE_T1_CONT */
#   if defined T1_CROSS_CORE_ACT
#       define T1_START_SEC_NO_INIT_32
#       include "T1_MemMap.h"
T1_uint32_t T1_SEC_NO_INIT_32 T1_taskAct[T1_MAX_NOF_TASKS];
#       define T1_STOP_SEC_NO_INIT_32
#       include "T1_MemMap.h"
#   endif /* defined T1_CROSS_CORE_ACT */
#   define T1_START_SEC_CONST_8
#   include "T1_MemMap.h"
T1_uint8_t const        T1_SEC_CONST_8 T1_syncTimerWidthBits = T1_SYNC_TIMER_WIDTH_BITS;
#   define T1_STOP_SEC_CONST_8
#   include "T1_MemMap.h"

#endif /* defined T1_ENABLE && !defined T1_DISABLE_T1_SCOPE */
