/*************************************************************************************
 *  FILE:           T1_config.h
 *
 *  DESCRIPTION:    this header was generated by perl script T1_projGen.pl
 *
 *  AUTHOR:         GLIWA GmbH
 *
 *  COPYRIGHT:      GLIWA GmbH | know-how in embedded software
 *                  Weilheim i.OB.
 *                  All rights reserved
 ************************************************************************************/

#ifndef T1_CONFIG_H_
#define T1_CONFIG_H_ (1)

/*----------------------------------------------------------------------------------*/
/*--- header includes --------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/



/*----------------------------------------------------------------------------------*/
/*--- Task and ISR IDs -------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#define T1_IdleTask_OsCore0_ID                        (  0u)
#define T1_IdleTask_OsCore1_ID                        (  1u)
#define T1_IdleTask_OsCore2_ID                        (  2u)
#define T1_Task1000ms_Core0_ID                        (  3u)
#define T1_Task1000ms_Core1_ID                        (  4u)
#define T1_Task1000ms_Core2_ID                        (  5u)
#define T1_Task100ms_Core0_ID                         (  6u)
#define T1_Task100ms_Core1_ID                         (  7u)
#define T1_Task100ms_Core2_ID                         (  8u)
#define T1_Task10ms_Core0_ID                          (  9u)
#define T1_Task10ms_Core1_ID                          ( 10u)
#define T1_Task10ms_Core2_ID                          ( 11u)
#define T1_Task1ms_Core0_ID                           ( 12u)
#define T1_Task1ms_Core1_ID                           ( 13u)
#define T1_Task1ms_Core2_ID                           ( 14u)
#define T1_Task200ms_Core0_ID                         ( 15u)
#define T1_Task200ms_Core1_ID                         ( 16u)
#define T1_Task200ms_Core2_ID                         ( 17u)
#define T1_Task20ms_Core0_ID                          ( 18u)
#define T1_Task20ms_Core1_ID                          ( 19u)
#define T1_Task20ms_Core2_ID                          ( 20u)
#define T1_Task500ms_Core0_ID                         ( 21u)
#define T1_Task500ms_Core1_ID                         ( 22u)
#define T1_Task500ms_Core2_ID                         ( 23u)
#define T1_Task50ms_Core0_ID                          ( 24u)
#define T1_Task50ms_Core1_ID                          ( 25u)
#define T1_Task50ms_Core2_ID                          ( 26u)
#define T1_Task5ms_Core0_ID                           ( 27u)
#define T1_Task5ms_Core1_ID                           ( 28u)
#define T1_Task5ms_Core2_ID                           ( 29u)
#define T1_TaskInit_Core0_ID                          ( 30u)
#define T1_TaskInit_Core1_ID                          ( 31u)
#define T1_TaskInit_Core2_ID                          ( 32u)
#define T1_TaskSchM_Core0_ID                          ( 33u)
#define T1_TaskSchM_Core1_ID                          ( 34u)
#define T1_TaskSchM_Core2_ID                          ( 35u)
#define T1_Adc0Sr0_Isr_ID                             ( 36u)
#define T1_Adc1Sr0_Isr_ID                             ( 37u)
#define T1_Adc2Sr0_Isr_ID                             ( 38u)
#define T1_Adc3Sr0_Isr_ID                             ( 39u)
#define T1_Adc4Sr0_Isr_ID                             ( 40u)
#define T1_Adc5Sr0_Isr_ID                             ( 41u)
#define T1_Adc6Sr0_Isr_ID                             ( 42u)
#define T1_CanIsr_0_ID                                ( 43u)
#define T1_CounterIsr_SystemTimer_Core0_ID            ( 44u)
#define T1_CounterIsr_SystemTimer_Core1_ID            ( 45u)
#define T1_CounterIsr_SystemTimer_Core2_ID            ( 46u)
#define T1_Isr_TIM02_ID                               ( 47u)
#define T1_Isr_TIM03_ID                               ( 48u)
#define T1_XSignalIsr_OsCore0_ID                      ( 49u)
#define T1_XSignalIsr_OsCore1_ID                      ( 50u)
#define T1_XSignalIsr_OsCore2_ID                      ( 51u)
/* Core 0: */
#define T1_NOF_TASKS_CORE0                            ( 50u)
#define T1_MAX_TASK_PREEMPTIONS_CORE0                 ( 20u)
#define T1_CAT1_ISR_ID_OFFSET_CORE0                   ( 50u)
#define T1_CAT2_ISR_ID_OFFSET_CORE0                   ( 43u)
#define T1_EXT_ISR_ID_OFFSET_CORE0                    ( 50u)
#define T1_CAT1_TO_TRACE_ID_CORE0( id_ )              (T1_CAT1_ISR_ID_OFFSET_CORE0 + (id_))
#define T1_CAT2_TO_TRACE_ID_CORE0( id_ )              (T1_CAT2_ISR_ID_OFFSET_CORE0 + (id_))
#define T1_EXT_ISR_TO_TRACE_ID_CORE0( id_ )           (T1_EXT_ISR_ID_OFFSET_CORE0 + (id_))
#define T1_NS_TO_TICKS_CORE0( ns_ )                   ((T1_tickUint_t)(((ns_) * 1.0f) / T1_TICK_DURATION_CORE0_NS))
#define T1_US_TO_TICKS_CORE0( us_ )                   ((T1_tickUint_t)(((us_) * 1000.0f) / T1_TICK_DURATION_CORE0_NS))
#define T1_MS_TO_TICKS_CORE0( ms_ )                   ((T1_tickUint_t)(((ms_) * 1000000.0f) / T1_TICK_DURATION_CORE0_NS))
/* Core 1: */
#define T1_NOF_TASKS_CORE1                            ( 51u)
#define T1_MAX_TASK_PREEMPTIONS_CORE1                 ( 20u)
#define T1_CAT1_ISR_ID_OFFSET_CORE1                   ( 51u)
#define T1_CAT2_ISR_ID_OFFSET_CORE1                   ( 36u)
#define T1_EXT_ISR_ID_OFFSET_CORE1                    ( 51u)
#define T1_CAT1_TO_TRACE_ID_CORE1( id_ )              (T1_CAT1_ISR_ID_OFFSET_CORE1 + (id_))
#define T1_CAT2_TO_TRACE_ID_CORE1( id_ )              (T1_CAT2_ISR_ID_OFFSET_CORE1 + (id_))
#define T1_EXT_ISR_TO_TRACE_ID_CORE1( id_ )           (T1_EXT_ISR_ID_OFFSET_CORE1 + (id_))
#define T1_NS_TO_TICKS_CORE1( ns_ )                   ((T1_tickUint_t)(((ns_) * 1.0f) / T1_TICK_DURATION_CORE1_NS))
#define T1_US_TO_TICKS_CORE1( us_ )                   ((T1_tickUint_t)(((us_) * 1000.0f) / T1_TICK_DURATION_CORE1_NS))
#define T1_MS_TO_TICKS_CORE1( ms_ )                   ((T1_tickUint_t)(((ms_) * 1000000.0f) / T1_TICK_DURATION_CORE1_NS))
/* Core 2: */
#define T1_NOF_TASKS_CORE2                            ( 52u)
#define T1_MAX_TASK_PREEMPTIONS_CORE2                 ( 20u)
#define T1_CAT1_ISR_ID_OFFSET_CORE2                   ( 52u)
#define T1_CAT2_ISR_ID_OFFSET_CORE2                   ( 46u)
#define T1_EXT_ISR_ID_OFFSET_CORE2                    ( 52u)
#define T1_CAT1_TO_TRACE_ID_CORE2( id_ )              (T1_CAT1_ISR_ID_OFFSET_CORE2 + (id_))
#define T1_CAT2_TO_TRACE_ID_CORE2( id_ )              (T1_CAT2_ISR_ID_OFFSET_CORE2 + (id_))
#define T1_EXT_ISR_TO_TRACE_ID_CORE2( id_ )           (T1_EXT_ISR_ID_OFFSET_CORE2 + (id_))
#define T1_NS_TO_TICKS_CORE2( ns_ )                   ((T1_tickUint_t)(((ns_) * 1.0f) / T1_TICK_DURATION_CORE2_NS))
#define T1_US_TO_TICKS_CORE2( us_ )                   ((T1_tickUint_t)(((us_) * 1000.0f) / T1_TICK_DURATION_CORE2_NS))
#define T1_MS_TO_TICKS_CORE2( ms_ )                   ((T1_tickUint_t)(((ms_) * 1000000.0f) / T1_TICK_DURATION_CORE2_NS))


/*----------------------------------------------------------------------------------*/
/*--- Config macros ----------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#define T1_NOF_CORES                                  (3u)
#define T1_SID                                        (2u)
#define T1_BUILD_ID                                   2024566120
#define T1_CAN_PC_TO_ECU_ID                           (0x7CBu)
#define T1_CAN_ECU_TO_PC_ID                           (0x7FAu)
#define T1_GCP_MAX_RX_FRAME_SIZE                      (8u)
#define T1_GCP_MAX_TX_FRAME_SIZE                      (8u)
#define T1_STATIC_RUNNABLE_ID                         (1023u)
#define T1_TIMEOUT_RX                                 (100u)
#define T1_TIMEOUT_TX                                 (100u)
#define T1_TIMEOUT_RESPONSE                           (1000u)
#define T1_INIT_FEATURE_MASK                          (0uL)
#define T1_GET_SYNC_TIME( )                           (*(T1_uint32_t volatile *)0xF0000114uL)
#define T1_SYNC_TIMER_WIDTH_BITS                      (32u)
#define T1_SYNC_TIMER_DURATION_NS                     ((1000.0f/100*16))
#define T1_CONT_NOF_FOCUS_MEASUREMENTS                (2u)
#define T1_MAX_NOF_TASKS                              (52u)
#define T1_GET_TRACE_TIME( )                          (*(T1_tickUint_t volatile *)T1_PTIMER_CORE0)

/* Core-specific configuration for core 0 */
#define T1_BSF_EVENT_ID_CORE0                         (T1_ACTIVATION)
#define T1_BSF_EVENT_INFO_CORE0                       (T1_Task100ms_Core0_ID)
#define T1_BACKGROUND_TASK_ID_CORE0                   (T1_INVALID_TASK_ID)
#define T1_TICK_DURATION_CORE0_NS                     ((1000.0f/100*16))
#define T1_OVERHEAD_CORE0_NS                          (178)
#define T1_FLEX_OVERHEAD_CORE0_NS                     (500)
#define T1_CPULOAD_CALLBACK_CORE0                     (T1_CPULoadCallbackCore0)
#define T1_CPULOAD_THRESHOLD_PERCENT_CORE0            (95)
#define T1_TRACEBUFFER_ENTRIES_CORE0                  (1000u)
#define T1_NOF_CSRNS_CORE0                            (2u)
#define T1_NOF_FLEX_STPWS_CORE0                       (16u)
#define T1_NOF_STPWS_CORE0                            (T1_NOF_USER_STPWS_CORE0 + T1_NOF_FLEX_STPWS_CORE0)
#define T1_NOF_FLEX_ADDRS_CORE0                       (16u)
#define T1_PTIMER_CORE0                               (0xF0000114uL)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE0            (1)
#define T1_TRACE_TIMER_COUNTS_DOWN_CORE0              (T1_FALSE)
#define T1_TRACE_TIMER_BIT_LENGTH_CORE0               (32u)
#define T1_CPULOAD_TX_PERIOD_CORE0                    (100u)
#define T1_CPULOAD_SAMPLES_CORE0                      (100u)
#define T1_CONT_ANALYSIS_CAPACITY_CORE0               (1000u)
#define T1_CET_EVT_CHAIN_TO_IDX_CORE0( id_ )          ( T1_NOF_STPWS_CORE0 + ( ( 3u < (id_) ) ? T1_invalidCETeventChainIdx : ( 2u*(id_) ) ) )
#define T1_GET_EVT_CHAIN_TO_IDX_CORE0( id_ )          ( T1_NOF_STPWS_CORE0 + ( ( 3u < (id_) ) ? ( (id_) + 4u ) : ( 2u*(id_) + 1u ) ) )

/* Core-specific configuration for core 1 */
#define T1_BSF_EVENT_ID_CORE1                         (T1_ACTIVATION)
#define T1_BSF_EVENT_INFO_CORE1                       (T1_Task100ms_Core1_ID)
#define T1_BACKGROUND_TASK_ID_CORE1                   (T1_INVALID_TASK_ID)
#define T1_TICK_DURATION_CORE1_NS                     ((1000.0f/100*16))
#define T1_OVERHEAD_CORE1_NS                          (178)
#define T1_FLEX_OVERHEAD_CORE1_NS                     (500)
#define T1_CPULOAD_CALLBACK_CORE1                     (T1_CPULoadCallbackCore1)
#define T1_CPULOAD_THRESHOLD_PERCENT_CORE1            (95)
#define T1_TRACEBUFFER_ENTRIES_CORE1                  (1000u)
#define T1_NOF_CSRNS_CORE1                            (2u)
#define T1_NOF_USER_STPWS_CORE1                       (1u)
#define T1_NOF_FLEX_STPWS_CORE1                       (16u)
#define T1_NOF_STPWS_CORE1                            (T1_NOF_USER_STPWS_CORE1 + T1_NOF_FLEX_STPWS_CORE1)
#define T1_NOF_FLEX_ADDRS_CORE1                       (16u)
#define T1_PTIMER_CORE1                               (0xF0000114uL)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE1            (1)
#define T1_TRACE_TIMER_COUNTS_DOWN_CORE1              (T1_FALSE)
#define T1_TRACE_TIMER_BIT_LENGTH_CORE1               (32u)
#define T1_CPULOAD_TX_PERIOD_CORE1                    (100u)
#define T1_CPULOAD_SAMPLES_CORE1                      (100u)
#define T1_CONT_ANALYSIS_CAPACITY_CORE1               (1000u)
#define T1_CET_EVT_CHAIN_TO_IDX_CORE1( id_ )          ( T1_NOF_STPWS_CORE1 + ( ( 3u < (id_) ) ? T1_invalidCETeventChainIdx : ( 2u*(id_) ) ) )
#define T1_GET_EVT_CHAIN_TO_IDX_CORE1( id_ )          ( T1_NOF_STPWS_CORE1 + ( ( 3u < (id_) ) ? ( (id_) + 4u ) : ( 2u*(id_) + 1u ) ) )

/* Core-specific configuration for core 2 */
#define T1_BSF_EVENT_ID_CORE2                         (T1_ACTIVATION)
#define T1_BSF_EVENT_INFO_CORE2                       (T1_Task100ms_Core2_ID)
#define T1_BACKGROUND_TASK_ID_CORE2                   (T1_INVALID_TASK_ID)
#define T1_TICK_DURATION_CORE2_NS                     ((1000.0f/100*16))
#define T1_OVERHEAD_CORE2_NS                          (178)
#define T1_FLEX_OVERHEAD_CORE2_NS                     (500)
#define T1_CPULOAD_CALLBACK_CORE2                     (T1_CPULoadCallbackCore2)
#define T1_CPULOAD_THRESHOLD_PERCENT_CORE2            (95)
#define T1_TRACEBUFFER_ENTRIES_CORE2                  (1000u)
#define T1_NOF_CSRNS_CORE2                            (2u)
#define T1_NOF_USER_STPWS_CORE2                       (1u)
#define T1_NOF_FLEX_STPWS_CORE2                       (16u)
#define T1_NOF_STPWS_CORE2                            (T1_NOF_USER_STPWS_CORE2 + T1_NOF_FLEX_STPWS_CORE2)
#define T1_NOF_FLEX_ADDRS_CORE2                       (16u)
#define T1_PTIMER_CORE2                               (0xF0000114uL)
#define T1_TRACE_TIMER_IS_SYNC_TIMER_CORE2            (1)
#define T1_TRACE_TIMER_COUNTS_DOWN_CORE2              (T1_FALSE)
#define T1_TRACE_TIMER_BIT_LENGTH_CORE2               (32u)
#define T1_CPULOAD_TX_PERIOD_CORE2                    (100u)
#define T1_CPULOAD_SAMPLES_CORE2                      (100u)
#define T1_CONT_ANALYSIS_CAPACITY_CORE2               (1000u)
#define T1_CET_EVT_CHAIN_TO_IDX_CORE2( id_ )          ( T1_NOF_STPWS_CORE2 + ( ( 3u < (id_) ) ? T1_invalidCETeventChainIdx : ( 2u*(id_) ) ) )
#define T1_GET_EVT_CHAIN_TO_IDX_CORE2( id_ )          ( T1_NOF_STPWS_CORE2 + ( ( 3u < (id_) ) ? ( (id_) + 4u ) : ( 2u*(id_) + 1u ) ) )


#if ! defined T1_CORE_ID_TO_SCOPE_GLOBALS
#   if defined T1_DISABLE_T1_CONT
#       if ! defined T1_NOF_CORES || defined T1_CLONE
#           define T1_CORE_ID_TO_SCOPE_GLOBALS( coreId_ ) (&T1_scopeGlobals)
#       else /* defined T1_NOF_CORES && ! defined T1_CLONE */
/* This default version can be evaluated at compile time when passed a literal input */
#           if 2 < T1_NOF_CORES && defined __GNUC__ /* use switch statement */
#               define T1_CORE_ID_TO_SCOPE_GLOBALS( coreId_ ) ({            \
    T1_scopeGlobals_t * pScopeGlobals_;                                     \
    switch( coreId_ )                                                       \
    {                                                                       \
    case 0:     pScopeGlobals_ = &T1_scopeGlobals0;  break;                 \
    case 1:     pScopeGlobals_ = &T1_scopeGlobals1;  break;                 \
    default:    pScopeGlobals_ = &T1_scopeGlobals2;  break;                 \
    }                                                                       \
    pScopeGlobals_;                                                         \
})
#           else /* NOTE 'coreId_' can be evaluated more than once with >2 cores */
#               define T1_CORE_ID_TO_SCOPE_GLOBALS( coreId_ ) (             \
    ( 0 == (coreId_) ) ? &T1_scopeGlobals0  :                               \
    ( 1 == (coreId_) ) ? &T1_scopeGlobals1  :                               \
                         &T1_scopeGlobals2                                  \
)
#           endif /* switch or ?: */
#       endif /* ! defined T1_NOF_CORES || defined T1_CLONE */
#   else /* ! defined T1_DISABLE_T1_CONT */
#       if ! defined T1_NOF_CORES || defined T1_CLONE
#           define T1_CORE_ID_TO_SCOPE_GLOBALS( coreId_ ) (&(T1_contScopeGlobals.scopeGlobals))
#       else /* defined T1_NOF_CORES && ! defined T1_CLONE */
/* This default version can be evaluated at compile time when passed a literal input */
#           if 2 < T1_NOF_CORES && defined __GNUC__ /* use switch statement */
#               define T1_CORE_ID_TO_SCOPE_GLOBALS( coreId_ ) ({            \
    T1_scopeGlobals_t * pScopeGlobals_;                                     \
    switch( coreId_ )                                                       \
    {                                                                       \
    case 0:     pScopeGlobals_ = &(T1_contGlobals0 .scopeGlobals); break;   \
    case 1:     pScopeGlobals_ = &(T1_contGlobals1 .scopeGlobals); break;   \
    default:    pScopeGlobals_ = &(T1_contGlobals2 .scopeGlobals); break;   \
    }                                                                       \
    pScopeGlobals_;                                                         \
})
#           else /* NOTE 'coreId_' can be evaluated more than once with >2 cores */
#               define T1_CORE_ID_TO_SCOPE_GLOBALS( coreId_ ) (             \
    ( 0 == (coreId_) ) ? &(T1_contGlobals0 .scopeGlobals) :                 \
    ( 1 == (coreId_) ) ? &(T1_contGlobals1 .scopeGlobals) :                 \
                         &(T1_contGlobals2 .scopeGlobals)                   \
)
#           endif /* switch or ?: */
#       endif /* ! defined T1_NOF_CORES || defined T1_CLONE */
#   endif /* defined T1_DISABLE_T1_CONT */
#endif /* ! defined T1_CORE_ID_TO_SCOPE_GLOBALS */

#if ! defined T1_CONT_RC_UNMAP
#   define T1_CONT_RC_UNMAP( coreId_ )                (coreId_)
#endif /* ! defined T1_CONT_RC_UNMAP */

#define T1_TRACE_TASK( taskId_ ) \
(  1 \
)


/*----------------------------------------------------------------------------------*/
/*--- Function wrapper -------------------------------------------------------------*/
/*----------------------------------------------------------------------------------*/

#if defined T1_ENABLE

#endif /* defined T1_ENABLE */

/*----------------------------------------------------------------------------------*/

#endif /* T1_CONFIG_H_ */
