/***********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2021 by Vector Informatik GmbH.                                              All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/*!        \file  vSwUpdM_ExecCtrl_Types.h
 *        \brief  vSwUpdM_ExecCtrl types header file
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Refer to the module's main header file.
 *
 *  FILE VERSION
 *  -------------------------------------------------------------------------------------------------------------------
 *  Refer to the module's main header file vSwUpdM.h.
 *********************************************************************************************************************/

#if !defined (VSWUPDM_EXECCTRL_TYPES_H)
#define VSWUPDM_EXECCTRL_TYPES_H

/***********************************************************************************************************************
 * INCLUDES
 **********************************************************************************************************************/
#include "ComStack_Types.h"

/* Other MultipleUnit's Type Headers used by ExecCtrl_Types */
#include "vSwUpdM_Priv_Types.h"
#include "vSwUpdM_Grid_Types.h"

/***********************************************************************************************************************
 *  GLOBAL CONSTANT MACROS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  GLOBAL FUNCTION MACROS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 **********************************************************************************************************************/

typedef struct
{
  vSwUpdM_GridSrvc_ServiceIdxType ServiceIndex;
  vSwUpdM_NodeGroupIterType       TargetGroup;
  vSwUpdM_NodeIterType            Target;
  boolean                         IsValid;
}
vSwUpdM_ExecCtrl_RemoteResumeServiceType;

typedef enum
{
  VSWUPDM_EXCTSCHEDULE_SERVICESTATE_RUN,
  VSWUPDM_EXCTSCHEDULE_SERVICESTATE_RESUME,
  VSWUPDM_EXCTSCHEDULE_SERVICESTATE_COUNT
}vSwUpdM_ExctSchedule_ServiceStateType;

typedef enum
{
  VSWUPDM_JOB_TYPE_INIT_COMPONENT = 0u,
  VSWUPDM_JOB_TYPE_INIT_PARTITIONS,
  VSWUPDM_JOB_TYPE_INIT_MODULES,
  VSWUPDM_JOB_TYPE_INIT_REGIONS,
  VSWUPDM_JOB_TYPE_INIT_SEGMENTS,
  VSWUPDM_JOB_TYPE_FINALIZE_SYNC_PARTITION,
  VSWUPDM_JOB_TYPE_SWAP_ACTIVE_PARTITION_CHECK,
  VSWUPDM_JOB_TYPE_SWAP_ACTIVE_PARTITION_WORK,
  VSWUPDM_JOB_TYPE_FINALIZE_MODULE_UPDATE_LOCAL,
  VSWUPDM_JOB_TYPE_OPEN_MODULE_LOCAL,
  VSWUPDM_JOB_TYPE_CLEANUP_MODULE,
  VSWUPDM_JOB_TYPE_CLOSE_MODULE_LOCAL,
  VSWUPDM_JOB_TYPE_HANDLE_UPDATE_STATE,
  VSWUPDM_JOB_TYPE_HANDLE_RESUME_INFO,
  VSWUPDM_JOB_TYPE_PERSIST_PARTITION_STATE,
  VSWUPDM_JOB_TYPE_INVALIDATE_PARTITION_LOCAL,
  VSWUPDM_JOB_TYPE_VALIDATE_PARTITION_LOCAL,
  VSWUPDM_JOB_TYPE_CHECK_PARTITION_CONSISTENCY,
  VSWUPDM_JOB_TYPE_PERSIST_MODULE_STATE,
  VSWUPDM_JOB_TYPE_INVALIDATE_MODULE_INTERNAL,
  VSWUPDM_JOB_TYPE_VALIDATE_MODULE_INTERNAL,
  VSWUPDM_JOB_TYPE_PERSIST_REGION_STATE,
  VSWUPDM_JOB_TYPE_PERSIST_ALL_REGION_STATES,
  VSWUPDM_JOB_TYPE_PERSIST_SEGMENT_STATE,
  VSWUPDM_JOB_TYPE_PERSIST_SEGMENT_COUNT,
  VSWUPDM_JOB_TYPE_OPEN_SEGMENT,
  VSWUPDM_JOB_TYPE_CLOSE_SEGMENT,
  VSWUPDM_JOB_TYPE_WAIT_FOR_BOOKKEEPER_OPERATION,
  VSWUPDM_JOB_TYPE_ERASE_MODULE_LOCAL,
  VSWUPDM_JOB_TYPE_ERASE_REGION,
  VSWUPDM_JOB_TYPE_ERASE_RANGE,
  VSWUPDM_JOB_TYPE_START_STREAM,
  VSWUPDM_JOB_TYPE_PROCESS_STREAM_DATA,
  VSWUPDM_JOB_TYPE_END_STREAM,
  VSWUPDM_JOB_TYPE_FILL_MEMORY,
  VSWUPDM_JOB_TYPE_READ_DATA,
  VSWUPDM_JOB_TYPE_WRITE_DATA,
  VSWUPDM_JOB_TYPE_PROCESS_STREAM_PIPELINED,
  VSWUPDM_JOB_TYPE_WAIT_FOR_MEMORY_OPERATION,
  VSWUPDM_JOB_TYPE_FINALIZE_MODULE_LOCAL,
  VSWUPDM_JOB_TYPE_VERIFY_MODULE_LOCAL,
  VSWUPDM_JOB_TYPE_PROCESS_MODULE_LOCAL,
  VSWUPDM_JOB_TYPE_FINALIZE_SEGMENT,
  VSWUPDM_JOB_TYPE_FINALIZE_SEGMENT_UPDATE_LOCAL_STATE,
  VSWUPDM_JOB_TYPE_SYNC_PARTITION_LOCAL,
  VSWUPDM_JOB_TYPE_SYNC_MODULE,
  VSWUPDM_JOB_TYPE_COMPARE_MODULE,
  VSWUPDM_JOB_TYPE_VALIDATE_MODULE_UPDATE_LOCAL_STATE,
  VSWUPDM_JOB_TYPE_INVALIDATE_MODULE_UPDATE_LOCAL_STATE,
  VSWUPDM_JOB_TYPE_SUSPEND,
  VSWUPDM_JOB_TYPE_RESUME,
  VSWUPDM_JOB_TYPE_START,
  VSWUPDM_JOB_TYPE_SHUTDOWN,
  VSWUPDM_JOB_TYPE_REMOTE_LOCK,
  VSWUPDM_JOB_TYPE_REMOTE_GROUP_CONFIRMATION,
  VSWUPDM_JOB_TYPE_REMOTE_SUSPEND_CONFIRMATION,
  VSWUPDM_JOB_TYPE_REMOTE_RESUME_CONFIRMATION,
  VSWUPDM_JOB_TYPE_REMOTE_SHUTDOWN_CONFIRMATION,
  VSWUPDM_JOB_TYPE_REMOTE_TARGET_CONFIRMATION,
  VSWUPDM_JOB_TYPE_SERVICE_DISPATCHER,
  VSWUPDM_JOB_TYPE_OPEN_PARTITION_LOCAL_HOOKS,
  VSWUPDM_JOB_TYPE_ERASE_REGION_LOCAL_WORK,
  VSWUPDM_JOB_TYPE_REMOTE_ADD_SEGMENTS,
  VSWUPDM_JOB_TYPE_CLEAR_SEGMENTS_OF_MODULE,
  VSWUPDM_JOB_TYPE_REMOTE_PROCESS_STREAM_DATA,
  VSWUPDM_JOB_TYPE_PROCESS_ENTITY,
  VSWUPDM_JOB_TYPE_REMOTE_PROCESS_INFO,
  VSWUPDM_JOB_TYPE_REMOTE_STREAM_SCHEDULER,
  VSWUPDM_JOB_TYPE_REMOTE_STREAM_CLEANUP,
  VSWUPDM_JOB_TYPE_INDICATE_WRITE_TO_MODULE,
  VSWUPDM_JOB_TYPE_COUNT,
  VSWUPDM_JOB_TYPE_INVALID
} vSwUpdM_JobTypeType;

typedef enum
{
  /* Default/initial operation */
  VSWUPDM_JOB_OPERATION_DEFAULT,

  /* Job type specific operations */
  /* Wait for bookkeeper */
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_NONE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_CALLOUT_INIT,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_OPEN_LOCAL,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_OPEN,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_CLOSE_LOCAL,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_CLOSE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_UPDATE_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_UPDATE_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_PARTITION_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_PARTITION_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_PARTITION_REVISION,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_PARTITION_REVISION,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_PARTITION_VALID,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_PARTITION_VALID,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_MODULE_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_MODULE_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_MODULE_REVISION,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_MODULE_REVISION,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_MODULE_PROGRAMMING_ATTEMPTS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_MODULE_PROGRAMMING_ATTEMPTS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_MODULE_VALID,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_MODULE_VALID,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_REGION_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_REGION_STATE,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_REGION_PROGRAMMING_ATTEMPTS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_REGION_PROGRAMMING_ATTEMPTS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_REGION_ERASE_ADDRESS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_REGION_ERASE_ADDRESS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_SEGMENT_COUNT,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_SEGMENT_COUNT,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_SEGMENT_ATTRIBUTES,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_SEGMENT_ATTRIBUTES,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_SEGMENT_WRITE_ADDRESS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_SEGMENT_WRITE_ADDRESS,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_GET_RESUME_INFO,
  VSWUPDM_JOB_OPERATION_WAIT_BOOKKEEPER_SET_RESUME_INFO,
  /* Wait for memory operation */
  VSWUPDM_JOB_OPERATION_WAIT_MEMORY_READ,
  VSWUPDM_JOB_OPERATION_WAIT_MEMORY_WRITE,
  VSWUPDM_JOB_OPERATION_WAIT_MEMORY_ERASE,
  /* Init segments */
  VSWUPDM_JOB_OPERATION_INIT_SEGMENTS_FIRST_SEGMENT,
  VSWUPDM_JOB_OPERATION_INIT_SEGMENTS_KEEP_STATE,
  /* Open module */
  VSWUPDM_JOB_OPERATION_OPEN_MODULE_RESTORE_SEGMENTS,
  /* Erase/finalize/sync module */
  VSWUPDM_JOB_OPERATION_CLOSE_MODULE,
  /* Erase region */
  VSWUPDM_JOB_OPERATION_ERASE_REGION_UPDATE_MODULE_STATE,
  /* Finalize segment */
  VSWUPDM_JOB_OPERATION_CLOSE_SEGMENT,
  /* Handle update state */
  VSWUPDM_JOB_OPERATION_HANDLE_UPDATE_STATE_GET,
  VSWUPDM_JOB_OPERATION_HANDLE_UPDATE_STATE_SET,
  /* Handle resume info */
  VSWUPDM_JOB_OPERATION_HANDLE_RESUME_INFO_GET,
  VSWUPDM_JOB_OPERATION_HANDLE_RESUME_INFO_SET,
  /* Shutdown */
  VSWUPDM_JOB_OPERATION_SHUTDOWN_SUSPEND,
  /* Service Dispatch */
  VSWUPDM_JOB_OPERATION_CHECK_AND_WORK,
  VSWUPDM_JOB_OPERATION_CHECK,
  VSWUPDM_JOB_OPERATION_WORK
  /* RemoteProcessInfo */
} vSwUpdM_JobOperationType;

typedef enum
{
  /* Default states */
  VSWUPDM_JOB_STATE_INITIAL,
  VSWUPDM_JOB_STATE_PENDING,
  VSWUPDM_JOB_STATE_FINAL,
  VSWUPDM_JOB_STATE_FAILED,
  VSWUPDM_JOB_STATE_CANCEL,
  VSWUPDM_JOB_STATE_EVAL_HOOK,

  /* Job type specific states */
  /* Init component */
  VSWUPDM_JOB_STATE_INIT_COMPONENT_BOOKKEEPER_OPEN_LOCAL,
  VSWUPDM_JOB_STATE_INIT_COMPONENT_BOOKKEEPER_OPEN,
  VSWUPDM_JOB_STATE_INIT_COMPONENT_PARTITIONS,
  VSWUPDM_JOB_STATE_INIT_COMPONENT_UPDATE_STATE,
  VSWUPDM_JOB_STATE_INIT_COMPONENT_RESUME_INFO,
  /* Init partitions */
  VSWUPDM_JOB_STATE_INIT_PARTITIONS_STATE,
  VSWUPDM_JOB_STATE_INIT_PARTITIONS_VALID,
  VSWUPDM_JOB_STATE_INIT_PARTITIONS_REVISION,
  VSWUPDM_JOB_STATE_INIT_PARTITIONS_MODULES,
  /* Init modules */
  VSWUPDM_JOB_STATE_INIT_MODULES_CHECK_PARTITION,
  VSWUPDM_JOB_STATE_INIT_MODULES_STATE,
  VSWUPDM_JOB_STATE_INIT_MODULES_PROGRAMMING_ATTEMPTS,
  VSWUPDM_JOB_STATE_INIT_MODULES_VALID,
  VSWUPDM_JOB_STATE_INIT_MODULES_REVISION,
  /* Init regions */
  VSWUPDM_JOB_STATE_INIT_REGIONS_GET_REGION_STATE,
  VSWUPDM_JOB_STATE_INIT_REGIONS_GET_REGION_PROGRAMMING_ATTEMPTS,
  VSWUPDM_JOB_STATE_INIT_REGIONS_GET_ERASE_ADDRESS,
  VSWUPDM_JOB_STATE_INIT_REGIONS_NEXT_REGION,
  /* Init segments */
  VSWUPDM_JOB_STATE_INIT_SEGMENTS_COUNT,
  VSWUPDM_JOB_STATE_INIT_SEGMENTS_ATTRIBUTES,
  VSWUPDM_JOB_STATE_INIT_SEGMENTS_CHECK_SEGMENT,
  VSWUPDM_JOB_STATE_INIT_SEGMENTS_WRITE_ADDRESSES,
  VSWUPDM_JOB_STATE_INIT_SEGMENTS_NEXT_SEGMENT,
  /* Open module */
  VSWUPDM_JOB_STATE_OPEN_MODULE_INIT_REGIONS,
  VSWUPDM_JOB_STATE_OPEN_MODULE_INIT_SEGMENTS,
  VSWUPDM_JOB_STATE_OPEN_MODULE_CLEANUP,
  VSWUPDM_JOB_STATE_OPEN_MODULE_UPDATE_STATE,
  /* Cleanup module */
  VSWUPDM_JOB_STATE_CLEANUP_MODULE_SWEEP_START,
  VSWUPDM_JOB_STATE_CLEANUP_MODULE_SWEEP_EVALUATE,
  VSWUPDM_JOB_STATE_CLEANUP_MODULE_SWEEP_ERASE,
  VSWUPDM_JOB_STATE_CLEANUP_MODULE_SWEEP_UPDATE,
  VSWUPDM_JOB_STATE_CLEANUP_MODULE_SWEEP_NEXT,
  /* Erase module */
  VSWUPDM_JOB_STATE_LOCAL_ERASE_MODULE_ERASE_REGION,
  VSWUPDM_JOB_STATE_LOCAL_ERASE_MODULE_ERASE_REGION_CHECK,
  VSWUPDM_JOB_STATE_LOCAL_ERASE_MODULE_UPDATE_STATE,
  /* Erase region */
  VSWUPDM_JOB_STATE_ERASE_REGION_STATE,
  VSWUPDM_JOB_STATE_ERASE_REGION_START,
  VSWUPDM_JOB_STATE_ERASE_REGION_UPDATE,
  VSWUPDM_JOB_STATE_ERASE_REGION_UPDATE_MODULE_STATE,
  /* Sync partition */
  VSWUPDM_JOB_STATE_SYNC_PARTITION_CHECK_MODULE,
  VSWUPDM_JOB_STATE_SYNC_PARTITION_NEXT_MODULE,
  /* Sync module */
  VSWUPDM_JOB_STATE_SYNC_MODULE_ERASE,
  VSWUPDM_JOB_STATE_SYNC_MODULE_START_SYNC,
  VSWUPDM_JOB_STATE_SYNC_MODULE_COMPARE,
  VSWUPDM_JOB_STATE_SYNC_MODULE_VERIFY,
  VSWUPDM_JOB_STATE_SYNC_MODULE_FINALIZE,
  VSWUPDM_JOB_STATE_SYNC_MODULE_VALIDATE,
  /* Compare module */
  VSWUPDM_JOB_STATE_COMPARE_MODULE_TRIGGER_PROCESSING,
  VSWUPDM_JOB_STATE_COMPARE_MODULE_FAIL_CLOSE_MODULE,
  VSWUPDM_JOB_STATE_COMPARE_MODULE_CLOSE_MODULE,
  /* Fill memory */
  VSWUPDM_JOB_STATE_FILL_MEMORY_FILL,
  VSWUPDM_JOB_STATE_FILL_MEMORY_WRITE,
  VSWUPDM_JOB_STATE_FILL_MEMORY_NEXT_CHUNK,
  /* Finalize module */
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_CHECK_SEGMENT_STATE,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_EVAL_FREE_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_EVAL_RESERVED_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_EVAL_USED_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_PREPARE_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_FILL_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_CLOSE_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_NEXT_SEGMENT,
  VSWUPDM_JOB_STATE_FINALIZE_MODULE_CLOSE,
  /* Process stream data */
  VSWUPDM_JOB_STATE_PROCESS_STREAM_DATA_COPY,
  VSWUPDM_JOB_STATE_PROCESS_STREAM_EVALUATE_REMOTE_COPY,
  VSWUPDM_JOB_STATE_PROCESS_STREAM_DATA_REMOTE,
  VSWUPDM_JOB_STATE_PROCESS_STREAM_DATA_FINALIZE,
  VSWUPDM_JOB_STATE_PROCESS_STREAM_DATA_PROCESS,
  VSWUPDM_JOB_STATE_PROCESS_STREAM_DATA_PROCESS_PIPELINED,
  VSWUPDM_JOB_STATE_PROCESS_STREAM_DATA_ABORT,
  /* Finalize segment */
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_PREPARE,
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_PROCESS,
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_CONCLUDE,
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_CLOSE,
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_ABORT,
  /* Finalize segment (update local state) */
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_UPDATE_REGION_STATE,
  VSWUPDM_JOB_STATE_FINALIZE_SEGMENT_UPDATE_MODULE_STATE,
  /* Shutdown */
  VSWUPDM_JOB_STATE_SHUTDOWN_GRID_WAIT,
  VSWUPDM_JOB_STATE_SHUTDOWN_REDUCE_PRIO,
  VSWUPDM_JOB_STATE_SHUTDOWN_CLEANUP,
  VSWUPDM_JOB_STATE_SHUTDOWN_PIPE_PREPARE,
  VSWUPDM_JOB_STATE_SHUTDOWN_PIPE_PROCESS,
  VSWUPDM_JOB_STATE_SHUTDOWN_CLOSE_MODULE,
  VSWUPDM_JOB_STATE_SHUTDOWN_UPDATE_RESUME_INFO,
  VSWUPDM_JOB_STATE_SHUTDOWN_BOOKKEEPER_CLOSE,
  VSWUPDM_JOB_STATE_SHUTDOWN_BOOKKEEPER_CLOSE_LOCAL,
  /* Resume */
  VSWUPDM_JOB_STATE_RESUME_ENQUEUE_JOBS,
  VSWUPDM_JOB_STATE_RESUME_REMOTE,
  VSWUPDM_JOB_STATE_SYNC_RESUME,
  /* Service Dispatch */
  VSWUPDM_JOB_STATE_DISPATCH_CHECK_LOCAL_PRECONDITION,
  VSWUPDM_JOB_STATE_DISPATCH_TRIGGER_REMOTE_WORK,
  VSWUPDM_JOB_STATE_DISPATCH_EXCECUTE_LOCAL_WORK,
  VSWUPDM_JOB_STATE_DISPATCH_UPDATE_REMOTE_STATE,
  VSWUPDM_JOB_STATE_DISPATCH_UPDATE_LOCAL_STATE,
  /* Verify */
  VSWUPDM_JOB_STATE_VERIFY_INIT_USER_ENTRY_NODES,
  VSWUPDM_JOB_STATE_VERIFY_PROCESS_SEGMENT,
  VSWUPDM_JOB_STATE_VERIFY_WAIT_FOR_PIPE,
  VSWUPDM_JOB_STATE_VERIFY_FLUSH,
  VSWUPDM_JOB_STATE_VERIFY_COLLECT_RESULTS,
  /* Process */
  VSWUPDM_JOB_STATE_PROCESS_REMOTE_REQUEST_NEXT_INPUT,
  VSWUPDM_JOB_STATE_PROCESS_REMOTE_WAIT_RX,
  VSWUPDM_JOB_STATE_PROCESS_INIT_PIPE,
  VSWUPDM_JOB_STATE_PROCESS_INIT_EXTERNAL_ENTRY_NODES,
  VSWUPDM_JOB_STATE_PROCESS_INIT_INTERNAL_EVAL_SCOPE,
  VSWUPDM_JOB_STATE_PROCESS_INIT_INTERNAL_SELECT_SEGMENT,
  VSWUPDM_JOB_STATE_PROCESS_INIT_INTERNAL_ENTRY_NODES,
  VSWUPDM_JOB_STATE_PROCESS_INIT_INTERNAL_NEXT_SEGMENT,
  VSWUPDM_JOB_STATE_PROCESS_PROCESS_PIPE,
  VSWUPDM_JOB_STATE_PROCESS_FLUSH,
  VSWUPDM_JOB_STATE_PROCESS_PROVIDE_EXTERNAL_RESULTS_REMOTE,
  VSWUPDM_JOB_STATE_PROCESS_PROVIDE_EXTERNAL_RESULTS_REMOTE_WAIT,
  VSWUPDM_JOB_STATE_PROCESS_COLLECT_EXTERNAL_RESULTS,
  VSWUPDM_JOB_STATE_PROCESS_COLLECT_EXTERNAL_RESULTS_FAIL,
  VSWUPDM_JOB_STATE_PROCESS_COLLECT_INTERNAL_RESULTS,
  VSWUPDM_JOB_STATE_PROCESS_POST_ACTION
} vSwUpdM_JobStateType;

typedef enum
{
  VSWUPDM_EXECCTRL_SEQUENCEIDX_OPEN_PARTITION,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_VALIDATE_PARTITION,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_INVALIDATE_PARTITION,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_SWAP_ACTIVE_PARTITION,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_FINALIZE_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_VERIFY_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_PROCESS_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_VERIFY_SEGMENT,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_SYNC_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_VALIDATE_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_INVALIDATE_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_ERASE_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_ERASE_REGION,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_OPEN_SEGMENT,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_CLOSE_SEGMENT,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_CLEAR_SEGMENTS_OF_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_FINALIZE_SEGMENT,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_SYNC_PARTITION,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_START_STREAM,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_END_STREAM,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_OPEN_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_CLOSE_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_CHECK_PARTITION_CONSISTENCY,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_INDICATE_WRITE_TO_MODULE,
  VSWUPDM_EXECCTRL_SEQUENCEIDX_INVALID
} vSwUpdM_ExecCtrl_SequenceListIndexType;

typedef struct
{
  vSwUpdM_JobTypeType           Type;
  vSwUpdM_JobOperationType      Operation;
  vSwUpdM_JobStateType          State;
  vSwUpdM_QueuePrioType         DefaultPrio;
  vSwUpdM_QueuePrioType         CurrentPrio;
  vSwUpdM_LengthType            Segmentation;
  vSwUpdM_LengthType            PendingLength;
  vSwUpdM_QueueHandleType       QueueHandle;
  vSwUpdM_AddressType           TargetAddress;  /**< Currently processed address */
  vSwUpdM_EntityIdsType         EntityIds;
  P2VAR(vSwUpdM_BufferInfoType, AUTOMATIC, VSWUPDM_APPL_VAR)    InputBuffer;
  P2VAR(vSwUpdM_BufferInfoType, AUTOMATIC, VSWUPDM_APPL_VAR)    OutputBuffer;
  vSwUpdM_ServiceIdType         ServiceId;
  vSwUpdM_ServiceIdType         ConfirmationService;
  Std_ReturnType                Result;
  vSwUpdM_LinkedResultType      ChildResult;
  P2VAR(vSwUpdM_LinkedResultType, AUTOMATIC, VSWUPDM_APPL_VAR)  LinkedResult;
  boolean                       Suspendable;
  boolean                       UpdateResumeInfo;
  vSwUpdM_ServiceHookPtrType    PreHookFct;
  vSwUpdM_ServiceHookPtrType    PostHookFct;
  vSwUpdM_HookActionType        HookAction;
  uint8                         RetryCount;
  vSwUpdM_RetryGranularity      RetryGranularity;
  vSwUpdM_JobPhaseType          Phase;
  /* vSwUpdM_RpcProxyServiceIdType RemoteServiceId; */
  vSwUpdM_GridSrvc_ServiceIdxType RemoteServiceIndex;
  vSwUpdM_NodeGroupIterType     RemoteTargetGroup;
  vSwUpdM_NodeIterType          RemoteTarget;
  vSwUpdM_NodeIterType          Source;
  uint32                        Count;
  vSwUpdM_ExecCtrl_SequenceListIndexType SequenceIdx;
} vSwUpdM_JobType;

typedef P2VAR(vSwUpdM_JobType, AUTOMATIC, VSWUPDM_APPL_VAR)   vSwUpdM_JobPtrType;

typedef enum
{
  VSWUPDM_JOB_PRIO_DEFAULT = 0u,

  VSWUPDM_JOB_PRIO_SHUTDOWN_LOW,
  VSWUPDM_JOB_PRIO_REMOTE_SHUTDOWN_CONFIRMATION,
  VSWUPDM_JOB_PRIO_RESUME_LOW,
  VSWUPDM_JOB_PRIO_SUSPEND_LOW,
  VSWUPDM_JOB_PRIO_REMOTE_SUSPEND_CONFIRMATION,
  VSWUPDM_JOB_PRIO_SERVICE_DISPATCHER,
  VSWUPDM_JOB_PRIO_START,
  VSWUPDM_JOB_PRIO_WAIT_FOR_BOOKKEEPER_OPERATION,
  VSWUPDM_JOB_PRIO_INDICATE_WRITE_TO_MODULE,
  VSWUPDM_JOB_PRIO_OPEN_PARTITION_LOCAL_HOOKS,
  VSWUPDM_JOB_PRIO_ERASE_REGION_LOCAL_WORK,
  VSWUPDM_JOB_PRIO_REMOTE_ADD_SEGMENTS,
  VSWUPDM_JOB_PRIO_CLEAR_SEGMENTS_OF_MODULE,
  VSWUPDM_JOB_PRIO_FINALIZE_SYNC_PARTITION,
  VSWUPDM_JOB_PRIO_SWAP_ACTIVE_PARTITION_CHECK,
  VSWUPDM_JOB_PRIO_SWAP_ACTIVE_PARTITION_WORK,
  VSWUPDM_JOB_PRIO_SYNC_PARTITION_LOCAL,
  VSWUPDM_JOB_PRIO_SYNC_MODULE,
  VSWUPDM_JOB_PRIO_COMPARE_MODULE,
  VSWUPDM_JOB_PRIO_FINALIZE_MODULE_UPDATE_LOCAL,
  VSWUPDM_JOB_PRIO_FINALIZE_MODULE_LOCAL,
  VSWUPDM_JOB_PRIO_VERIFY_MODULE_LOCAL,
  VSWUPDM_JOB_PRIO_PROCESS_MODULE_LOCAL,
  VSWUPDM_JOB_PRIO_FINALIZE_SEGMENT_UPDATE_LOCAL_STATE,
  VSWUPDM_JOB_PRIO_FINALIZE_SEGMENT,
  VSWUPDM_JOB_PRIO_MUX_END_STREAM,
  VSWUPDM_JOB_PRIO_END_STREAM,
  VSWUPDM_JOB_PRIO_FILL_MEMORY,
  VSWUPDM_JOB_PRIO_PROCESS_STREAM_PIPELINED,
  VSWUPDM_JOB_PRIO_PROCESS_STREAM_DATA,
  VSWUPDM_JOB_PRIO_REMOTE_PROCESS_STREAM_DATA,
  VSWUPDM_JOB_PRIO_PROCESS,
  VSWUPDM_JOB_PRIO_COPY_STREAM_DATA,
  VSWUPDM_JOB_PRIO_WRITE_DATA,
  VSWUPDM_JOB_PRIO_READ_DATA,
  VSWUPDM_JOB_PRIO_MUX_START_STREAM,
  VSWUPDM_JOB_PRIO_START_STREAM,
  VSWUPDM_JOB_PRIO_ERASE_MODULE_LOCAL,
  VSWUPDM_JOB_PRIO_ERASE_REGION,
  VSWUPDM_JOB_PRIO_ERASE_RANGE,
  VSWUPDM_JOB_PRIO_OPEN_SEGMENT,
  VSWUPDM_JOB_PRIO_OPEN_MODULE_LOCAL,
  VSWUPDM_JOB_PRIO_CLEANUP_MODULE,
  VSWUPDM_JOB_PRIO_CLOSE_MODULE_LOCAL,
  VSWUPDM_JOB_PRIO_CLOSE_SEGMENT,
  VSWUPDM_JOB_PRIO_HANDLE_UPDATE_STATE,
  VSWUPDM_JOB_PRIO_VALIDATE_MODULE_UPDATE_LOCAL_STATE,
  VSWUPDM_JOB_PRIO_INVALIDATE_MODULE_UPDATE_LOCAL_STATE,
  VSWUPDM_JOB_PRIO_CHECK_PARTITION_CONSISTENCY,
  VSWUPDM_JOB_PRIO_INIT_PARTITIONS,
  VSWUPDM_JOB_PRIO_INIT_MODULES,
  VSWUPDM_JOB_PRIO_INIT_SEGMENTS,
  VSWUPDM_JOB_PRIO_INIT_REGIONS,
  VSWUPDM_JOB_PRIO_WAIT_FOR_MEMORY_OPERATION,
  VSWUPDM_JOB_PRIO_INIT_COMPONENT,
  VSWUPDM_JOB_PRIO_REMOTE_LOCK,
  VSWUPDM_JOB_PRIO_REMOTE_GROUP_CONFIRMATION,
  VSWUPDM_JOB_PRIO_RESUME,
  VSWUPDM_JOB_PRIO_HANDLE_RESUME_INFO,
  VSWUPDM_JOB_PRIO_REMOTE_PROCESS_INFO,
  VSWUPDM_JOB_PRIO_REMOTE_STREAM_SCHEDULER,
  VSWUPDM_JOB_PRIO_REMOTE_STREAM_CLEANUP,
  VSWUPDM_JOB_PRIO_REMOTE_RESUME_CONFIRMATION,
  VSWUPDM_JOB_PRIO_INVALIDATE_MODULE_INTERNAL,
  VSWUPDM_JOB_PRIO_VALIDATE_MODULE_INTERNAL,
  VSWUPDM_JOB_PRIO_INVALIDATE_PARTITION_LOCAL,
  VSWUPDM_JOB_PRIO_VALIDATE_PARTITION_LOCAL,
  VSWUPDM_JOB_PRIO_REMOTE_TARGET_CONFIRMATION,
  VSWUPDM_JOB_PRIO_SHUTDOWN,
  VSWUPDM_JOB_PRIO_PERSIST_ALL_REGION_STATES,
  VSWUPDM_JOB_PRIO_PERSIST_REGION_STATE_LOW,
  VSWUPDM_JOB_PRIO_PERSIST_SEGMENT_COUNT,
  VSWUPDM_JOB_PRIO_PERSIST_SEGMENT_STATE,
  VSWUPDM_JOB_PRIO_PERSIST_REGION_STATE,
  VSWUPDM_JOB_PRIO_PERSIST_MODULE_STATE,
  VSWUPDM_JOB_PRIO_PERSIST_PARTITION_STATE,
  VSWUPDM_JOB_PRIO_SUSPEND
} vSwUpdM_JobPrioType;

typedef enum
{
  VSWUPDM_JOB_STATUS_ACTIVE,
  VSWUPDM_JOB_STATUS_PENDING,
  VSWUPDM_JOB_STATUS_FINISHED,
  VSWUPDM_JOB_STATUS_SUSPENDED
} vSwUpdM_JobStatusType;

typedef struct
{
  vSwUpdM_JobTypeType   JobType;
  vSwUpdM_ServiceIdType ServiceId;
  vSwUpdM_JobPrioType   Priority;
  boolean               Suspendable;
} vSwUpdM_JobDefinitionType;

/***********************************************************************************************************************
 *  GLOBAL DATA PROTOTYPES
 **********************************************************************************************************************/

/***********************************************************************************************************************
 *  GLOBAL FUNCTION PROTOTYPES
 **********************************************************************************************************************/

#endif  /* VSWUPDM_EXECCTRL_TYPES_H */

/***********************************************************************************************************************
 *  END OF FILE: vSwUpdM_ExecCtrl_Types.h
 **********************************************************************************************************************/
