/*
********************************************************************************
*
*  File name:	Os_Arch_Kernal_Lcfg.c
*
*  Copyright	Neusoft Reach Corporation. All rights reserved.
*
********************************************************************************
*
* History
*-------------------------------------------------------------------------------
********************************************************************************
* Version: 3.0
* Author/Date : HanCL/2021.11.23
* Change: New create.
* Cause: New
********************************************************************************
*/
/*
********************************************************************************
*    Includes
********************************************************************************
*/
#include "Os_Arch_Interrupt_Lcfg.h"
#include "Os_Arch_Exception.h"
#include "Os_Arch_Compiler.h"

/*
********************************************************************************
*    Local Macros
********************************************************************************
*/
/*
********************************************************************************
*    Local Types
********************************************************************************
*/
/*
********************************************************************************
*    Local Variables
********************************************************************************
*/
/*
********************************************************************************
*    Local Constants
********************************************************************************
*/
/*
********************************************************************************
*    Local Functions
********************************************************************************
*/
/*
********************************************************************************
*    Global Variable
********************************************************************************
*/
OS_ARCH_CODE_SECTION(OS_IRQVEC_OSCORE )
OS_ARCH_GLOBAL_EXCINTVEC(OS_IRQVEC_OSCORE )
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_MultiCommIsr_OsCore_Core0)    /* 0 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_MultiCommIsr_OsCore_Core1)    /* 1 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_MultiCommIsr_OsCore_Core2)    /* 2 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 3 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 4 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 5 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 6 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 7 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 8 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 9 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 10 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 11 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 12 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 13 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 14 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 15 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 16 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 17 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 18 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 19 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 20 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 21 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 22 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 23 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 24 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 25 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 26 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 27 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 28 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 29 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 30 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 31 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 32 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 33 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 34 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 35 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Os_Monitor_Isr)               /* 36 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 37 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 38 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 39 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 40 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 41 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 42 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 43 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 44 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 45 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 46 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 47 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 48 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 49 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 50 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 51 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 52 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 53 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 54 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 55 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 56 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 57 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 58 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 59 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 60 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 61 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 62 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 63 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 64 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 65 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 66 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 67 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 68 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 69 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 70 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 71 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 72 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 73 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 74 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 75 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 76 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 77 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 78 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 79 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 80 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 81 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 82 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 83 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 84 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 85 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 86 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 87 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 88 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 89 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 90 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 91 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 92 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 93 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 94 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 95 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 96 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 97 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 98 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 99 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 100 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 101 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 102 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 103 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 104 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 105 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 106 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 107 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 108 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 109 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 110 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 111 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 112 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 113 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 114 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 115 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 116 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 117 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 118 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 119 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 120 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 121 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 122 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 123 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 124 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 125 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 126 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 127 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 128 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 129 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 130 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 131 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 132 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_EDMA_Ch80_IRQHandler)         /* 133 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 134 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 135 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 136 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 137 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 138 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 139 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 140 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 141 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 142 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 143 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 144 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 145 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 146 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 147 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 148 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 149 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 150 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 151 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 152 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 153 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 154 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 155 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 156 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 157 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 158 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 159 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 160 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 161 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 162 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 163 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 164 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 165 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 166 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 167 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 168 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 169 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 170 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 171 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 172 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 173 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 174 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 175 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 176 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 177 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 178 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 179 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 180 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 181 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 182 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 183 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 184 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_FlashDone_Isr)                /* 185 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 186 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 187 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 188 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 189 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 190 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 191 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 192 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 193 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 194 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 195 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 196 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 197 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 198 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 199 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 200 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 201 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 202 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 203 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 204 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 205 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 206 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 207 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 208 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 209 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 210 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 211 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 212 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 213 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 214 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 215 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 216 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 217 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 218 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 219 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 220 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 221 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 222 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 223 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 224 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 225 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_CounterIsr_SystemTimer_Core0) /* 226 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_CounterIsr_SystemTimer_Core1) /* 227 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_CounterIsr_SystemTimer_Core2) /* 228 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 229 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_PIT0_CH4)                     /* 230 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_PIT0_CH5)                     /* 231 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_PIT0_CH6)                     /* 232 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 233 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 234 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 235 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 236 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 237 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 238 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 239 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 240 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 241 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 242 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_SIUL_External_0_ISRFunc)      /* 243 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_SIUL_External_1_ISRFunc)      /* 244 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 245 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 246 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 247 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 248 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 249 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 250 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 251 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 252 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 253 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 254 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 255 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 256 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 257 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 258 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 259 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 260 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 261 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 262 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 263 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 264 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 265 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 266 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 267 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 268 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 269 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 270 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 271 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 272 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 273 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 274 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 275 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 276 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 277 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 278 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 279 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 280 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 281 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 282 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 283 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 284 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 285 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 286 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 287 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 288 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 289 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 290 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 291 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 292 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 293 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 294 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 295 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 296 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 297 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 298 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 299 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 300 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 301 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 302 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 303 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 304 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 305 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 306 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 307 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 308 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 309 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 310 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 311 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 312 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 313 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 314 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 315 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 316 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 317 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 318 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 319 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 320 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 321 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 322 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 323 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 324 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 325 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 326 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 327 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 328 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 329 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 330 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 331 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 332 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 333 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 334 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 335 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 336 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 337 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 338 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 339 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 340 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 341 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 342 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 343 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 344 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 345 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 346 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 347 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 348 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 349 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 350 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 351 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 352 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 353 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 354 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 355 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 356 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 357 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 358 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 359 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 360 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 361 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 362 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 363 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 364 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 365 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 366 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 367 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 368 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 369 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 370 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 371 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 372 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 373 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 374 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 375 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 376 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 377 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 378 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 379 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 380 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 381 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 382 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 383 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 384 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 385 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 386 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 387 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 388 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 389 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 390 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 391 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 392 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 393 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 394 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 395 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 396 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 397 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 398 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 399 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 400 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 401 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 402 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 403 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 404 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 405 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 406 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 407 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 408 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 409 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 410 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 411 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 412 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 413 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 414 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 415 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 416 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 417 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 418 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 419 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 420 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 421 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 422 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 423 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 424 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 425 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 426 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 427 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 428 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 429 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 430 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 431 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 432 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 433 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 434 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 435 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 436 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 437 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 438 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 439 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 440 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 441 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 442 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 443 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 444 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Can2_Isr)                     /* 445 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 446 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Can3_Isr)                     /* 447 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 448 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Can4_Isr)                     /* 449 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 450 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 451 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 452 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 453 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 454 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 455 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 456 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 457 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 458 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 459 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 460 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 461 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 462 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 463 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 464 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 465 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 466 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 467 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 468 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 469 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 470 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 471 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 472 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 473 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 474 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 475 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 476 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 477 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 478 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 479 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 480 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 481 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 482 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 483 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 484 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 485 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 486 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 487 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 488 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 489 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 490 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 491 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 492 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 493 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 494 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 495 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 496 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 497 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 498 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 499 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 500 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 501 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 502 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 503 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 504 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 505 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 506 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 507 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 508 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 509 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 510 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 511 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 512 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 513 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 514 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 515 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 516 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 517 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 518 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 519 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 520 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 521 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 522 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 523 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 524 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 525 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 526 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 527 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 528 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 529 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 530 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 531 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 532 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 533 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 534 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 535 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 536 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 537 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 538 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 539 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 540 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 541 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 542 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 543 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 544 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 545 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 546 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 547 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 548 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 549 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 550 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 551 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 552 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 553 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 554 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 555 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 556 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 557 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 558 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 559 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 560 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 561 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 562 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 563 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 564 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 565 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 566 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 567 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 568 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 569 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 570 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 571 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 572 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 573 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 574 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 575 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 576 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 577 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 578 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 579 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 580 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 581 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 582 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 583 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 584 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 585 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 586 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 587 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 588 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 589 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 590 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 591 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 592 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 593 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 594 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 595 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 596 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 597 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 598 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 599 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 600 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 601 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 602 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 603 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 604 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 605 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 606 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 607 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 608 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 609 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 610 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 611 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 612 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 613 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 614 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 615 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 616 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 617 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 618 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 619 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 620 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 621 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 622 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 623 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 624 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 625 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 626 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 627 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 628 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 629 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 630 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 631 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 632 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 633 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 634 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 635 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 636 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 637 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 638 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 639 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 640 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 641 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 642 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 643 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 644 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 645 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 646 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 647 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 648 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 649 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 650 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 651 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 652 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 653 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 654 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 655 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 656 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 657 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 658 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 659 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 660 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 661 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 662 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 663 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 664 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 665 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 666 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 667 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 668 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 669 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 670 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 671 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 672 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 673 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 674 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 675 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 676 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 677 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 678 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 679 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 680 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 681 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 682 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 683 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 684 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 685 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 686 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 687 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Can1_Isr)                     /* 688 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 689 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 690 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 691 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 692 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 693 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 694 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 695 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 696 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 697 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 698 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 699 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 700 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 701 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 702 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 703 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 704 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 705 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 706 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 707 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 708 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 709 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 710 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 711 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 712 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 713 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 714 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 715 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 716 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 717 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 718 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 719 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 720 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 721 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 722 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 723 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 724 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 725 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 726 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 727 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 728 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 729 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 730 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 731 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 732 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 733 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 734 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 735 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 736 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 737 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 738 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 739 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 740 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 741 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 742 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 743 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 744 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 745 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 746 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 747 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 748 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 749 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 750 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 751 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 752 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 753 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 754 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 755 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 756 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 757 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 758 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 759 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 760 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 761 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 762 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 763 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 764 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 765 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 766 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 767 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 768 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 769 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 770 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 771 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 772 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 773 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 774 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 775 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 776 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 777 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 778 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 779 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 780 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 781 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 782 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 783 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 784 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 785 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 786 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 787 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 788 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 789 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 790 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 791 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 792 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 793 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 794 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 795 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 796 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 797 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 798 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 799 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 800 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 801 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 802 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 803 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 804 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 805 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 806 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 807 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 808 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 809 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 810 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 811 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 812 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 813 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 814 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 815 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 816 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 817 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 818 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 819 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 820 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 821 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 822 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 823 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 824 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 825 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 826 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 827 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 828 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 829 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 830 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 831 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 832 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 833 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 834 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 835 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 836 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 837 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 838 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 839 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 840 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_GTM_ATOM10_ISRfunc)           /* 841 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 842 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 843 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 844 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 845 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 846 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 847 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 848 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 849 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 850 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 851 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 852 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_GTM_ATOM40_ISRfunc)           /* 853 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 854 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 855 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 856 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 857 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 858 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 859 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 860 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 861 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 862 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 863 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 864 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 865 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 866 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 867 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 868 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 869 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 870 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 871 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 872 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 873 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 874 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 875 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 876 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 877 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 878 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 879 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 880 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 881 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 882 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 883 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 884 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 885 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 886 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 887 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 888 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 889 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 890 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 891 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 892 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 893 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 894 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 895 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 896 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 897 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 898 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 899 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 900 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 901 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 902 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 903 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 904 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 905 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 906 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 907 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 908 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 909 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 910 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 911 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 912 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 913 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 914 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 915 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 916 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 917 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 918 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 919 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 920 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 921 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 922 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 923 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 924 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 925 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 926 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 927 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 928 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 929 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 930 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 931 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 932 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 933 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 934 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 935 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 936 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 937 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 938 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 939 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 940 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 941 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 942 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 943 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 944 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 945 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 946 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 947 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 948 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 949 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 950 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 951 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 952 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 953 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 954 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 955 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 956 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 957 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 958 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 959 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 960 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 961 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 962 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 963 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 964 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 965 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 966 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 967 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 968 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 969 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 970 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 971 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 972 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 973 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 974 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 975 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 976 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 977 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 978 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 979 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 980 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 981 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 982 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 983 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 984 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 985 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 986 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 987 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 988 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Adc89_Grp0_Isr)               /* 989 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Adc89_Grp1_Isr)               /* 990 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Adc89_Grp2_Isr)               /* 991 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Adc89_Grp3_Isr)               /* 992 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Adc89_Grp4_Isr)               /* 993 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Adc89_Grp5_Isr)               /* 994 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 995 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 996 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 997 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 998 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 999 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1000 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1001 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1002 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1003 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1004 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1005 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1006 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1007 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1008 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1009 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1010 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1011 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1012 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1013 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1014 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1015 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1016 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1017 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1018 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1019 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1020 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1021 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1022 */
OS_ARCH_EIINT_ENTRY(Os_Arch_Irq_Unhandled)                    /* 1023 */

